### ISSUE TITLE
Problem updating with npm

### ISSUE THREAD

**Issue by doudbanks** [hammerjs/hammer.js#1012]
Hi guys,

When we install hammerjs via npm we get version 2.0.7 whereas the most updated version is 2.0.8.

At the moment we are manually including the library by taking it online, saving it, and referencing it.

Do you know when you plan to update the version of hammerjs on npm?

Thanks.

**Comment by arschmitz** [comment]
Hi im not sure why your getting 2.0.7 2.0.8 is the most recent version on NPM updated 4 months ago. https://www.npmjs.com/package/hammerjs

**Comment by arschmitz** [comment]
I do have to admit it looks like i forgot to update the readme with latest release though

**Comment by doudbanks** [comment]
It's weird because when I'm installing hammerjs on npm I do npm install hammerjs@2.0.8 --save and after that it's written 2.0.7 at the top of the hammerjs.min.js file :(

Thanks for your quick reply - very impressive

**Comment by arschmitz** [comment]
Looks like its just a bad header i missed updating it also with the 2.0.8 release. https://github.com/hammerjs/hammer.js/blob/master/hammer.min.js really sorry for the inconvienence :-(

**Comment by doudbanks** [comment]
No problem could you tell us when it's updated please ?

Thanks a lot.

**Comment by arschmitz** [comment]
Its based on tags so the comment will not be updated until 2.0.9 or more likely 2.1.0 is released Old tags cant be changed

**Comment by doudbanks** [comment]
Ok thanks. By the way your personnal website is awesome!
