### ISSUE TITLE
Threshold unstable?

### ISSUE THREAD

**Issue by praghavaji** [hammerjs/hammer.js#1018]
I have an issue with the threshold parameter for horizontal pan events.

The threshold setting only holds for the first horizontal pan event and then returns to a tiny threshold.

I can reset the threshold by scrolling or panning up/down.

Anyone got any ideas about this?

**Comment by runspired** [comment]
Example code?

**Comment by praghavaji** [comment]
Doh! Here it is..

`
// Go modal
$(document).on( 'click touch', '.modal-link', function( event ) {

	// Load modal
	load_modal( entryID );

	// Hammer Time
	modal = document.getElementById( 'modal' );
	var hammertime = new Hammer( modal );
	hammertime.get( 'pan' ).set({ direction: Hammer.DIRECTION_HORIZONTAL, threshold: 200 });

	// Pan events
	hammertime.on( 'panleft panright', function( ev ) {

		// Pan left
		if( 'panleft' === ev.type) {
			var entryID = $( '.entry-right' ).data( 'entry' );
			if( typeof entryID !== 'undefined' && entryID !== currentID ) {
				load_modal( entryID );
				currentID = entryID;
			}
		}

		// Pan right
		if( 'panright' === ev.type) {
			var entryID = $( '.entry-left' ).data( 'entry' );
			if( typeof entryID !== 'undefined' && entryID !== currentID ) {
				load_modal( entryID );
				currentID = entryID;
			}
		}
	});		
});
`

**Comment by praghavaji** [comment]
Ok, I can now see that it's the `load_modal()` function that conflicts with hammer. this function simply makes a WordPress AJAX call. This seems to reset the threshold to 10 :/

**Comment by praghavaji** [comment]
I fixed this by adding an ev.distance check, like this..

// Pan left
```
if( 'panleft' === ev.type) {
	var entryID = $( '.entry-right' ).data( 'entry' );
	if( typeof entryID !== 'undefined' && entryID !== currentID ) {
		// console.log( 'pan left', entryID, currentID, ev.distance);
		if( ev.distance > 199 ) {							
			load_modal( entryID );
			setTimeout(function(){
				currentID = entryID;
				setupHammer();
			}, 1000);
		}
	}
}

```

**Comment by runspired** [comment]
Interesting, I'm a little surprised the ajax call is interfering with the detection. Is there unstable DOM underneath the user's finger?

**Comment by praghavaji** [comment]
I'm not sure @runspired ..

I can't see any alarming code in the AXAJ call. If I had more timeI'd run some tests but we're up against it here, as ever.

Thanks for your interest and responses.

Bestest,

m.
