### ISSUE TITLE
How to distinguish 3 point from 2 point pan?

### ISSUE THREAD

**Issue by morious** [hammerjs/hammer.js#1021]
Hi,
I am trying to create a behavior where for 2 points pan I do one thing and for three points pan I do another.
The way I go about it is to instantiate two hammer managers each with a different pan configuration, one for 2 points and one for 3 points.

I noticed the following:
1. The IsFirst flag is never set to true.
2. The behavior is that when I pan with 3 points and lift one finger up the pan with 2 points event handlers kick in immediately.
The desired behavior is to not process a 2 points pan unless started with 2 points pan and same for 3 points.

Any ideas?

**Comment by arschmitz** [comment]
you need to use the recognizeWith and requireFailure options here is an example using single and double tap same idea http://codepen.io/jtangelder/pen/pBuIw

**Comment by morious** [comment]
@arschmitz thanks! I tried that and could not get it to work with pan.
I am going to give it a try again though as I am just getting familiar with these concept. 
Will post the results shortly...

**Comment by morious** [comment]
@arschmitz,
here is what i did:
```
let hm = new Hammer(el, {});
hm.add(new Hammer.Pan({event: "pan2", pointers: 2}));
hm.add(new Hammer.Pan({event: "pan3", pointers: 3}));

hm.get('pan3').recognizeWith('pan2');
hm.get('pan2').requireFailure('pan3');

hm.on("pan2 pan3",(ev)=>{
   console.log(ev.type);
});
```

That worked to recognize both pan 2 pointers and pan 3 pointers but failed to isolate them.
Meaning when started a 3 point pan and lifted a finger the 2 points pan kicked in right away.

I managed to solve it using state management and calling stop when switching between states.

ex:
```
let hm = new Hammer(this._elementRef.nativeElement, {});
hm.add(new Hammer.Pan({event: "pan2", pointers: 2}));
hm.add(new Hammer.Pan({event: "pan3", pointers: 3}));

hm.get('pan3').recognizeWith('pan2');
hm.get('pan2').requireFailure('pan3');
let lastEvent = "";
hm.on("pan2 pan3",(ev)=>{
   if(lastEvent!=""){
        if(ev.type != lastEvent){
            hm.stop(true);
           lastEvent = ev.type;
           return; //force stopping event cycle and return
       }
   }
   else{
        lastEvent = ev.type;
   }
   console.log(ev.type);
});
```

Can you think of a proper approach to this?

**Comment by arschmitz** [comment]
@morious you could also use http://hammerjs.github.io/toggle-recognizer/ to disable the 2 point pan when you get pan3start then re-inable it on pan3end

**Comment by arschmitz** [comment]
http://jsbin.com/bumeluq/edit?html,js,output

**Comment by morious** [comment]
Thx! i'll give this approach a try.

**Comment by arschmitz** [comment]
Im going to close this since its not an issue with the lib and is just a question. feel free to still comment

**Comment by morious** [comment]
sounds right. thanks!
