### ISSUE TITLE
Pinch example with desktop emulator

### ISSUE THREAD

**Issue by nuthinking** [hammerjs/hammer.js#1028]
I am testing pan and pinch on Chrome Mac and Windows 10 tablet. Having difficulties having a consistent behavior.

Simple implementation of 'pinch' and 'pan' (without Manager) doesn't seem to work, with the manager it does. Would be great to know why.

With the manager, the tablet fires the right events but the Mac doesn't. Tried also with the Emulator JS which I am not sure 100% if it worked since I am using es6.

Tried:

    import TouchEmulator from 'hammer-touchemulator'
    // react
    export default class extends Component {
            componentDidMount(){

                TouchEmulator();

I am asking for support since the demos at the page: http://hammerjs.github.io/#try-it work consistently on both devices. So it would be good to see their code and understand what I am missing.

Thanks!

**Comment by nuthinking** [comment]
Ok, found a way to correctly include TouchEmulator. All good on Mac now.

**Comment by linweigao** [comment]
Could you share correct way of including TouchEmulator?

**Comment by linweigao** [comment]
Got it!
import * as TouchEmulator from 'hammer-touchemulator'
