### ISSUE TITLE
Scrolling bug (2.0.7)

### ISSUE THREAD

**Issue by georgekosmidis** [hammerjs/hammer.js#1033]
I use hammer for adding "pull2refresh" functionality on a div in a phonegap app...

For some reason when enabled it prevents normal scrolling even in chrome browser (mobile toolbar enabled), while version 2.0.4 was working perfectly...

Here is a fiddle with the problem:
https://jsfiddle.net/georgekosmidis/dhf1yx54/17/

1. Click and hold the mouse, pull down to refresh (working)
2. Click and hold the mouse, push up to scroll (not working)

This line causes the problem... can't do without it ofcourse...

` h.get('pan').set({ direction: Hammer.DIRECTION_VERTICAL });`

**Comment by runspired** [comment]
This is not a bug, that this was working before was likely either an issue in Chrome or a bug in Hammer prior to 2.0.5 whereby touch-action was set improperly. Correct use for this scenario involves configuring touch-action to a value other than `none`. See: hammerjs.github.io/touch-action/
