### ISSUE TITLE
Difference between version 1 and 2 (hammer vs hammer-time)

### ISSUE THREAD

**Issue by pihvi** [hammerjs/hammer.js#1038]
Front page http://hammerjs.github.io/ gives me two options for download. Version 2 or version 1, but I can not find any information which should I use for my case. All I want is to remove the 300ms delay, so I don't need zooming or pinching etc. Version one is 7 times smaller than version 2, so it's better in that sense. What's the difference between the versions?

**Comment by pihvi** [comment]
Hahaa, reading again and seeing how it quite clearly explains the diff right above! :D

**Comment by runspired** [comment]
@pihvi if you are looking to remove the click delay this is the wrong libarary. You want to use hammer-time.  https://github.com/hammerjs/hammer-time
