### ISSUE TITLE
Mouse events not working in Chrome

### ISSUE THREAD

**Issue by ohmycode** [hammerjs/hammer.js#1058]
[Hammer js pinch Demo](https://hammerjs.github.io)

Neither pinch nor any other gesture with multiple finger input is being triggered while emulating  touches holding shift and dragging with the mouse. In Firefox and Safari it's still working.

**Comment by RopoMen** [comment]
Relates https://github.com/hammerjs/touchemulator/issues/13

**Comment by MickL** [comment]
Please close as duplicate of #13
