### ISSUE TITLE
Rotate on center

### ISSUE THREAD

**Issue by dotMastaz** [hammerjs/hammer.js#1070]
Hellllo !!

First, thanks for this great Touch Gestures.

I have implement HammerJs, but when i try to rotate, element don't rotate by the center ?
Any ideas ?

Thanks,
Nico

**Comment by PierBover** [comment]
I haven't tested this, but maybe you could try moving the `transform-origin` CSS property.

**Comment by dotMastaz** [comment]
Yes exactly!  That's run!!
Thanks
