### ISSUE TITLE
Customizing hammerjs in angular

### ISSUE THREAD

**Issue by MurhafSousli** [hammerjs/hammer.js#1102]
I'm using HammerJS with Angular, Currently I load the library with this line
```ts
import 'hammerjs';
```
I need to activate vertical events for `pan` and `swipe`, someone wrote this fix:

> var mc = Hammer(document.body);
> mc.get('pan').set({ direction: Hammer.DIRECTION_ALL });
> mc.get('swipe').set({ direction: Hammer.DIRECTION_ALL });

I tried 

```ts
import * as Hammer from 'hammerjs';

var mc = Hammer(document.body);
mc.get('pan').set({ direction: Hammer.DIRECTION_ALL });
mc.get('swipe').set({ direction: Hammer.DIRECTION_ALL });
```

but It didn't work, can anyone tell how do I set these options in angular environment ?

**Comment by orian** [comment]
https://joshmobley.net/writing/2016/12/24/gesture-support-in-your-angular-2-app-with-hammerjs.html

**Comment by morjanmihail** [comment]
@orian Link is not working anymore. Do you have a working one?
