### ISSUE TITLE
Pressup doesn't work when finger is moved

### ISSUE THREAD

**Issue by Keilost** [hammerjs/hammer.js#1145]
Hello,

I'am using Hammer.js press to record voice (like whatsapp app), but if finger is moved the pressup event isn't fired, I set threshold to a high number but still not working

`		
		var hammertime = new Hammer(startSelector);

		hammertime.get('press').set({
			pointer: 1,
			threshold: 1000
		});

		hammertime.on("press", function(ev) {
			console.log('press');
			startSelector.toggleClass('fa-microphone fa-circle');
			recorder.start();
		});`

**Comment by choskim** [comment]
@Keilost: can you show that this doesn't work with a codepen? Also, I'm unsure if you're using this correctly. You're listening for a "press" event--not "pressup." With this said, if you look at this codepen (https://codepen.io/choskim/pen/RLYebL) and add a high threshold to it, the press event will still get fired.

**Comment by Keilost** [comment]
Hmm, weird... I'am using now another lib, but I tested with hight threshold and worked.. Thx.
