### ISSUE TITLE
SwipeUp & SwipeDown Dosen't work with jQuery.hammer

### ISSUE THREAD

**Issue by riiccardo** [hammerjs/hammer.js#1157]
Here My Example With JQueryHammer ... SwipeLeft & SwipeRight Looks Good But In Vertical Mode (Up & Down) ^-^ Doesn't Work

`  var myElement = $(".box"); `

     myElement.hammer({direction: Hammer.DIRECTION_ALL, threshold: 1, velocity:0.1}).on("swipeup swipedown", function(event) {
      console.log(event.gesture.deltaY);
    })

Please Make A Better Documention For jQueryHammer For Understanding...

1- how to use hammer option in jqueryhammer
2- diffrence between javascript hammer and jqueryhammer
3- how to .set or .get hammer function in jqueryhammer
4- .data hammer in jqueryhammer

Thanks For Ur Greate TouchPlugin Please Give Us Best Answer ^-^ <3 !

**Comment by masilver99** [comment]
Instead of trying to use the jQuery wrapper, wrap the calls to Hammer with jQuery:

```
$('td').each(function () {
    var $this = $(this);
    var h = new Hammer(this);
    h.get('swipe').set({ direction: Hammer.DIRECTION_ALL });

    h.on("swipeup", async function (e) {
        // do something
    });
    h.on("swipedown", async function (e) {
        // do something else
    });
});
```
