### ISSUE TITLE
How to load hammer.js in angular5?

### ISSUE THREAD

**Issue by ft115637850** [hammerjs/hammer.js#1181]
Maybe this is a silly question. 
I try to import hammer.js in .angular-cli.json.
{
  "apps": [
    {
      "scripts": [
        "../node_modules/hammerjs/hammer.min.js"
      ],
    }
}

But the mat-slider still can't drag. Is anything missing?

**Comment by ValeraTychov** [comment]
https://github.com/angular/material2/blob/master/guides/getting-started.md#step-5-gesture-support

**Comment by longgt** [comment]
https://material.angular.io/guide/getting-started#installing-hammerjs
