### ISSUE TITLE
Double tap on IOS 13 Public Beta doesn't work

### ISSUE THREAD

**Issue by mandawino** [hammerjs/hammer.js#1232]
Double tap works perfectly fine on IOS 12 but doesn't work anymore on IOS 13 Public Beta.

The example from the README is the best way to see it : 
https://codepen.io/choskim/pen/vezzwZ

**Comment by barnard-b** [comment]
I can confirm that the linked pen does not work on iOS 13 (Dev Beta 8), but does work in iOS 12.4.1

Personally been having issues with Swipe on iOS 13 as demonstrated by the [official swipe/pan example](https://rawgit.com/hammerjs/hammer.js/master/tests/manual/nested.html), which again, works in 12.4.1 but not 13.

**Comment by mandawino** [comment]
Double tap still doesn't work in new IOS 13.1 Public Beta.
This Beta will be out the 10th of September.

**Comment by nielsoo** [comment]
also 'panstart' event fires, but 'panend' never fires, instead almost instantly 'pancancel' fires .... this all also only on IOS13 beta

**Comment by javiermarinros** [comment]
The official swipe/pan example is still not working on iOS 13 final release 😕
https://rawgit.com/hammerjs/hammer.js/master/tests/manual/nested.html

**Comment by ltq918** [comment]
I can't swipe on the page in iOS13. It seems to be affected by the Point Events option in the Experimental Features of safari. You can slide after closing this option.

**Comment by ltq918** [comment]
In iOS 13, swipe will make the page slide, use the following code to make it work properly.

`   document.body.addEventListener('touchmove', function (e) {
        e.preventDefault() 
    }, {passive: false}) 
`

**Comment by krisatkinson** [comment]
The issue with double-tapping appears to be across the board, not just with Hammer.js. Here is a pure JS example that has the same issue (this is not my jsfiddle, I found it while Googling the double tap issue) -

https://jsfiddle.net/brettwp/J4djY/

**Comment by mandawino** [comment]
The double tap issue isn't present anymore in the last Beta version !

**Comment by ltq918** [comment]
There is no longer a swipe problem in ios 13.1. There is a problem with the iOS 13.0 system.

**Comment by cbettinger** [comment]
To me it seems that the double tap problem has not been solved. On my iPad using iPadOS 13.1.3 the demo on https://codepen.io/choskim/pen/vezzwZ still does not work as expected.

**Comment by barnard-b** [comment]
> To me it seems that the double tap problem has not been solved. On my iPad using iPadOS 13.1.3 the demo on https://codepen.io/choskim/pen/vezzwZ still does not work as expected.

The double tap pen works for me on 13.2 (17B84, iPhone)

**Comment by cbettinger** [comment]
Just to be clear: I am not using a pen. I don't know if this makes any difference.

And an update to iPadOS 13.2 solved the problem for me, too.
