### ISSUE TITLE
iOS13 scrolling and swiping conflict?

### ISSUE THREAD

**Issue by sk29110** [hammerjs/hammer.js#1237]
After upgrading to v13 dialog swiping stop working I have some events registered on swipeleft and swiperight but nothing is called when i swipe diagonally. Is anybody experiencing this? This only happen when the content gets longer than the view size. I am using the latest. 

> hammertime.on('swipeleft',
>             function (ev) {
>                 alert('hello');
>             });

**Comment by longgt** [comment]
Try to turn off the following setting

```
Settings -> Safari -> Advanced -> Experimental Features -> Pointer Events
```

iOS 13 supports Pointer Event, so HammerJS seems to recognize Pointer Event instead of Touch.

**Comment by sk29110** [comment]
But since this is the default option and it's not user friendly we should have the fix or the workaround

**Comment by sk29110** [comment]
I resolved it by listening to hammer.input event.

var myElement = document.getElementById('gallery');
var mc = new Hammer(myElement);

//catch all events hammer input events
mc.on("hammer.input", (ev) => {     
  if(ev.eventType === 8 ){                
    //touch event direction left
    if(ev.direction === 2){          
      //action when swipe left
      //touch event direction right
      }else if(ev.direction === 4 ){              
        //action when swipe right
      }
      }
    });

**Comment by longgt** [comment]
#1084

**Comment by sk29110** [comment]
Thanks.
