### ISSUE TITLE
Hammer and css-transform

### ISSUE THREAD

**Issue by WallyDoodlez** [hammerjs/hammer.js#134]
I realized that hammer does not report the correct position when css-transform is a factor. I have an element that is has -webkit-transform: scale(0.5) and the event is giving me touch positions as if it is not transformed.

Would be nice to know exactly where the even is fired, according to the element's css-transformation matrix

**Comment by nwlieb** [comment]
Hi, this would be a great feature to have and while it is not a common use case, I don't see how it could be resolved by a user's implementation. Please see https://github.com/uber/react-map-gl/issues/299 for the specific use case. Can we reopen this?
