### ISSUE TITLE
Prevent hammer from handling mouse events?

### ISSUE THREAD

**Issue by rymohr** [hammerjs/hammer.js#167]
Sometimes it's nice to handle mouse events totally separate from touch.  Is there a way to just prevent hammer from listening for mouse events instead of having to check the pointer type each time?

**Comment by ivomontigatti** [comment]
umm... this might be very out of date, nonetheless I will post my solution. On the latest HammerJS version you can do the following:

```
/**
 * create new input type manager
 * called by the Manager constructor
 * @param {Hammer} manager
 * @returns {Input}
 */
function createInputInstance(manager) {
    var Type;
    var inputClass = manager.options.inputClass;

    if (inputClass) {
        Type = inputClass;
    } else if (SUPPORT_POINTER_EVENTS) {
        Type = PointerEventInput;
    } else if (SUPPORT_ONLY_TOUCH) {
        Type = TouchInput;
    } else {
      Type = TouchInput;  
    }
    return new (Type)(manager, inputHandler);
}

```

modify the createInputInstance for this one, HammerJS will initialize with ONLY a touchInput handler regardless if touch and/or mouse are supported

**Comment by jasco** [comment]
@ivomontigatti your suggestion saved me some time understanding the different event types.

To avoid modifying the library, I chose to allow the events to bind but only process those where `event.pointType === 'touch'`.  In my case this worked well, though I do block stop further processing of handled events so have not verified whether subsequent dispatching varies based on binding type.
