### ISSUE TITLE
Zoom with pinch

### ISSUE THREAD

**Issue by saibayadon** [hammerjs/hammer.js#17]
Here a quick example of a dirty zoom to pinch, perhaps it can help you in some way...

http://labs.brunolazzaro.com.ar/hammer

**Comment by redgeoff** [comment]
Here's another example for anyone else that comes across this thread: [Pinch Zoom and Pan with HammerJS Demo](http://bl.ocks.org/redgeoff/raw/6be0295e6ebf18649966d48768398252/)

You can find the source code at [Pinch Zoom and Pan with HammerJS](https://gist.github.com/redgeoff/6be0295e6ebf18649966d48768398252)
