### ISSUE TITLE
Working with iFrames

### ISSUE THREAD

**Issue by NirbhayK** [hammerjs/hammer.js#188]
How to get swipe and tap events on iframes embeded in html with Hammer.js?

**Comment by andyyou** [comment]
@mikyweb Sorry for bother I am new to Hammer
I need the same solution but I am not sure how to use `setup()` seems I can't get `Hammer.READY`.

I try to wrap a component into `iframe` that use Hammer, I found out Hammer events binding to outer document not `iframe` one. Could you give me more example

Thanks
