### ISSUE TITLE
Zoom Demo - I added drag functionality and fixed some bugs

### ISSUE THREAD

**Issue by createthis** [hammerjs/hammer.js#20]
Hey, first off, congrats on hammer.js. It is the right tool for the job. Just the right level of abstraction. All of those others try to do too much, IMO.

I've added single finger drag functionality to your zoom demo. I also have a zoom bug fix for you. How do I clone/commit my changes?

**Comment by guicouto** [comment]
After giving the zoom in image , there is a possibility to catch so you can drag just up and down? That is, it is not possible to drag to the left or right.
