### ISSUE TITLE
adding hammer to the body tag in ie10 disables scrolling via touch

### ISSUE THREAD

**Issue by klundberg** [hammerjs/hammer.js#241]
...specifcially with the -ms-touch-action: none style being set. when I set stop_browser_behavior to false this fixes that issue, but then drag hammer events don't properly work since the page wants to scroll.

I'm not really sure what the best solution here is; ideally one could conditionally disable and re-enable default browser behavior when convenient. Our use case is that we want a hold event to trigger an element to become draggable. The browser behavior would be stopped once the hold gesture triggers, and it would then be restarted when the drag event is finished.

**Comment by arschmitz** [comment]
Where do we stand on this now?

**Comment by RByers** [comment]
This was fixed in Hammer a year ago, guess the issue was accidentally left open?
Details: https://github.com/EightMedia/hammer.js/wiki/How-to-fix-Chrome-35--and-IE10--scrolling-(touch-action)

**Comment by arschmitz** [comment]
@RByers Thanks looks like it was also a V1 issue. Just taking over leading this project and trying to wade through some of these really old issues that are still open.

**Comment by prashon** [comment]
Somehow I managed to overcome this issue.. I just commented out a line in the library and it fixed the whole crap. FInd the below function in the touchemulator.js library and just comment the 4th line below i.e,. **preventMouseEvents(ev);** . Thats it.. Yor are done.. Check it on browser and celebrate...

 function onMouse(touchType) {
        return function(ev) {
            // prevent mouse events
            preventMouseEvents(ev);

            if (ev.which !== 1) {
                return;
            }

            // The EventTarget on which the touch point started when it was first placed on the surface,
            // even if the touch point has since moved outside the interactive area of that element.
            // also, when the target doesnt exist anymore, we update it
            if (ev.type == 'mousedown' || !eventTarget || (eventTarget && !eventTarget.dispatchEvent)) {
                eventTarget = ev.target;
            }

            // shiftKey has been lost, so trigger a touchend
            if (isMultiTouch && !ev.shiftKey) {
                triggerTouch('touchend', ev);
                isMultiTouch = false;
            }

            triggerTouch(touchType, ev);

            // we're entering the multi-touch mode!
            if (!isMultiTouch && ev.shiftKey) {
                isMultiTouch = true;
                multiTouchStartPos = {
                    pageX: ev.pageX,
                    pageY: ev.pageY,
                    clientX: ev.clientX,
                    clientY: ev.clientY,
                    screenX: ev.screenX,
                    screenY: ev.screenY
                };
                triggerTouch('touchstart', ev);
            }

            // reset
            if (ev.type == 'mouseup') {
                multiTouchStartPos = null;
                isMultiTouch = false;
                eventTarget = null;
            }
        }
    }
