### ISSUE TITLE
drag problem (and workaround) on certain android stock browsers

### ISSUE THREAD

**Issue by davidmarkclements** [hammerjs/hammer.js#245]
On certain android stock browsers, sometimes drag events are "stunted" - you can 
move maybe 50px before drag events are no longer triggering - however the release
event doesn't trigger until you release, so it's not down to an early release it's down a bug in these browsers. 

The browser tested on is default stock browser for Samsung Galaxy S3, here's the full UA string:

mozilla/5.0 (linux; u; android 4.1.2 en-gb; gt-i9300 build/jzo54k) applewebkit/534.30 (khtml, like gecko) version/4.0 mobile safari/534.30

Found a workaround here: http://stackoverflow.com/questions/10246305/android-browser-touch-events-stop-display-being-updated-inc-canvas-elements-h/10495741#10495741

Essentially attach preventDefault touchstart/move/end events to the document. This of course messes up the ability to scroll, so it would have to be done dynamically each time. 

Eg from SO: 
function touchHandlerDummy(e) {
    e.preventDefault();
    return false;
}
document.addEventListener("touchstart", touchHandlerDummy, false);
document.addEventListener("touchmove", touchHandlerDummy, false);
document.addEventListener("touchend", touchHandlerDummy, false);

**Comment by cipsicko** [comment]
I had the same problem and fix it with this configuration:
myVar = new Hammer(s.itemActive, {
	dragLockMinDistance: 10,
	dragBlockHorizontal: true,
	drag_lock_to_axis: true,
	drag_block_horizontal: true,
    	drag: true
}).on("dragleft dragright release", handleHammer);

the issue was on this configuration:

myVar = new Hammer(s.itemActive, {
	dragLockMinDistance: 10,
	dragBlockHorizontal: true,
}).on("dragleft dragright release", handleHammer);

**Comment by arschmitz** [comment]
Im going to close this since the drag events were removed in v2
