### ISSUE TITLE
Hammer.js repo with just the .js files for use with Bower

### ISSUE THREAD

**Issue by harsaharsa** [hammerjs/hammer.js#253]
Bower always copies all the files from the repository, and just to keep my app's file structure cleaner, it would be great to have a repository that just contains the latest release version of Hammer.js, i.e. the contents of the dist folder.

**Comment by arschmitz** [comment]
You can also commit on a detached head this is what many projects do. Im going to close this for now if we want to do anything more in the future we can discuss / open a new issue
