### ISSUE TITLE
ev.gesture.target not updated on Android devices while dragging (update : + iOS)

### ISSUE THREAD

**Issue by CheetahDev** [hammerjs/hammer.js#269]
Hi,

I'm building a webapp with hammer.js and I noticed an issue with drag event. Let me explain in few points what I'm trying to do :
1) I've a list of elements on the left of my screen
2) I've a "drop" area on the right of my screen (which is splitted into 4 parts)
3) The user should be able to drag one element (this element didn't move) from left to right

So : the user touch one element, he drags it virtually to the right and when he's hovering an area, this area is highlighted.

I need two elements : 
- the start element (on touch)
- the end element (on release)

My code works on my computer (FF, Chrome ...), but it fails on Android devices (didn't try on iOS) : if I drag one element from left to right (outputting the ev.gesture.target on drag in a console), the target is not updated. It'll output <.li>...<./li> everytime, even if I'm hovering a div, a h3 or anything else.

You can see what I explain by trying http://eightmedia.github.io/hammer.js/examples/events.html on an Android device. Eventdata target will never change.

Many Thanks,
Cyril.

Edit: I've just tried on iOS, same issue.

**Comment by xuxiaomi** [comment]
how do it?
