### ISSUE TITLE
event.gesture not defined

### ISSUE THREAD

**Issue by DimitrisSevastakis** [hammerjs/hammer.js#288]
When i access my page from my localhost server everything behaves as expected, but when i deploy exactly the same configuration on a server, the object event.gesture is undefined. Instead the gesture object is available in the event.originalEvent object.

**Comment by vko-online** [comment]
`Uncaught TypeError: Cannot read property 'stopDetect' of undefined` because of `event.gesture.stopDetect()`
This is still active issue

**Comment by aymanosman** [comment]
+1 I get this issue with IE10 on Win8

On an <img> tag event.gesture == undefined (occasionally)

**Comment by AnnVoV** [comment]
use event.gesture.scale
