### ISSUE TITLE
Doubletap firing on single tap

### ISSUE THREAD

**Issue by martinkorner** [hammerjs/hammer.js#292]
Testing the Hammer.js demo at http://eightmedia.github.io/hammer.js/ on a 1080p touchscreen triggers the 'doubletap' message on a single tap most of the time, only sometimes triggering just the 'tap' message.
The only way I have been able to get around this is to ignore any taps which occur shortly after previous tap.

In jquery.hammer.js I have replaced from line 1114 (check if double tap) section with the following code:
```javascript
if(prev && prev.name == 'tap' &&
	(ev.timeStamp - prev.lastEvent.timeStamp) < 140 &&				// less than 140ms ago
	(prev.lastEvent.target.offsetLeft - ev.target.offsetLeft)==0 &&	// same h target
	(prev.lastEvent.target.offsetTop - ev.target.offsetTop)==0) {	// same v target
	console.log('no tap');
} else {
	console.log('tap');
	Hammer.detection.current.name = 'tap';
	inst.trigger(Hammer.detection.current.name, ev);
}
```

This now catches any secondary taps which occur (and of course won't trigger any doubletaps) but feels very hacky. Does anyone know anything about this issue?

**Comment by arschmitz** [comment]
Im going to close this since its a v1 issue and things were re-written if you still see this with v2 pleas comment and we will re open

**Comment by wizajay** [comment]
Its still in v2. Hammer.JS - v2.0.6. I use google chrome on asus t100, w8. Have two divs working on 'tap', one fires right, the other fires twice when tapped. But works fine on click.

Hammer(document.getElementById("back_icon")).on("tap", function() { CODE }); 

have I made any mistake?

**Comment by wizajay** [comment]
Fixed for the time being, by setting and retrieving values from local-storage. Thank you Hammer.js

**Comment by uudruid74** [comment]
I'm seeing this in 2.0.8.  I'm using the jQuery wrapper and domEvents: true if that makes a difference.  I'll try to just ignore one of them for now.

**Comment by arschmitz** [comment]
@uudruid74 This would be expected when using the jQuery Wrapper AND domEvents true the jquery triggers events directly on the jQuery event system. This same event system works fine with DOM events so you get both. if your using domEvents:true you don't need the jQuery Wrapper

**Comment by uudruid74** [comment]
I thought the jQuery wrapper was just for the syntax sugar.  It will be a bit of rewrite to remove it.  Thanks for the info.
