### ISSUE TITLE
drag_lock_to_axis doesn't seem to work on iPhone safari/chrome.

### ISSUE THREAD

**Issue by sg0891039** [hammerjs/hammer.js#293]
I have tested on android chrome and desktop chrome and it works as expected. On iPhone the drag_lock_to_axis:true will work only if the drag is extremely fast, during a slow drag it does not work.

I have a simple example (webkit only) at:
http://ramenlife.com/hammer/

In the example dragging left and right on a card should flip it, if the drag direction is vertical, the card should not flip. On iPhone if a slow vertical drag is initiated, the card can still be flipped by dragging horizontally.

I have console.log(event.gesture.direction) so you can see the event direction, on iPhone, the direction is never locked to an axis on a slow/midspeed drag

**Comment by arschmitz** [comment]
Im going to close this since its about drag and this was removed in v2.
