### ISSUE TITLE
Tap event triggers twice on Chrome, FF in Mac OS

### ISSUE THREAD

**Issue by protobi** [hammerjs/hammer.js#302]
The tap event seems to fire twice in v1.05 release and v1.06dev when delegated.  This seems similar to an issue recently closed: 
https://github.com/EightMedia/hammer.js/issues/234

 ```javascript
      $(this.el).hammer().on("tap", ".label", function(event) {
          console.log("Tap! "+event.timeStamp);
          console.log(event);
        });
```
yields two `tap` events with only 3 nanoseconds difference. 

```javascript
Tap! 1372188081692 elementtree.js:95
x.Event {type: "tap", gesture: Object, timeStamp: 1372188081692, jQuery110100932544965762645: true, isTrigger: 3…}
 elementtree.js:96
Tap! 1372188081695 elementtree.js:95
x.Event {originalEvent: x.Event, type: "tap", isDefaultPrevented: function, timeStamp: 1372188081695, jQuery110100932544965762645: true…

```

 I'm pretty sure it's the same single object, not duplicated.  `event.stopPropagation()` and `event.preventDefault()` didn't seem to help.   But adding this throttle seems to work for now:

```javascript
        var freeze = false;
        $(this.el).hammer().on("tap", ".label", function(event) {
          console.log("Tap! "+event.timeStamp);

          if (freeze) {
            freeze = false;
            console.log("event throttled");
          }
          else {
            freeze = true;
            console.log("event accepted");
            onTapLabel();  
            setTimeout(function() { freeze = false; },50);
          }
        });
```

**Comment by arschmitz** [comment]
Since this is super stale im going to close it @bmesing if you can still reproduce this with v2 please make a simple test case using jsfiddle or jsbin or something like that and we will reopen and look into it.

**Comment by bikb** [comment]
It is still happening on Chrome 47 on Win10 Touch device!
