### ISSUE TITLE
IE fires click event on drag/swipe release whereas Chrome/FF do not

### ISSUE THREAD

**Issue by bighuggies** [hammerjs/hammer.js#308]
[See this fiddle](http://jsfiddle.net/w2cGz/6/)

I'm trying to build a carousel type widget but I'm having some troubles with IE.

In the above example, when you drag the carousel a mouse click event is triggered when you release the mouse and you are navigated by the link (only in IE). This also occurs when using touch or pen input on IE10.

In Chrome/WebKit/Firefox the drag/swipe events don't fire a click event on release and the carousel behaves as expected.

This is an inconsistency which should be fixed, although I don't know which is the correct behaviour.

Any hints as to how to prevent navigation in my carousel when dragging is finished would also be appreciated.

**Comment by arschmitz** [comment]
Im going to close this its a v1 issue and things were re-written for v2
