### ISSUE TITLE
All the End Events not firing on Android after scrolling.

### ISSUE THREAD

**Issue by vtecman** [hammerjs/hammer.js#316]
not sure if anyone else is getting this problem,  

I have added the jquery.hammer library into my site,  I am trying to get the drag/hold events to work,  everything works smoothly on ipad, but on Andoird tablets ( have tried on Galaxy tab1, tab2, and Xoom)  if I first open the site all the gestures seems to work fine,  but once I scroll the parent div, it just won't detect the gesture anymore until I single tap on any element on the screen.  then I can drag/hold elements just fine.  

I added tracing against all the event "handler" functions and I can see that from logcat that without scrolling all the event cycle is in "start" "move" "end" pattern,  whereas if I scroll the page,  the cycle I get is only "start" "move"  the "END" events doesn't seems to fire?     but once I single tap on an element, the whole event cycle will become normal again.    

can anyone give me any suggestion on what to look for to resolve this problem?

BTW,  thanks for this wonderful library......  happy coding:)

**Comment by vladtret** [comment]
I'm using hammer 2 with backbone. also faced this issue. here is my fix:

this.$el.hammer({ domEvents: true }); // here $el is body and this line enables hammer to work on each dom el in the app
this.$el.data("hammer").get('pan').set({ enable: false }); // add this line. this fixes the issue. pan continues working in child elements, where it is added as:
$childEl.hammer().on("pan", ...);
$childEl.data("hammer").get('pan').set({ direction: Hammer.DIRECTION_ALL, threshold: threshold });

hope this helps somebody

**Comment by vladtret** [comment]
the issue reproduces on android, desktop chrome
