### ISSUE TITLE
Drag stops short on Nexus 2013 and Galaxy Tab 3

### ISSUE THREAD

**Issue by pete-mckinney** [hammerjs/hammer.js#337]
We are experiencing problems with dragend / release firing prematurely on these two devices.  The Nexus is Android 4.3 and the Tab is 4.1.2.  Both devices are using Chrome as the browser.

The user attempts to drag and can only drag it a very short distance in our application with either of these devices.  It looks like a touchcancel is triggering the dragend.  We can reproduce this easily with the events.html sample on the nexus, but the Tab will not reproduce the problem there.

**Comment by arschmitz** [comment]
Im going to close this since drag was removed in v2
