### ISSUE TITLE
The drag and dragend event do not fire when the mousemove or mouseup event occurs outside the element that is drag enabled.

### ISSUE THREAD

**Issue by shyam-habarakada** [hammerjs/hammer.js#347]
I haven't (yet) looked closely at the hammer.js code, but my guess is that, for the drag events, it's binding all the events to the target element. A solution, which I will try in a bit, it to bind mousemove and mouseup events to the entire document after the dragstart has taken place.

This would however require some more state-tracing and potentially assume that drag events are mutually exclusive with other gestures.

Can anyone comment on the mutual exclusivity of gestures in the context of the document? For example, can a drag event and a swipe event both be taking place at the same time? is this something allowed / supported by Hammer?

**Comment by Ziriax** [comment]
I'm not sure if this fixed, but to solve this, instead of listening to move/end events on the element itself, one should listen to the window (or some configurable container) for these events. The start event should be on the element itself.
