### ISSUE TITLE
Event listener leak in Hammer.Instance constructor

### ISSUE THREAD

**Issue by felixlaumon** [hammerjs/hammer.js#353]
We are reviewing our web app performance and found a possible memory leak from hammer.js.

Whenever a Hammer instance is created (i.e. calling `Hammer(el)`), an anonymous event handler will be attached to `Hammer.EVENT_START`

````js
Hammer.Instance = function(element, options) {
 ...
 Hammer.event.onTouch(element, Hammer.EVENT_START, function(ev) {
        if(self.enabled) {
            Hammer.detection.startDetect(self, ev);
        }
    });
  ...
````

(from [here](https://github.com/EightMedia/hammer.js/blob/master/src/instance.js#L32)) 

Because that function is anonymous, there is no way to unbind it as we cannot get a reference to it. And actual handler is `bindDomOnTouch` which comes from `Hammer.Events` [here](https://github.com/EightMedia/hammer.js/blob/master/src/event.js#L48).

Can you please let me know what is our best course of action? Creating DOM Node and calling Hammer on them is a very common use-case for our web app, so this will be a huge performance problem for us.

I'm more than happy to send a PR but needed some advice. Thanks!

**Comment by arschmitz** [comment]
Looks like this was a v1 issue so im going to go ahead and close this if this still exists with v2 please comment and we will reopen this issue
