### ISSUE TITLE
Hammer plugins don't working with require.js

### ISSUE THREAD

**Issue by alex5555** [hammerjs/hammer.js#355]
I am trying to use hammer.js plugins with require.js but I have no luck.

Here is my code:

requirejs.config({
  paths: {
      "jquery": ('**proto**' in {}) ? "lib/zepto" : "lib/jquery",
      "hammer-jquery": "lib/jquery.hammer",
      "hammer-showtouches": "lib/hammer.showtouches",
      "hammer-fakemultitouch": "lib/hammer.fakemultitouch"
  },
  shim: {
      "jquery": {
          exports: "$"
      },
      "hammer-showtouches": {
          deps: [ "hammer-jquery" ],
          exports: "Hammer.plugins.showTouches"
      },
      "hammer-fakemultitouch": {
          deps: [ "hammer-jquery" ],
          exports: "Hammer.plugins.fakeMultitouch"
      }
  },
  waitSeconds: 30
});

requirejs(["jquery","hammer-jquery","hammer-showtouches","hammer-fakemultitouch"], function ($,Hammer) {
    $(function(){
      if(!Hammer.HAS_TOUCHEVENTS && !Hammer.HAS_POINTEREVENTS) {
            Hammer.plugins.showTouches();
            Hammer.plugins.fakeMultitouch();
          }
    });
});

And here is the error:

Uncaught TypeError: Cannot read property 'plugins' of undefined hammer.showtouches.js:7

Uncaught TypeError: Cannot read property 'plugins' of undefined require.js:8

Uncaught TypeError: Cannot read property 'plugins' of undefined hammer.fakemultitouch.js:7

Uncaught TypeError: Cannot read property 'plugins' of undefined require.js:8

I have tried to include Hammer in shim config with no luck (I think that it's not necessary beacause fixed version of jquery.hammer is compatible).

**Comment by othmaan** [comment]
I've the same error when trying to configure Karma test runner.  I use angular.hammer & hammer of course. I got this message...
"HammerJS (window.Hammer) is undefined but is necessary"
