### ISSUE TITLE
Humble request for a new method `.trigger`

### ISSUE THREAD

**Issue by Fresheyeball** [hammerjs/hammer.js#365]
I would very much like something like a `.trigger` method. This would be useful for unit testing, as the unit test could directly trigger a hammer.js event. Preferably I would be able to pass in a mock hammer.js event object.

What do you say?

**Comment by arschmitz** [comment]
Im going to close this since i think we are going to move to actual functional testing with real events using webdriver.

**Comment by achikin** [comment]
Unfortunately not all drivers support this. I'm faced with nightwatch.js and I'm trying to trigger 'panleft' event.
