### ISSUE TITLE
Pinch scale jumps if you don't release both fingers at exactly the same moment

### ISSUE THREAD

**Issue by rymohr** [hammerjs/hammer.js#380]
If you're pinch zooming and you release one finger slightly before the other `gesture.scale` gets reset.

What's the suggested way to avoid this from happening?

**Comment by natsu90** [comment]
Hi, anyone still have this problem? Even after applied rymohr solution.

**Comment by briancodes** [comment]
@natsu90 I found that disabling `pan` for a few milliseconds on `pinchend` works

```
switch (event.type) {
            case 'pinchend':
                this.manager.get('pan').set({ enable: false });
                window.setTimeout(() => {
                    this.manager.get('pan').set({ enable: true });
                }, 100);
                break;
}
```

**Comment by paulstevenuk** [comment]
> @natsu90 I found that disabling `pan` for a few milliseconds on `pinchend` works
> 
> ```
> switch (event.type) {
>             case 'pinchend':
>                 this.manager.get('pan').set({ enable: false });
>                 window.setTimeout(() => {
>                     this.manager.get('pan').set({ enable: true });
>                 }, 100);
>                 break;
> }
> ```

Thank you - this really helped me!
