### ISSUE TITLE
Swipe, DoubleTap, Pinch doesn't trigger on Android Nexus 10 Chrome 30

### ISSUE THREAD

**Issue by louiswilbrink** [hammerjs/hammer.js#388]
I am developing a webapp, testing on both (iPad 4 | Chrome 30) and ( Nexus 10 | Android 4.3 | Chrome 30).

I have been seeing a discrepancy in behavior between the two.

I wrote this plunkr to demonstrate, but the behavior I'm seeing is:  "pinch", "doubleTap", and "swipe" does not get triggered on the Nexus 10.

http://embed.plnkr.co/OkFBsl5JGE3h7AqfQFCd/preview

"drag" and "tap" are fine, I haven't tested all the commands yet, but these are crucial.

**Comment by arschmitz** [comment]
This is a v1 issue so im going to close it if there are still issues with latest code please open a new issue
