### ISSUE TITLE
Swipedown gesture not working in Chrome 30 on Android 4.3

### ISSUE THREAD

**Issue by theirf** [hammerjs/hammer.js#394]
I'm trying to listen for the swipedown gesture on the body in Chrome 30 on Android 4.3

The following implementations do not work / do not cause the alert inside to fire:

    var gesture;
    Hammer(document.body).on('swipedown', function(e){
        gesture = e.gesture
        alert(gesture.distance+", "+gesture.deltaY+", ");
    });

    var gesture;
    var hammertime = Hammer(document.body);
    $(hammertime).on("swipedown", function(e){
        gesture = e.gesture;
        alert(gesture.distance+", "+gesture.deltaY+", ");
    });

**Comment by arschmitz** [comment]
Since this is about drag its a v1 issues drag was removed in version 2 so im going to close this.
