### ISSUE TITLE
Chrome 30 (desktop): drag with right mouse button not detected

### ISSUE THREAD

**Issue by matejk** [hammerjs/hammer.js#396]
When developing a web application that shall work in desktop and mobile browsers we wanted to have shortcuts with right mouse button on desktop browsers.

We use dragstart/drag/dragend events and detected desktop browser by verifying ev.gesture.srcEvent object type. Mouse button is then read from the srcEvent (evt.buttons or evt.button or evt.which).

This works as expected in Firefox and IE10, however it does not work in Chrome 30: dragstart is not fired at all on right button.

I inspected the code of Hammer and found out that detection is based on property e.which (=== 1). FF and IE10 set e.which to 1 and e.button or e.buttons accordingly.

Chrome sets e.which to 3 and e.button to 2.

I propose to change the button detection to use event properties in this order:

* e.buttons > 0 (or selectively) (DOM level 3)
* e.button
* e.which (non-standard)

Reference:

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent.buttons

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent.button

http://msdn.microsoft.com/en-us/library/ie/ff974884(v=vs.85).aspx

**Comment by arschmitz** [comment]
Closing this since its about drag which was removed in v2
