### ISSUE TITLE
"Release to refresh" message never shown

### ISSUE THREAD

**Issue by bbsam** [hammerjs/hammer.js#398]
Hi,

When we pull down and the slide_down exceeds the breakpoint then the text should be shown as "Release to refresh". Instead it is always showing "Pull to refresh".

I have also found the fix for this issue. Is there a way to submit the same? Or do you want me to submit the fix in this issue description itself.

Awaiting your response.

**Comment by arschmitz** [comment]
Closing this due to age and inactivity also there is no longer any pull to refresh support / examples
