### ISSUE TITLE
drag event - event.gesture undefined (intermittent) on img element

### ISSUE THREAD

**Issue by phodude** [hammerjs/hammer.js#399]
When dragging on an img element, the event.gesture is undefined.  Using latest: 1.05.

I changed the element to a div with a background, instead of an img with src.   
All other sibling elements (spans & divs) perform as expected.

**Comment by aymanosman** [comment]
+1 I get this issue with IE10 on Win8

On an <img> tag event.gesture == undefined (occasionally)

**Comment by arschmitz** [comment]
Closing this as a version 1 issue drag was removed on v2
