### ISSUE TITLE
Regarding pull-to-refresh issue

### ISSUE THREAD

**Issue by bbsam** [hammerjs/hammer.js#403]
Hi,

I am writing an application for BB10 webworks (768*1280). In my application I have created a container under which the content is shown. Content is occupied 768*2067 which is 2 pages in height. When I trigger pull-to-refresh being on the top of the container, it works fine, no issues observed. When I scroll down the container, lets say I am at the end of the container and when I try to scroll up to see the content at the top it triggers pull-to-refresh action instead of scrolling up the container to the top.

Can some one help to understand if the approach is wrong or a known issue from Hammer.js.

Similar behaviour is observed in the example "Pull-to-refresh.html".

Thanks in advance.

**Comment by arschmitz** [comment]
Closing this due to age and inactivity this is from V1 also pull to refresh was removed
