### ISSUE TITLE
Sometimes event is fire at second attempt

### ISSUE THREAD

**Issue by fray88** [hammerjs/hammer.js#409]
I've been trying with different events through the jquery hammer library and, in some cases, the event is fire at the second attempt of touch it. The events I've been trying are "touch" and "tap". I've been able to launch them from the safari console (debugging on iOS) using $(selector).trigger('touch'), so it looks like the event is properly bind. It's the same in Android. It happen just in no cases, and digging on the html structure I can't watch anything weird. Could it be that some css breaks the first attempt?

**Comment by arschmitz** [comment]
These sound like different issues on different versions. I'm closing this if you still have this issue with latest code please opens new issue with a small test case
