### ISSUE TITLE
Focus set on input underneath an overlay when removing it on tap

### ISSUE THREAD

**Issue by gabrielmaldi** [hammerjs/hammer.js#411]
I have a menu, upon selection (tap on one of its items), I remove the menu and now an input is shown where the tapped menu item was.

That input gains focus and the keyboard is shown (on devices, of course).

Calling

event.gesture.preventDefault();

fixes it on iOS, but not on Android. With this fix, this only happens on Android's Internet Browser (not Chrome) and on pre KitKat devices (KitKat replaces the default browser with Chrome 30).

I also tried calling:

event.stopPropagation();
event.gesture.preventDefault();
event.preventDefault();
event.gesture.stopPropagation();
event.gesture.stopDetect();

together, to no avail.

http://jsfiddle.net/yYJ4P/

Can anyone think of a quick workaround to use while the real issue is addressed?

**Comment by runspired** [comment]
This occurs because ghost clicks don't maintain the original target, will be addressed in #808
