### ISSUE TITLE
correct_for_drag_min_distance not working as I would expect when multiple different gestures are performed in one touch sequence

### ISSUE THREAD

**Issue by CrowdHailer** [hammerjs/hammer.js#422]
This drag offset correction seams to be only applied to the first time that dragstart is fired in a selection of gestures. 

For example when dragging then pinching then dragging again. The deltaX/deltaY values in the second drag are calculated from the position of dragstart for the first event. This causes unwanted jumping when navigating my graphic.

Is there are way to change this or is it deliberate?

**Comment by arschmitz** [comment]
Closing this due to age and inactivity this is from V1 and drag was removed
