### ISSUE TITLE
Fake MultiTouch plugin breaks when using Django Compression v1.2

### ISSUE THREAD

**Issue by thisjustin** [hammerjs/hammer.js#426]
The double hyphens used in the fake multi touch plugin are incorrectly minified by Django Compression v 1.2 and result in JS syntax errors. The math is also just plain confusing (subtracting a negative number when you could just add a positive number).

**Comment by marlocorridor** [comment]
@jaap3, could i get a clue where I could get the fixed file? Fake multi touch plugin is missing on the current files.
