### ISSUE TITLE
Distinguishing between swipe and drag

### ISSUE THREAD

**Issue by mikagenic** [hammerjs/hammer.js#428]
How can swipe and drag be distinguished on the same element ? I tried:

Hammer(blueDiv).on('swipe', function(e) {
     e.gesture.stopDetect();
     e.gesture.preventDefault();
     alert('swipe');
});
    
Hammer(blueDiv).on('drag', function(e) {
     alert('drag');
});

(http://jsfiddle.net/crEEN/)

But I just get the alert for drag and not swipe.
What I need is _just_ swipe event for a quick swipe, and _just_ drag event for longer drag

any help ?

**Comment by arschmitz** [comment]
Closing this due to age and inactivity this is from V1 drag was removed in v2
