### ISSUE TITLE
Windows Phone: drag looses event

### ISSUE THREAD

**Issue by hasch2o** [hammerjs/hammer.js#430]
I use HammerJS for a project I'm working on right now.
It works perfectly on iOS (Safari & Chrome) and Android (Chrome, Firefox, Stockbrowser).
But not on the Windows Phone we have here for testing (Nokia Lumia 920, Windows Phone 8.0).
Especially when I use any Drag related events:
    var element_content = document.getElementById('ed_main');
    if(element_content != null){Hammer(element_content).on('release dragright swiperight dragleft swipeleft', hammerContent);}

The dragleft and dragright are not behaving correctly, when I start dragging, the draggable object is being moved for a split second, but it seems like the browser forgets that I'm dragging something and releases the draggable object.

I tried to do some remote debugging, but I'm in a restricted environment and I can't access the windows phone for remote debugging.

 Anybody had a similar issue? Or any advice on how I can fix that?

Thanks in advance
Cheers H20

**Comment by arschmitz** [comment]
Closing this since its about drag and drag was removed in v2
