### ISSUE TITLE
Not working in Firefox OS

### ISSUE THREAD

**Issue by hazlema** [hammerjs/hammer.js#433]
I am writing an app for FFOS and hammer has some issues.  Some of the tap events never get run.  Here is a quick example I made.  Works in the browser but not in the emu's.

in the emu, the first hold event works but the second tap does not. I think this is a bug or am I doing something wrong....

http://pastebin.com/VpZcNgr6

**Comment by arschmitz** [comment]
Closing this as its an old version 1 issue if this is still reproducible with v2 please comment and we will reopen
