### ISSUE TITLE
Tap not firing on second tap

### ISSUE THREAD

**Issue by lordg** [hammerjs/hammer.js#434]
I have the following script to bind a tab event to boxes. When each box (.person) is tapped, it opens and a description box appears. If another box is tapped, any active boxes are closed, and the new box is opened.

However, if the person taps a box that is already open, it is meant to close the box, but for some reason it doesn't. I've tracked this and the tap event is not being fired on the box when it is tapped a second time once opened. You'll notice the alert call, which doesn't run on the second tap.

Is there meant to be a different binding, or can someone suggest an alternative solution for the 2nd tap? Or is this a bug?

Much appreciated.

	  $(document).ready(function(){
		if (isMobileWebKit) {
			$('.person').hammer().on('tap',
				function(){
					return toggleDescrition(this);
				}
			);
		} else {
			$('.person').hover(
				function(){
					return toggleDescrition(this);
				}
			);
		}
		function toggleDescrition(obj)
		{
			alert($(obj).attr('class'));
			if ($(obj).hasClass('active')) {
				$(obj)
					.removeClass('active')
					.find('.description')
					.animate({margin: '100% 0 0 0'},500,'easeOutExpo');
			} else {
				//check if any other actives, and smooth them out
				if ($('.people .active')) {
					$('.people .active')
						.removeClass('active')
						.find('.description')
						.animate({margin: '100% 0 0 0'},500,'easeOutExpo');
				}
				$(obj)
					.addClass('active')
					.find('.description')
					.animate({margin: '0'},500,'easeOutExpo');
			}
			return false;
		}
	  });

**Comment by arschmitz** [comment]
Closing this due to age and inactivity this is from V1
