### ISSUE TITLE
Some events not triggering after first trigger.

### ISSUE THREAD

**Issue by vanilla38** [hammerjs/hammer.js#443]
I just noticed some events as swipeleft / swiperight / tap / etc...

Will trigger on the first move but not on the second and it will re-trigger on the third move and not on the fourth etc...

I didnt noticed it happening with release event this is why i say "Some events".

You can check thir url (All my tests have been done on Iphone):

http://ns3262575.ip-5-39-77.eu/

=> try to swipe right, menu opens.
=> close menu then retry to swipe right, nothing happens.
=> retry again, menu reopens...

As i said before, this is happening on my Iphone.

Does anyone know how to fix this ?

Thanks.

**Comment by arschmitz** [comment]
Closing this due to age and inactivity this is from V1
