### ISSUE TITLE
double swipe required to trigger simple swipe.

### ISSUE THREAD

**Issue by vanilla38** [hammerjs/hammer.js#446]
Hi, i wonder if i'm the only one getting this bug:
when i swipe, on the first time it works.
after that, it's only swiping one time for two swipe.

tested on iphone:
ns3262575.ip-5-39-77.eu

try to swipe right.

This bug is really painful ! all moves except "release" should be done twice to get one trigger...

**Comment by arschmitz** [comment]
Im going to close this since its very old an a version 1 issue if you still see this with latest code please comment and we will reopen
