### ISSUE TITLE
useCapture listener option?

### ISSUE THREAD

**Issue by Reyncor** [hammerjs/hammer.js#450]
jQuery does not support it, Hammer.on() does not support it either. Any way to use hammer with a useCapture mode listener? Even if it means writing native JS.

Use capture allows us to handle events before children see them, and allows us to prevent them from processing it. jQuery does not support it because ie8 does not support it... but for mobile, we have no issues.

**Comment by arschmitz** [comment]
This is old and on v1 if you are interested in working on capture support still feel free to open an issue and start new discussion on the topic based on v2
