### ISSUE TITLE
Pinch gesture fires even when touches don't have the same target

### ISSUE THREAD

**Issue by Bragolgirith** [hammerjs/hammer.js#451]
The setup:
   Two rectangles are registered to a pinch gesture that resizes them.
Expected result:
   The user is able to resize both of them simultaneously and independently.
What actually happens:
   Rectangles are getting scaled even when there aren't two touches on them - only one touch on the target is required; the second could be anywhere on the webpage and the pinch gesture will still fire. This makes it impossible to create a true multi-user application (where two people could work on two objects at the same time).

The issue is demonstrated here:
http://jsfiddle.net/BYCfZ/41/

Ideally, any transform operations should only consider manipulations that are performed on the same object.

What would be a good way to remedy the situation and allow both objects to scale independently?

**Comment by arschmitz** [comment]
Closing this due to age and inactivity this is from V1
