### ISSUE TITLE
allow middle mouse button (and maybe right)

### ISSUE THREAD

**Issue by indus** [hammerjs/hammer.js#461]
I´m using the "fakemultitouch" plugin alot. I think it would be nice if it could be triggered not only by the keyboard (shift-key) but also by the middle mousebutton (to rotate something for example).

Its easy to implement...
> hammer.js (line 512)
```javascript
 (sourceEventType.match(/mouse/) && (ev.which === 1 || ev.which === 2))   // mouse is pressed
```
> hammer.fakemultitouch.js (line 38)
```javascript
if (ev.shiftKey || ev.which === 2) {
```

...but it would be nice to get this out of the box.

**Comment by arschmitz** [comment]
Closing this due to age and inactivity this is from V1 also there is a separate repo for the touch emulator
