### ISSUE TITLE
Questions multi-touch drag

### ISSUE THREAD

**Issue by pcdeadeasy** [hammerjs/hammer.js#463]
I have wired drag event to two images, when I start dragging them together I notice that the events I receive are not necessarily corresponding to each element that is dragger. From the code below basically I see the function dragChart being called but the not alternating between the first and the 2nd chart. The issues with this is how do I get the deltaX and deltaY for each of the drags?

$("#img_chart")
            .hammer({drag_max_touches: 5 })
            .on("dragstart drag dragend", function (ev) {
                console.log("test1: " + ev.type);
                dragChart(ev);
            });

    $("#img_chart2")
            .hammer({drag_max_touches: 5 })
            .on("dragstart drag dragend", function (ev) {
                console.log("test2: " + ev.type);
                dragChart(ev);
            });

**Comment by arschmitz** [comment]
Closing this due to age and inactivity this is from V1 also drag was removed in v2
