### ISSUE TITLE
Tap makes false positive for IE on touch devices

### ISSUE THREAD

**Issue by AllNamesRTaken** [hammerjs/hammer.js#467]
Tap event triggers on element with overflow != hidden even when dragging since the tap gesture handler >> function tapGesture(ev, inst) << isnt excluding pointer cancel events, only touchcancel.

Solves by changing row
if (ev.eventType == Hammer.EVENT_END && ev.srcEvent.type != 'touchcancel')
to
if (ev.eventType == Hammer.EVENT_END && ev.srcEvent.type != 'touchcancel' && ev.srcEvent.type != 'pointercancel' && ev.srcEvent.type != 'MSPointerCancel')

**Comment by arschmitz** [comment]
Closing this due to age and inactivity this is from V1
