### ISSUE TITLE
Hammer and requirejs

### ISSUE THREAD

**Issue by tachyon-ops** [hammerjs/hammer.js#473]
Hi,

So... I've made my way up until I've loaded hammer.js in my require app structure, proved by the following output:

-code-
<code>
 try {
      console.log("Hammer(): " + typeof Hammer);
 }
 catch(err){ 
      console.log('Ups... Hammer() gave this error: ', err); 
 }
</code>
-console-

Hammer(): function

So far so good... Now I've tried to put it to work:

-code-
<code>
 try {
      var element = $('#gallery-div');
      var hammertime = Hammer(element).on("tap", function(event){
            alert("Tapped the div! :) hehe");
      });
 }
 catch(err){ 
      console.log('Ups... Hammer(element... bla bla) gave this error: ', err); 
 }
</code>
-console-
<code>
Ups... Hammer(element... bla bla) gave this error:
TypeError: element.addEventListener is not a function

.replace(/[\n]/g, "\n")

</code>

If I <code>console.log( $('#gallery-div'));</code>: ouputs this: <code>jQuery(div#gallery-div)</code>

So... 
I quite need some help from a more experienced js programmer... 

Thanks in advance...!

**Comment by walleykool** [comment]
Thanks
