### ISSUE TITLE
hammer.js interfering with jQueryUI draggable. How to get them both working?

### ISSUE THREAD

**Issue by theirf** [hammerjs/hammer.js#474]
I've successfully implemented jQueryUI draggable, but as soon as I add hammer.js code, the draggable code no longer works.

It is not as soon as I include hammer.js, but as soon as I use the script.

Why is this? How can I get them both to work?

Both the draggable and hammer are applied to `.dataCard` and `#main`

The draggable code works fine here ( with hammer implementation commented out ): http://goo.gl/MO5Pde

Here is an example of the draggable code:

    $('#main').draggable({
        axis:'y',
        revert:true,
	    start: function(event, ui){
	        topValue = ui.position.top;
	    },
	    drag: function(event, ui){
                if(pastBreakpoint === false){
                    $('#searchInput').blur();
                    if(topValue > ui.position.top) return false;
		        if(ui.position.top >= 161){
		            if(pastBreakpoint === false){
			        pastBreakpoint = true;
			            if($('.loadingRefresh').length === 0) $('#main').before('<div class="loadingRefresh"></div>');
			            else{
				        $('.loadingRefresh').remove();
			                $('#main').before('<div class="loadingRefresh"></div>');
			            }
			            $('.loadingRefresh').fadeIn();
			            $('#main').mouseup();
			            setTimeout(function(){
			               location.reload();
			            }, 1000);
			         }
		          }
		        }	
	        }
	    });

Here is the hammer code uncommented and the draggable code not working: http://goo.gl/994pxF

Here is the hammer code: 

    var hammertime = Hammer(document.getElementById('main'), {
	    transform_always_block: true,
	    transform_min_scale: 0
    });

    var posX = 0,
        posY = 0,
        lastPosX = 0,
        lastPosY = 0,
        bufferX = 0,
        bufferY = 0,
        scale = 1,
        last_scale = 1;

    hammertime.on('touch transform transformend', function(ev) {

	    if ((" " + ev.target.className + " ").indexOf(" dataCard ") < 0) return;

	    else manageMultitouch(ev, ev.target); }); 

	    function manageMultitouch(ev, element) { 

		    switch (ev.type) { 
			    case 'touch': 
				    last_scale = scale;
                                    return;
			     case 'transform':
				    scale = Math.min(last_scale * ev.gesture.scale, 10);
				    break;
		        }

		        if(scale <= 0.5) $(element).hide('clip');

		        if(scale > 1.0) $(element).addClass('focused');

		        var transform = "translate(" + 0 + "px," + 0 + "px) " + "scale(" + 1 + "," + scale + ")";
		        var style = element.style;
		        style.transform = transform;
		        style.oTransform = transform;
		        style.msTransform = transform;
		        style.mozTransform = transform;
		        style.webkitTransform = transform;
	     }

**Comment by arschmitz** [comment]
Closing this due to age and inactivity this is from V1 that said i work on the jQuery UI team if this is still an issue create a small test case and ill be happy to work on this.
