### ISSUE TITLE
Android 2.3 ghost tap

### ISSUE THREAD

**Issue by castus** [hammerjs/hammer.js#482]
Hello,

I have an issue on old Android 2.3. When using "touch" or "tap" on some object event is firing, but after short delay (I believe something like 300ms) it seems like Android making additional event in the same place (touchend?). Trying to solve it by adding event.prevent Default() and stopPropagation but no luck. Could someone help me?

**Comment by arschmitz** [comment]
Closing this as stale and a version 1 issue
