### ISSUE TITLE
Properties reset when number of fingers changes

### ISSUE THREAD

**Issue by appsforartists** [hammerjs/hammer.js#484]
Steps to reproduce:
 - Listen for `drag` and `transform`, using `event.gesture.deltaX/Y/scale` to set `image.style.transform`
 - 2-finger drag the image
 - Release one finger and continue dragging

Expected result:
 - The image continues to move seamlessly/intuitively with no perceivable jank.

Actual result:
 - `scale`, `deltaX`, and `deltaY` are recalculated as if the pinch never occurred, causing the image to jump and shrink when the number of fingers changes.

-------

I tried Hammer expecting it to make common use case multitouch easier.  2-finger pan-zooming an image is the quintessential use for multitouch in modern interfaces, yet Hammer makes this harder than it should be.

A better way to handle this may be to dispatch an event between changes (e.g. `gesturetypechange`) and to treat that event as the first event in a new series.  That is, if the 2-finger center is at 100,100 and the user removes a finger leaving only a point at 50,50, treat 50,50 as the origin of all the drag events that occur after the finger is lifted.  The developer can do the same type of cleanup in `gesturetypechange` that he would have done in `release` to persist any transforms that occurred when two fingers were down.  That way, the user has a seamless experience if he inadvertently adds/removes a finger during a transform.

**Comment by arschmitz** [comment]
Sounds like this was solved and its on v1 closing
