### ISSUE TITLE
Scale & rotation reset on release

### ISSUE THREAD

**Issue by mormubis** [hammerjs/hammer.js#485]
I was writting some code about zoom & pinch and I was surprised when I show up that rotation and scale values are reseted.

**Comment by husseinsharif** [comment]
Late here, but some input that might help others...

*all* properties are reset on new gesture, i.e. deltaX, deltaX, scale, rotation, etc.  Each action is independent, and thus this makes sense.

If you would like to save the scale/rotation/etc in your application, you must *save* the last scale/rotation/deltaX to a variable which is in a higher scope (e.g. global) than the event scope.
