### ISSUE TITLE
doubletap doesn't work on IE8

### ISSUE THREAD

**Issue by constantinexue** [hammerjs/hammer.js#510]
jQuery JavaScript Library v1.11.0
jQuery plugin for Hammer.JS - v1.0.5 - 2014-03-18

see #381

**Comment by runspired** [comment]
Closing as this is an issue about v1.  If this is still an issue with v2 please re-report it with a working jsbin to demonstrate the issue.  Bear in mind, v2 doesn't come with a recognizer for doubletap, and requires you to create your own.  The issue being demonstrated should be that a multi-tap recognizer doesn't work on IE8.
