### ISSUE TITLE
There is not dragstart but dragend in a new session  when stopDetect after a swipe in previous session.

### ISSUE THREAD

**Issue by zzm2q** [hammerjs/hammer.js#526]
In session A, when I detect a swipe gesture, i call ev.gesture.stopDetect().
and then dragend will not trigger, this is right.
In new session B after session A, i will receive an dragend event, but there is not dragstart before.

I check Hammer.js code, and I found the following code in Drag.handler:

    // current gesture isnt drag, but dragged is true
    // this means an other gesture is busy. now call dragend
    if(Hammer.detection.current.name != this.name && this.triggered) {
        inst.trigger(this.name + 'end', ev);
        this.triggered = false;
        return;
    }

I think the if statement is not good to handle the previous case.

**Comment by arschmitz** [comment]
Closing this due to age and inactivity this is from V1. Drag was removed in V2
