### ISSUE TITLE
Incompatibility with Touch Punch on iPad2 

### ISSUE THREAD

**Issue by ttback** [hammerjs/hammer.js#54]
My goal is to have drag+drop and double tap working on mobile but I haven't seen an "easy" example to integrate Hammerjs with jQuery Ui's draggable and droppable. Most of the example code requires me to basically write whatever jQuery UI already offers on the desktop. That forced me to use Touch Punch, which solves the problem. But when I try to use $(element).bind('doubletap') with hammerjs, It will interfere with the element's draggable. It will still drag but to a limited distance. I feel that the problem is probably some namespace conflict for the events associated with drag+drop.

So i either have to try to disable Hammerjs's drag and drop handling code or I have to find a way to make Hammerjs working with 
jQueryUI so i don't have to write drag+drop handlers myself. Please let me know if you have some suggestions for making this work. 

Thanks in advance.

**Comment by yeldarby** [comment]
Anyone found a fix yet?

**Comment by adamgins** [comment]
Hi, Anyone find a solution?
