### ISSUE TITLE
hammer.js 1.1.2 breaks on Windows Phone 8

### ISSUE THREAD

**Issue by rodbzro** [hammerjs/hammer.js#543]
Hi there.

I've noticed that from version 1.1.1 to 1.1.2 hammer.js stopped working on Windows Phone 8.

I've tried to apply the changes defined in #430 but had no success. 

It still runs ok on W8/8.1 desktop, but I had to revert to version 1.1.1 to get my project running across Android/iOS/Windows.

Hope this helps!

**Comment by Krishna25Vrinsoft** [comment]
Pinch Zoom in zoom out is still not working in Windows Phone. Can anyone help me to solve this?
I tried a lot. but still facing same

**Comment by runspired** [comment]
@Krishna25Vrinsoft on hammer 1.1.x ? Windows Phone is known to work on hammer 2.0.x

**Comment by Krishna25Vrinsoft** [comment]
@runspired I am using hammer 2.0.4
