### ISSUE TITLE
Hammer.js Examples page in wiki with links to manual/*.html

### ISSUE THREAD

**Issue by eliotsykes** [hammerjs/hammer.js#550]
What do you think about adding a wiki page which links to all of the example pages in the manual/ directory? 

It took me a while to discover all of the examples (not all of them are linked to from http://eightmedia.github.io/hammer.js/ ) and perhaps others are experiencing the same problem and this would save them time when learning hammer.js. 

The links are listed below, however, if there's a way for me to do the work of adding a wiki page with this information please advise. 

Many thanks, Eliot

* [Basic usage](http://rawgit.com/EightMedia/hammer.js/master/tests/manual/basic.html)
* [Pinch zoom](http://rawgit.com/EightMedia/hammer.js/master/tests/manual/pinchzoom.html)
* [Event listener log](http://rawgit.com/EightMedia/hammer.js/master/tests/manual/log.html)
* [Carousel](http://rawgit.com/EightMedia/hammer.js/master/tests/manual/carousel.html)
* [Pull-to-refresh](http://rawgit.com/EightMedia/hammer.js/master/tests/manual/pull-to-refresh.html)
* [Events](http://rawgit.com/EightMedia/hammer.js/master/tests/manual/events.html)

**Comment by arschmitz** [comment]
the site was updated with v2 so im going to close this
