### ISSUE TITLE
Documentation clarifying hammer.js vs. 300ms delay

### ISSUE THREAD

**Issue by eliotsykes** [hammerjs/hammer.js#551]
Docs would be improved with some clarification in the wiki on if hammer.js takes away the 300ms click delay or if another solution (e.g. fastclick) is recommended (or perhaps it isn't?) or how hammer.js can be configured to remove the delay.

If you can clarify it here or point me in the right direction, I'm happy to write the wiki page.

Kind regards and thanks for making hammer.js!
Eliot

**Comment by corgrath** [comment]
Did a page get created for this?

**Comment by runspired** [comment]
There is no page for this.  Using tap as a `fastclick` presents other issues.  You'll usually need to bust the clicks that do occur later, but clicks on inputs and buttons on mobile often need to be allowed.  There's lots of tricky corner cases, so in general with the current (2.0.4) version of Hammer, tap is not a drop in replacement for fastclick.

Closing this in favor of actually producing a solution to these cases in https://github.com/hammerjs/hammer.js/issues/808
