### ISSUE TITLE
Hammer.JS versus HTML5 Drag and Drop

### ISSUE THREAD

**Issue by jokeyrhyme** [hammerjs/hammer.js#553]
So, many modern browsers have native implementations of HTML5 Drag and Drop:
- http://www.whatwg.org/specs/web-apps/current-work/multipage/dnd.html
- http://www.html5rocks.com/en/tutorials/dnd/basics/
- http://html5demos.com/drag

The specification has the following events:
- dragstart
- drag
- dragenter
- dragleave
- dragover
- drop
- dragend

The specification definitely has some problems, and I've recently spent some time working with it and can echo the sentiment found here: http://www.quirksmode.org/blog/archives/2009/09/the_html5_drag.html

Is there room in Hammer.JS's scope to cover some of the features from the specification, but in a sane way? Specifically, the dragenter, dragleave and dragover events are not covered by Hammer currently, and might cover common use cases.

This may be partly related to #230.

**Comment by arschmitz** [comment]
Closing this hammer dropped all drag support in v2

**Comment by alexeypetrushin** [comment]
Can you please clarify - what's the recommended way to implement Drag & Drop? Or hammer.js doesn't implement it at all and some other library supposed to be used?

**Comment by AlbaLopez** [comment]
@alexeypetrushin did you find any solution?
