### ISSUE TITLE
Bug with multiple window objects

### ISSUE THREAD

**Issue by sebbernery** [hammerjs/hammer.js#554]
Hi !
We found a bug with your library. When we have two windows, we want to listen to the events of the second window from the first one.
The problem occurs when the first window declares hammer.js, and adds Hammer listeners on the events of the second window (especially move and end).
The problem seems to be the Hammer.DOCUMENT variable. We wrote a patch to solve the problem. If you want to see the patch we can gladly send it to you.

**Comment by arschmitz** [comment]
Patches are welcome if this is still an issue on V2 im going to close this because its been open for so long its no longer on the current version
