### ISSUE TITLE
Change preventMouse to prevent_mouseevents in Wiki

### ISSUE THREAD

**Issue by IanLunn** [hammerjs/hammer.js#564]
In the Getting Started Wiki under [Gesture Options](https://github.com/EightMedia/hammer.js/wiki/Getting-Started#gesture-options) the option `preventMouse` is listed but doesn't actually do anything (as far as I am aware). After a quick Google, it appears `prevent_mouseevents` is the correct option.

**Comment by arschmitz** [comment]
Im going to close this since i don't believe the section you are referencing exists any more
