### ISSUE TITLE
Hammer tap event on class fires multiple times

### ISSUE THREAD

**Issue by corand** [hammerjs/hammer.js#566]
Catching a tap event of a class, it fires for all the elements with that class. I don't know if it is the desired behaviour, but I don't like it. Just in case, I report it here with a very simple example:

http://jsfiddle.net/acor/hv7n4/

**Comment by arschmitz** [comment]
Im going to close this since it was an issue on v1 if your still facing this in version 2 pleas file a new issue and we will take a look
