### ISSUE TITLE
Recognizing the start and stop of a gesture (Hammer 2.0)

### ISSUE THREAD

**Issue by bradleybossard** [hammerjs/hammer.js#574]
So, in the previous version of Hammer, you could listen for the transformstart and transformend events, but I don't see anything similar to that in Hammer 2.0.  Looking at the events that I listen to, I see there are two properties, isFirst and isFinal, which sound like I could do something similar with.  But, when I print the values out, then don't seem to change.  For instance, running some code similar to below, I get the following output, where I don't see isFirst or isFinal change value.

Anyway, what I am trying to do (and maybe going about it the wrong way) is detect  when a gesture starts, particularly the rotate one, b/c I'm writing an app where I can words that can be rotated, so if a word have been rotated, then the rotation stops and starts again, I need to incorporate the previous rotation into the new gesture (the new gesture always seems to start from angle 0, correct).  Is there a prescribed way of doing this, or is it just that the isFirst and isFinal values aren't being propagated yet?

Thanks for your help in advance.

onRotate 0 0 2 268 hame2.js:124
onRotate 0 0 2 303 hame2.js:124
onRotate 0 0 2 327 hame2.js:124
onRotate 0 0 2 351 hame2.js:124
onRotate 0 0 2 368 hame2.js:124
onRotate 0 0 2 393 hame2.js:124
onPan 0 0 2 160 hame2.js:118
onPan 0 0 2 170 hame2.js:118
onPan 0 0 2 190 hame2.js:118
onPan 0 0 2 214 hame2.js:118
onPan 0 0 2 247 hame2.js:118
onPan 0 0 2 277 hame2.js:118

```
function addHammer(element) {

  var mc = new Hammer.Manager(element, {});
  mc.add(new Hammer.Rotate({ threshold: 0, pointers: 1 }));
  mc.add(new Hammer.Pan({ threshold: 0}));
  mc.on("pan", onPan);
  mc.on("rotate", onRotate);

  function onPan(e) {
    console.log('onPan', e.isFirst, e.isFinal, e.eventType, e.deltaTime);
  }

  function onRotate(e) {
    console.log('onRotate', e.isFirst, e.isFinal, e.eventType, e.deltaTime);
  }

}

var el1 = document.getElementById('id1');
addHammer(el1);
```

**Comment by Ashley2014** [comment]
hi @bradleybossard ,I know this is irrelevant,I'm struggling in debug multi-touch,can you share how you log this infomation?

onRotate 0 0 2 268 hame2.js:124
onRotate 0 0 2 303 hame2.js:124
onRotate 0 0 2 327 hame2.js:124
onRotate 0 0 2 351 hame2.js:124
onRotate 0 0 2 368 hame2.js:124
onRotate 0 0 2 393 hame2.js:124
