### ISSUE TITLE
`doubletap` event are broken in IE10 / WIndows Phone 8

### ISSUE THREAD

**Issue by hxgdzyuyi** [hammerjs/hammer.js#578]
When you double tap fast (  <= ~200ms ), `MSPointerUp` event only triggered once.
When you double tap slow (  > ~300ms ), `MSPointerUp` event can be triggered normal.

Test page

http://jsbin.appfn.com/omavus/6/edit

**Comment by runspired** [comment]
Closing this in favor of #808, but since this appears to be a unique case of pointer events not working properly on a platform, this particular bug should be accounted for in testing. @arschmitz
