### ISSUE TITLE
Unbinding issue in Hammer.instance.off?

### ISSUE THREAD

**Issue by seisiuneer** [hammerjs/hammer.js#579]
Doing a lot of dynamic binding and unbinding in my project, noticed this in the Hammer.instance.off:

    /**
     * unbind events to the instance
     * @method off
     * @chainable
     * @param {String} gestures
     * @param {Function} handler
     */
    off: function offEvent(gestures, handler) {
        var self = this;

        Event.off(self.element, gestures, handler, function(type) {
            var index = Utils.inArray({ gesture: type, handler: handler });
            if(index !== false) {
                self.eventHandlers.splice(index, 1);
            }
        });
        return self;
    },

Utils.inArray appears to be called with only one parameter, so it never matches and as aresult the eventHandlers.splice never occurs....  Even if you pass in self.eventHandlers as the first parameter, it fails due to the use of indexOf, to fix in my case I added a new inGestureArray():
   /**
     * find if a gesturelist contains the gesture
     * @method inArray
     * @param {String} src
     * @param {String} find
     * @return {Boolean|Number} false when not found, or the index
     */
    inGestureArray: function inArray(src, find) {
        for(var i = 0, len = src.length; i < len; i++) {
            if(src[i].gesture == find.gesture) {
                return i;
            }
        }
        return false;
    },

and called it as follows:

   /**
     * unbind events to the instance
     * @method off
     * @chainable
     * @param {String} gestures
     * @param {Function} handler
     */
    off: function offEvent(gestures, handler) {
        var self = this;
        Event.off(self.element, gestures, handler, function(type) {
            var index = Utils.inGestureArray(self.eventHandlers,{ gesture: type, handler: handler });
            if(index !== false) {
                self.eventHandlers.splice(index, 1);
            }
        });
        return self;
    },

With this code in place, I see the eventHandlers getting removed from the array.

**Comment by runspired** [comment]
Closing as this is no longer an issue with v2
