### ISSUE TITLE
Multitouch hold not firing on Android Chrome mobile

### ISSUE THREAD

**Issue by funkydelpueblo** [hammerjs/hammer.js#581]
I tried using the following simple code as a test to see why multitouch hold was not firing events on Chrome mobile (running on Android):

    Hammer(document.querySelector("#dragbox"), {preventDefault: true, transform:false}).on("hold", function(evt){
		document.querySelector("#debug").innerHTML += "H: ";
		document.querySelector("#debug").innerHTML += evt.gesture.touches.length + "...";
	});

This behaved as expected on desktop Chrome. On mobile, the code works fine when the hold has 1 touch, but does nothing when there are multiple touches. In addition, it works as expected when the event is "touch" instead of "hold."

**Comment by runspired** [comment]
Closing as v1
