### ISSUE TITLE
dragLockToAxis does not lock to axis

### ISSUE THREAD

**Issue by festo** [hammerjs/hammer.js#585]
I think, we found a bug:
If we set the dragLockToAxis:true, it is not working sometimes on iPad:
If I start a drag to left, and I start back up across (Like a Z from the bottom) in a dragend event, sometimes I get an "up" direction.

**Comment by husseinsharif** [comment]
I was under the impression this feature was removed in HammerjS 2.x?

**Comment by arschmitz** [comment]
Closing since drag was removed in v2
