### ISSUE TITLE
Documentation consistency

### ISSUE THREAD

**Issue by prettycode** [hammerjs/hammer.js#590]
On the Getting Started page (https://github.com/EightMedia/hammer.js/wiki/Getting-Started), it states:

    You don't need to add the new keyword...
    
Yet, on the Tips & Tricks page (https://github.com/EightMedia/hammer.js/wiki/Tips-&-Tricks), all the examples use the "new" keyword.

So which it is--should I use the "new" keyword, or not? Both appear to work.

I would recommend making the documentation consistent.

**Comment by runspired** [comment]
Closing as V1, but this suggestion is a good one to keep to even in v2 :)  We'll be updating docs once we've finished the first triaging and patching cycle.
