### ISSUE TITLE
When the number of touch points changes, unexpected movement occurs

### ISSUE THREAD

**Issue by mkv123** [hammerjs/hammer.js#596]
I noticed that when the user changes from using two touches for rotation to one touch, dragging, the deltaX and deltaY and velocities jump.

From a usage perspective when doing panning, if the persons fingers don't move, it would be expected that the surface below doesn't move, even if they lift a finger from the screen. However I assume that because the center of the gesture moves, this causes deltaX and deltaY to change which in turn causes a velocity to be generated.

I've worked around the deltaXY changing by detecting when the number of touches changes, or when the finger identifier changes, and compensating for the jump in deltaXY but I haven't figured out how to compensate for the velocity.

Using Hammer.js would be easier if the deltaX, deltaY and velocities would relate to the user's fingers moving on screen, rather than the center point of the gesture changing. Tracking the center point moving does work, but only when the number of touches remains constant through the gesture.

**Comment by morph85** [comment]
I'm having issue even with v2.04 in iOS devices.
The element will rotate 180 degree when i tap using two finger, followed by one finger and vice versa.

I managed to do a work around for this issue using code below, just for temporary measure:
if (ev.rotation < 120 && ev.rotation > -120) {
    // assume user will not twist their finger so much to more than 120 degree
    rotate = ev.rotation;
}

**Comment by mkv123** [comment]
morph85: Thanks for writing that there are still bugs. We are using the old 1.x branch which doesn't have this bug.

**Comment by demrks** [comment]
I'm still seeing deltaX/deltaY jumps with 2.0.4 (Android Chrome, iOS Safari). If you are panning with one finger and you add another finger later (for multitouch panning, pinching etc.) there are unexpected deltaX/deltaY changes.
