### ISSUE TITLE
Support for mousewheel? 

### ISSUE THREAD

**Issue by Dashed** [hammerjs/hammer.js#602]
Is there support for mousewheel in hammer.js v2?

Or can it be easily done with a custom recognizer? I'm unsure how to go about this; the docs seems lacking on this.

**Comment by arschmitz** [comment]
Closing this since there is no bug here

**Comment by acidhax** [comment]
I'd say re-open, mark as improvement, and mark as closed when fulfilled.

**Comment by runspired** [comment]
@acidhax If mousewheel is anything like touchpad, it's not actually possible without a browser plugin.  What google does for zooming via trackpad / mousewheel is convert scroll events to scaling (and then prevent the scroll).

**Comment by runspired** [comment]
(And there's really no reason for us to attempt to normalize scroll events into pinch events)

**Comment by arschmitz** [comment]
@acidhax also see my answer on https://github.com/hammerjs/hammer.js/issues/835 if you need to support mousewheel

**Comment by acidhax** [comment]
Well, I don't think it should become pinch events, it should be a pan event (imho). Scrolling is panning by nature. 

I suppose I'll figure out how to just add it myself.
jQuery is a no go.

**Comment by arschmitz** [comment]
> (And there's really no reason for us to attempt to normalize scroll events into pinch events)

agreed this library is about gesture recognition mousewheel has nothing to do with gestures on touch type inputs

**Comment by therealmarv** [comment]
This all possible without jquery, see the referenced issue here https://github.com/hammerjs/hammer.js/issues/658 or here http://jsbin.com/cuxopid/1/edit?html,css,js,output

The stupid thing is only that gestures on trackpad & desktop browser & Chrome (or IE) is a scroll event+ctrl key! See discussion from Chromium team here https://code.google.com/p/chromium/issues/detail?id=289887 One famous example which works this way on desktop: Google Maps..

So the best is to implement this event yourself. It is not conflicting with hammer.js AFAIK.

**Comment by acidhax** [comment]
Yeah-- I've implemented mousewheel support already-- I'd just like to keep it closer to one-point-of-entry for future site maintenance workers.

**Comment by Xavours** [comment]
Hey Acidhax, how have you done ? Can you share it with us ?

**Comment by acidhax** [comment]
Yeah, it's implemented outside of Hammer.js.

element.addEventListener('mousewheel', _onMouseWheel, false);

**Comment by Xavours** [comment]
Ok, thx, I am gonna try that.

**Comment by wmertens** [comment]
Note, you should use the standard 'wheel', not 'mousewheel'. https://developer.mozilla.org/en-US/docs/Web/Events/wheel#Listening_to_this_event_across_browser
