### ISSUE TITLE
Support for vertical panning?

### ISSUE THREAD

**Issue by cvuong** [hammerjs/hammer.js#604]
I want to do a specific behavior when the user does a vertical pan. Vertical pans do not seem to work until you initiate with a horizontal pan first. If you press on the screen and swipe directly up or down, none of the pan events occur including vertical pan events. If you press on the screen and pan to the left or right and then pan up or down, then vertical pan events are registered. I read in the docs that vertical panning is not supported. Is this a consequence of vertical panning not being supported?

**Comment by Marckon** [comment]
> Vertical pans do not seem to work until you initiate with a horizontal pan first

For the followings, it may be because of the  default 10 threshold.

> ``` javascript
>var mc = Hammer(document.body);
>mc.get('pan').set({ direction: Hammer.DIRECTION_ALL });
>mc.get('swipe').set({ direction: Hammer.DIRECTION_ALL });
>```
and this will add `touch-action: none` like hammer has mentioned, which breaks the scrolling manipulation.
