### ISSUE TITLE
Event delegation?

### ISSUE THREAD

**Issue by normanrz** [hammerjs/hammer.js#607]
Is there some way to use event delegation in v2?

**Comment by stratboy** [comment]
I still can't figure out how to avoid internal elements to interfere with the main panning. 
I mean, I'm using hammer for panning a slideshow. The slideshow elements contain links, which break the norma functions. I tried several things but still can't get the whole thing working.
Obviously, if I put `pointer-events: none;` one the links, or if I delete the links themselves, all works fine. So, I should find a way to stop links from responding to/broadcasting hammer events. How to?
