### ISSUE TITLE
SVG interactivity support

### ISSUE THREAD

**Issue by Zahnstochermann** [hammerjs/hammer.js#622]
I'm working on a project where I want to be able to use hammer.js for zooming and panning an SVG Element. The SVG has interactive Elements inside (eg. onclick: change color, call js-function etc).
Problem: using the object tag to ebned the svg-file into my html file, interactivity is possible but hammer functions are not called. Using the img src-tag, it's the other way around; zoom and panning works fine, but the interactive elements don't change on click. 
I also postet this "problem" with a short code example at stackoverfolw, see here:

http://stackoverflow.com/questions/24913733/hammer-js-and-svg-interactivity

Idk if this is a problem/issue with hammer itself, but I thought maybe someone here has experienced some similar thing. Otherwise I'd consider this issue a feature request ;)

**Comment by runspired** [comment]
Hi @Zahnstochermann, I've successfully used Hammer with SVG often.  To do so I've utilized Hammer's ability to emit DOM Events, and attached the recognizer SVG group (`<g>`) elements on an embedded SVG.
