### ISSUE TITLE
cancel native events on hammer event trigger? eg touch

### ISSUE THREAD

**Issue by annam** [hammerjs/hammer.js#626]
Hello,

I have the following issue: http://stackoverflow.com/questions/24998194/hammer-js-click-triggered-on-dom-elements-behind-tapped-after-tap-action

I hope to prevent it but cancelling native events to prevent them from bubbling/triggering on  other elements after they are used on a hammer instance. for example on touchend (which is used on eg tap) touch (and click) events should not be triggered on other elements. 

is there a way to do this? perhaps with a custom listener? shouldn't it be the default behaviour anyway? I'm using hammer v1 but I can update if this issue can be solved in v2 but not in v1..

I can find a number of similar issues being reported on both this repository and on stackoverflow

thanks!

**Comment by runspired** [comment]
Closing in favor of #808
