### ISSUE TITLE
Replacement for dragLockToAxis?

### ISSUE THREAD

**Issue by njam** [hammerjs/hammer.js#633]
I'm trying to reconstruct the _carousel_ example from version 1.

I have a `pan` recognizer only:

```
  [Hammer.Pan, { direction: Hammer.DIRECTION_HORIZONTAL, threshold: 20 }]
```

I'm trying to implement something like what `dragLockToAxis` was.
Basically to make sure when the content is scrolled vertically, that the horizontal _panning_ doesn't start.
(The opposite is doable with `event.preventDefault()`.)

I can't find such functionality in Hammer 2, is that correct?

Demo: http://jsfiddle.net/rLNX6/2/
(try scrolling vertically and while doing that start a horizontal panning. You will see that the panning is started if you check the console output.)

**Comment by jakecraige** [comment]
I'd love a solution for this as well. I'm hacking together one using the `scroll` event but it's not ideal

**Comment by Benmidi** [comment]
Has anyone figured out a solution?

**Comment by hdezela** [comment]
I have gotten around it with this horrible, hacky, ugly and nasty code...but it seems to work. Basically what I'm doing is keeping a variable with the last pan action (left, right, end). Left and right set the value but only check for vertical movement if the last pan action is false (i.e. panstart).

I'm sure it's not the best way to do it nor is my code a shining example, but maybe it'll give someone an idea on how to do it right.

This code is for an options drawer for an app that lives between {left:-80%} and {left:0%}, out and in, respectively.

<head> has global variables named:
```javascript
var cajonPos = -80; //current drawer position
var lastPan = false; //last pan action
var ancho = window.width(); //browser width for calculations
```

Hammer is called like this:
```javascript
panCentral = new Hammer(document.getElementById('caja'));
panCentral.on("panleft panright panend", function(ev) { navegaCentral(ev.type,ev.deltaX,ev.deltaY); });
```

My pan callback is:
```javascript
function navegaCentral(direccion,distancia,vertical) {
	var pos = cajonPos+Math.ceil((distancia/ancho)*100);
	if(direccion === "panend") {
		// LAST DIRECTION TELLS US WHAT TO DO
		if(lastPan === "panleft") {
			// PULL IT OUT
			animaCajon(pos,'sale');
			cajonPos = -80;
		}
		if(lastPan === "panright") {
			// PUSH IT IN
			animaCajon(pos,'entra');
			cajonPos = 0;
		}
	} else {
		if(pos >= -80 && pos <= 0) {
			if(lastPan !== false) {
				// ALREADY PANNING, DON'T CARE ABOUT VERTICAL
				document.getElementById("cajon").style.left = pos+"%";
				lastPan = direccion;
			} else {
				// NOT PANNING, VERTICAL MATTERS
				if(Math.abs(vertical) < 15) {
					document.getElementById("cajon").style.left = pos+"%";
					lastPan = direccion;
				}
			}
		}
	}
}
```

And finally the function that gets called when the pan ends
```javascript
function animaCajon(actual,direccion) {
	if(direccion === "entra") {
		// ADD UNTIL 0
		if(actual <= 0) {
			var newPos = actual + 1;
			if(newPos < 0) { setTimeout(function(){ animaCajon(newPos,'entra'); },0); }
		}
	}
	if(direccion === "sale") {
		if(actual >= -80) {
			// SUBSTRACT UNTIL -80
			var newPos = actual - 1;
			if(newPos > -80) { setTimeout(function(){ animaCajon(newPos,'sale'); },0); }
		}
	}
	document.getElementById("cajon").style.left = newPos+'%';
	lastPan = false;
}
```

**Comment by nilssolanki** [comment]
I could use this as well, horizontal panning without axis locking creates all sorts of undesirable behaviour. Is the hammerjs team aware of this issue?

**Comment by jakecraige** [comment]
@nilssolanki Hammer JS hasn't been touched in 6 months. My guess is that the project is fairly dead at this point... :/

**Comment by runspired** [comment]
@jakecraige it's not dead, there's an open issue for a new maintainer and I suspect one will materialize soon.

**Comment by njam** [comment]
outdated feature request
