### ISSUE TITLE
offsetdirection returns the opposite direction

### ISSUE THREAD

**Issue by annam** [hammerjs/hammer.js#639]
Hi Jorik,

from my understanding of the docs:
offsetDirection:	Direction moved from it's starting point. Matches the DIRECTION constants.

offsetDirection should return the overall direction that we have moved/swiped

eg if i've panned 100px to the left and then 50px to the right, while direction should return right, the offsetdirection should return left.

more importantly and a simpler test case, if i've panned 100px to the left then both direction and offsetdirection should return left. offsetdirection in this case returns right.

in fact, looking at the code it seems that the direction test is reversed:
function getDirection(x, y) {
     return x > 0 ? DIRECTION_LEFT : DIRECTION_RIGHT;
}

if x is negative then the direction should be left, not the other way around.

then, it seems that the simple direction check is wrong:

function computeIntervalInputData(session, input) {
        var deltaX = last.deltaX - input.deltaX;
        var deltaY = last.deltaY - input.deltaY;
        direction = getDirection(deltaX, deltaY);
}

deltaX should be calculated as input.deltaX - last.deltaX (so that if we've moved to the left, this will return to a negative value).

changing both this and the direction test above should return the correct direction for both direction and offset direction

**Comment by runspired** [comment]
Closing in favor of #806 and #728
