### ISSUE TITLE
Contenteditable cannot be focused - still won't work

### ISSUE THREAD

**Issue by GittiHab** [hammerjs/hammer.js#647]
See title...

Just found out that [this](https://github.com/hammerjs/hammer.js/issues/48) doesn't work for me :cry: 
If I do `var touch = new Hammer(touchableElement, {});` and `touch.hammer({ behavior: { userselect: false } });` Hammer js doesn't work.
If I do `var touch = new Hammer(touchableElement, {behavior: { userselect: false }});` then `contenteditable = true` doesn't work.

What do I need to do? I need touch events and contenteditabled = true

**Comment by runspired** [comment]
Closing as this issue boils down to deprecated v1 code not working in v2
