### ISSUE TITLE
Input event type INPUT_END not fired when specifically listening for panleft and panright

### ISSUE THREAD

**Issue by tweetpixx** [hammerjs/hammer.js#648]
When I set up Hammer like this:

```javascript
var mc = new Hammer(element);
mc.on('panleft panright swipeleft swiperight', handleHammer);
```

I usually don't receive INPUT_END events as expected.
When however I set up Hammer like this and use the event's direction attribute to determine direction:

```javascript
var mc = new Hammer(element);
mc.on('pan swipe', handleHammer);
```

I do receive INPUT_END as expected.
This is not the way it should be now should it :)

**Comment by runspired** [comment]
you would need to add `panend` to your list of events listened too.
