### ISSUE TITLE
how to use backbone view's eventlist with hammer events

### ISSUE THREAD

**Issue by mreinstein** [hammerjs/hammer.js#65]
I'm curious how I'd go about using hammer in a backbone application. I know the demo shows this as the default way to register event handlers in hammer:

``` javascript
var hammer = new Hammer(document.getElementById("container"));
hammer.ontap = function(ev) { };
```

But considering I've got a backbone view which provides a much nicer event declaration system:

``` coffeescript
events:
            'click .imageLogin'    : 'login'
            'click .imageLogout'  : 'logout'
```

I'm wondering how I can go about adding 'tap' support and other hammer events using this syntax. I know that backbone is basically able to parse these and add them as jquery standard events. I _think_ the problem is with hammer being in a seperate namespace, it doesnt know where to find the event handlers for these types of events. has anyone run into this before? I"m curious why create an entirely seperate namespace for hammer rather then punching the jquery library similar to how jquery mobile does it?

thanks! cool library btw. :)

**Comment by animatist** [comment]
Hi, how do you think 7up.nl using hammer alongside backbone? you may check the final-f3b595cbaf.min.js of it
