### ISSUE TITLE
Swipe and Pan cannot work together

### ISSUE THREAD

**Issue by cfernandomaciel** [hammerjs/hammer.js#650]
I tried using both pan and swipe gestures, as soon as the Pan gesture is instantiated, swipe stops working, not leaving any error message to track its reason. It simply stops working.

``` javascript
var myElement = document.getElementById("mainCanvas");       
var mc = new Hammer.Manager(myElement, {});

var panning = new Hammer.Pan({event: 'panning', direction: Hammer.DIRECTION_ALL, threshold: 0})
var swipping = new Hammer.Swipe({event: 'swipping', direction : Hammer.DIRECTION_HORIZONTAL})

mc.add(swipping);
mc.add(panning);

 mc.on('swipping', function(event) {                
             console.log('swipping: ', event);
}

 mc.on('panning', function(event) {                
             console.log('panning: ', event);
}
```

**Comment by mar10br0** [comment]
I would be great if you show how to this with the recognizeWith method. I've tried every possible permutation of recognizeWith/requireFailure on pan and swipe (also switching the order in which pan and swipe are added to the manager). It never recognizes swipes, only pans (with low and high velocities). I could of course check the velocity and do all the distinguishing myself, but that totally defeats the purpose of using hammer!

**Comment by mar10br0** [comment]
So, I got curious into how Hammer is doing this and found the issue: when requiring failure of swipe for a pan (a swipe is a basically a fast pan) the requireFailure function reciprocates the failure-requirement (requires pan to fail to accept a swipe). But a swipe can NEVER be detected without the pan also being detected, so the pan will NEVER be in FAILED state when a swipe is recognised!!
I commented out the reciprocating line and my system started to work as expected: either a pan or a swipe depending on the velocity.

**Comment by josh18** [comment]
I'm also having trouble with this, is there any documentation or demo that can help with this issue?

**Comment by runspired** [comment]
@josh18 very simple to get running with `recognizeWith`, just don't fall into the same trap of also adding a `recognizeFailure` condition.  You'll need to setup your own manager instance, not the default Hammer() configuration.

**Comment by josh18** [comment]
Hmm I think [I tried that](http://jsfiddle.net/mrkurqrq/) but swipe doesn't seem to be recognized, am I doing something wrong?

**Comment by rob-signorelli** [comment]
I realize it's been a few months but in case anyone else sees this issue and is curious what's going on, the swipe *is* being recognized in your fiddle, Josh. If you change the "textContent = ..." to "textContent += ..." you'll see that it was working. The problem is that your example was only displaying the last event that was fired. In this case it was the "pan" event. Using the "+=" you'll see that a number of pan events fire then one swipe event and one pan event to finish. These all just happen so quickly that you don't see the "swipe" get printed before it gets replaced with that final pan.
