### ISSUE TITLE
Prevent tap on parent element

### ISSUE THREAD

**Issue by rgl** [hammerjs/hammer.js#652]
How do we prevent the parent element from receiving the tap event, when we tap a child element?

I've tried to call <code>event.preventDefault()</code> and <code>event.srcEvent.stopPropagation()</code>, but none seem to work :-(

I've placed an example at: http://codepen.io/anon/pen/qDisl

**Comment by kbullaughey** [comment]
I can confirm that `propagating-hammerjs` satisfies my requirements to control propagation. Any chance this could be rolled into hammerjs and enableable as a configuration option?

**Comment by runspired** [comment]
Closing this in favor of #807

**Comment by rimatla** [comment]
Guys, could you instruct me on what the implementation would look like the other way around? 
**- How to prevent an event on a child element?**  

I have a navigation bar that is invoked/shown in the app via a right swipe gesture. 
My issue is that the swipe is currently registered anywhere on the screen, conflicting to a slide carousel, which is a child element, that I've implemented in one of the pages as well.

So I need to either find a way to:
- Isolate/prevent the hammer swipe gesture to be triggered within the slide carousel or
- Adjust the threshold of of the swipe to not be available everywhere on the screen, but limit it to a specific threshold, aka 'edge swipe'.

I'm using Hammer.JS - v2.0.8

`//detect hammer on all of the document
var swipe = new Hammer(document);
swipe.on('swiperight swipeleft', function (e) {
    e.preventDefault();
    //swipe right to open nav
    if (e.type == 'swiperight') {
        // open main menu
        $('#navigation-menu').animate({
            left: '0'
        });
        //swiping left should slide out nav and/or sub-nav(s)
    } else {
        // close/hide menu(s)
        $('#navigation-menu, #task-menu, #brief-menu').animate({
            left: '-100%'
        });
    }
});`
