### ISSUE TITLE
Pinch gesture can not triggered well on svg children elements

### ISSUE THREAD

**Issue by ShawnKuan** [hammerjs/hammer.js#660]
I used 2 different versions of hammer.js(v1.1 and v2.0.3) to try the pinch event, both works fine on div elements, but when i change to svg element, v2.0 can not triggered well on svg children elements.
Here're the examples i created. try to use ipad and make a pinch-in gesture on Mr. sonic

v.1 http://codepen.io/ShawnKuan/pen/ApfHF
v.2 http://codepen.io/ShawnKuan/pen/IkjGJ

How could the v.2 works as same as v.1?
Is v.1 still supported?

**Comment by runspired** [comment]
Closing since resolved in a released version.
