### ISSUE TITLE
Events not triggering in IE8

### ISSUE THREAD

**Issue by zamith** [hammerjs/hammer.js#661]
Hi,

I'm adding some listeners to hammer, using jquery.hammer:

    this.$callingElement
        .hammer({
                'dragMinDistance': 2,
                'correct_for_drag_min_distance': false,
                'drag_block_horizontal': true,
                'prevent_default': true
         }).data('hammer')
                 .on('dragstart drag', $.proxy(this, '_handleDrag'))
                 .on('dragend', $.proxy(this, '_handleDragStop'));

This works fine for Chrome, FF, IE9+, but on IE8 the `_handleDrag` function is not called. If I change the event to `mousedown`, it does get triggered, so I'm assuming the problem is with the drag event.

In case you're wondering I cannot use the `mousedown` event because I need some data it does no provide, such as `interimDirection` and `deltaX`.

Thanks.

**Comment by runspired** [comment]
Closing as an issue with v1 (v2 does not support ie8)
