### ISSUE TITLE
Jumpy deltaX

### ISSUE THREAD

**Issue by braco** [hammerjs/hammer.js#666]
on an iPhone 5s, when binding to "dragleft, dragright" and observing the values of

event.gesture.deltaX

I noticed that the values do not consistently increase/decrease in a steady manner. For example, when dragging my finger right:

10, 12, 15, 14, 17, 20, 37, 35, 42

This means that if you're tracking drag with a high framerate animation, the animation will appear jerky.

Has anyone else encountered this, and what are you doing to correct for it?

**Comment by runspired** [comment]
Closing as v1
