### ISSUE TITLE
Hammer js crashes on Windows Surface

### ISSUE THREAD

**Issue by bharatyerra** [hammerjs/hammer.js#670]
Hammer js crashes on Windows Surface. Steps to reproduce:

1. Use html5 tel: tag on an anchor tag. 
2. Click the anchor to get the confirmation dialog to open skype. Click Cancel to cancel opening skype.
3. Tap on any element that has a hammer binding on the html. 

I checked the console to see that the bindDOM function being triggered infinitely. Any suggestions to fix the issue?

**Comment by runspired** [comment]
Closing as v1.
