### ISSUE TITLE
Hammer event not working in ios8 desktop.

### ISSUE THREAD

**Issue by mahendra86patel** [hammerjs/hammer.js#672]
hammer all event not working ios8 desktop version, it work fine in browser[IE, chrome, safari, Mozilla] as well as ios 5-6-7 desktop version, but after update new ios8 it stop working.

Version: Hammer.JS - v1.0.5
Test Device: ipad 2&3 with ios8
Event Use: hold tap swipe doubletap transformstart transform transformend dragstart drag dragend release pinch pinchin pinchout

**Comment by runspired** [comment]
Closing as V1, but also as v2 is known to work with ios8.
