### ISSUE TITLE
Severe performance degradation from 2.0.2 to 2.0.3

### ISSUE THREAD

**Issue by jperl** [hammerjs/hammer.js#676]
This example is using [hammer.js@2.0.2](http://paper1.meteor.com) and this example is using [hammer.js@2.0.3](http://paper2.meteor.com).

[Here](https://github.com/jperl/paper) is the source code.

If you pull up a card (need touch emulation on) you will notice a severe performance degradation between the two versions, the only difference is the hammer version.

**Comment by runspired** [comment]
Is this true for 2.0.4 as well?

**Comment by runspired** [comment]
I'm closing this as out-of-date.  @arschmitz it's likely this is still true though, at some point we should run through and make sure we don't have any `args` bindings that cause de-opts.
