### ISSUE TITLE
handlers attached on parent but triggered for children

### ISSUE THREAD

**Issue by expntly** [hammerjs/hammer.js#679]
The DOM I have is pretty much

```
<div id="theparent" hm-drag="dragged($event)">
  <div id="thechild">...</div>
  <div id="theotherchild">...</div>
</div>
```

This uses angular-gestures.  The problem is that when I drag one of the children, dragged() is called with the child as the event target, never the parent.  I was expecting the parent to receive it, since the handlers are defined on the parent itself and it encapsulates the children by definition.  Am I missing something?   Of course if I try to drag just the parent and not any of the children divs, it does the right thing and calls dragged() with parent as the target.

angular-gestures freshly installed today with bower.  Looking at gestures.js though, it seems to have pulled Hammer.JS - v1.0.5, as defined here: https://github.com/wzr1337/angular-gestures/blob/master/bower.json#L18.  Is this a know bug and should I use HM2 somehow?

**Comment by runspired** [comment]
Closing as v1, although this is likely able to be improved along with the other eventing in #808 or similar.
