### ISSUE TITLE
swipe up and swipe down not working

### ISSUE THREAD

**Issue by priyankaviswan** [hammerjs/hammer.js#684]
Hi am developing an application with marionette and hammer,swipe up and swipe down functions are not invoked,where as swipe left and swipe right is invoked.

**Comment by chengqiang1992** [comment]
I just want to know how everyone resolved this problem. When i try to swipe up and down it doesn't work. Swipe Left / Right work. But i have so many content in the list.

**Comment by jaysalvat** [comment]
Hello @chengqiang1992

I've just fixed my issue by setting:

```javascript
var hammertime = new Hammer(document.body);

hammertime.get('swipe').set({ direction: Hammer.DIRECTION_ALL });
`````

I hope it helps.

**Comment by liSong5713** [comment]
@jaysalvat  if you do this ,the body can not scroll . but if add touchAction ='pan-y'  ,swipe will not work. and please help me . many thanks
