### ISSUE TITLE
Pan Event isFirst never true

### ISSUE THREAD

**Issue by pr1ntr** [hammerjs/hammer.js#685]
isFirst is never true. I have to create my own isFirst to make it work.

**Comment by jdhiro** [comment]
That kind of works, but you can't just subscribe to 'pan' and get the 'panstart', so they all have to be called out individually. It works, but isFirst would certainly be nice to have.

**Comment by pr1ntr** [comment]
I would disagree. A simple switch statement could tell you what is going on. The whole idea here is to subscribe to multiple events and let your handler sort it out. Could you give an example of why you would need to subscribe to only one event per handler?

```
switch(event.type) {
  case "panstart" :
    // do pan start things
    break;
  default: 
    // do the rest..
    break;
}
```

**Comment by jdhiro** [comment]
Yeah, the issue I was having is that if you init with pan, you never get panstart event types. Like this:
```
hammertime.on('pan panstart'...)
```

I just resolved this by doing a ``hammer.on('pan')`` and  ``hammer.on('panstart')``

**Comment by pr1ntr** [comment]
I wonder if the order matters. but yeah that works too.

**Comment by noclat** [comment]
Why closed? The first problem about `ev.isFirst` remains unfixed…

**Comment by pr1ntr** [comment]
I think because no one has posted a legitimate use case where ```ev.isFirst``` is needed over ```ev.type == 'panstart'```

**Comment by noclat** [comment]
The need set apart, a useless variable is still hanging around there probably offending some perfectionists :). The issue is about the variable, not the use of it.

**Comment by andrey-p** [comment]
@pr1ntr If those variables shouldn't be used, maybe it would be a good idea to make a note of it in the docs or not mention them altogether.

(I just spent a good 20 minutes trying to debug some code that relied on `isFirst`, I can imagine other people going through that too.)

**Comment by pr1ntr** [comment]
that is why i started this thread ;). You can submit a pull request for the docs? I don't know I am not the author.

**Comment by jdhiro** [comment]
Just to drive me a little nuttier -- I just noticed that isFirst===true on...... the panend event...

This must be a little bug somewhere where true is being set on the wrong thing.

**Comment by reid3290** [comment]
Hit the same problem with pinch. event.isFirst never true ever.

**Comment by AdamSGit** [comment]
Hi guys,

Ran into same issue. Wheter it's used internally or not, if it doesn't work, what's the point ?

Either fix it or delete the var...

**Comment by sebmor** [comment]
Ran into the same issue very confused why it was never triggered. Agree with @AdamSGit that if it doesn't work, remove it.
Personally I like the simplicity of having isFirst & isFinal in one tap event.

**Comment by jdhiro** [comment]
@sebmor frankly, the project just isn't being maintained.

**Comment by simeyla** [comment]
`isFirst` **does** get called, even when just listening to the single `pan` event.

However I'm not seeing it get triggered a second time until the Y axis is moved. So it's as if it's saying `isFirst` time panning this object at all. 

HOWEVER `isFinal` gets called every end. So it seems like a bug.

I'm using RxJS to get the events like this

      const pan$ = fromEvent<HammerInput>(hammerPan, 'pan');
      const panStart$ = fromEvent<HammerInput>(hammerPan, 'panstart');
      const panEnd$ = pan$.pipe(filter((e) => e.isFinal);

**Comment by oisinlavery** [comment]
If you listen to the catch all **hammer.input** event you will see isFinal == true on the first event

```
hammer.on("hammer.input", function (ev) {
  console.log(ev.isFirst);
});
```

**Comment by qkreltms** [comment]
How about doing this: `clinicRefMc.on('panstart', (e) => onPanning(<HammerInput>{ ...e, isFirst: true }));`
