### ISSUE TITLE
Pressed state

### ISSUE THREAD

**Issue by miguelcobain** [hammerjs/hammer.js#689]
My use case is fairly simple, i guess.

I need to trigger some behavior when an element is pressed and when it is released, across multiple types of input (mouse and touch). Imagine to change the color of a button for as long as it is pressed, for example.

Can this be accomplished with hammer.js? This isn't a gesture "per se", but more like "universal" mousedown and mouseup events. It isn't a tap or a press. I wonder if hammer.js makes this possible.

Thanks!

**Comment by runspired** [comment]
@miguelcobain depending on what you need, there's two ways to accomplish this.

With CSS: `.foo:active {}` will apply styles so long as the pointer (mouse, finger, etc.) is actively pressing on the element.

With Hammer: `press` and `pressUp` can be used for behavior while pressing and when pressing ends.
