### ISSUE TITLE
weird propagation

### ISSUE THREAD

**Issue by berkaey** [hammerjs/hammer.js#690]
Hi can someone enlighten me about this issue

let's say we have structure like this

```
<div class="hammered">
 <div class="parent hammer">
  <div class="brother hammer">
   <div class="sister hammer">
   </div>
  </div>
 </div>
</div>
```
bind hammer (tap) (coffee script)
```
  $(".hammered").find(".hammer").hammer
    cssProps:
      userSelect: false  

  $(".parent").on "tap",(e)->
    console.log "parent"

  $(".brother").on "tap",(e)->
    e.stopPropagation()
    console.log "brother"

  $(".sister").on "tap",(e)->
    e.stopPropagation()
    console.log "sister"

```

and then everything goes crazy from this point.

if i tap parent,
parent fires once.

if i tap brother,
parent fires twice.
brother fires once.

if i tap sister,
parent fires 3 times.
brother fires twice.
sister fires once.

also stopPropagation won't working.

by the way on 1.x.x everythings works as expected.

**Comment by runspired** [comment]
Closing in favor of #807
