### ISSUE TITLE
How to make the inner div horizontal scroll when container has swipeleft/swiperight gesture?

### ISSUE THREAD

**Issue by dengdengxia** [hammerjs/hammer.js#695]
I bind the swipeleft/swiperight gesture to a container div, it works fine.
There is a div included in the container which has css style overflow-x:scroll to show wide contents.
The problem is the inner div cannot scroll horizontal now.
How to disable the container gesture while touch on the inner div?

**Comment by cupofjoakim** [comment]
I'm having the same problem, but in the vertical direction. I'd also like to know how to get this to work. @dengdengxia, how did you solve it?

**Comment by runspired** [comment]
@dengdengxia @cupofjoakim unfortunately you can't use touch to produce gestures and allow scrolling in the same direction as the gestures.  You may want to setup hammer in a way that it doesn't listen events originating in the scrollable div, or use a custom scroll solution.  In any case, it's bad UX to have a gesture and a scroll behavior that both trigger horizontally or vertically.
