### ISSUE TITLE
Global reference to Hammer should still be available even when an AMD loader is present

### ISSUE THREAD

**Issue by d13** [hammerjs/hammer.js#697]
This is needed for when Hammer is accessed by things outside of requirejs. For example, a 3rd party block of code adds an AMD loader, but it is not used by the rest of a page's code.

**Comment by runspired** [comment]
I've bumped into this problem on Cordova (among other places).  I think the solution here is on you to use the AMD loader if you discover it is present and affecting your code.  We'll be investigating a better modularity / consume-ability story in the near future.
