### ISSUE TITLE
Hammer js doesn't work with Jquery mobile

### ISSUE THREAD

**Issue by jackyon** [hammerjs/hammer.js#698]
Hi, currently i'm using jquery mobile for building an web app, every thing works great, but i found there is some bugs happened the swipe issues on Android devices.

so I am trying hammer js to solve those issues, the swipe event works weird, most of time I need to swipe a lot of times then the swipe event will be trigger

hammer swipe usage: $(element).hammer().on("swipeleft", myFunction);
jquery mobile swipe usage: $(element).on('swipeleft',myFunction);

I think this issue happened because of the element binds multiple events, am I right?

plz advise any solution for this, I have been fighting with this issue couple of days.

thx!

**Comment by runspired** [comment]
Closing as not enough information for a bug report and likely related to conflicting listener or poor configuration settings, not hammer.  If configuration, might be helped by #838

**Comment by arschmitz** [comment]
This was an issue with jquery Mobile and was fixed within jQuery mobile https://github.com/jquery/jquery-mobile/issues/7805
