### ISSUE TITLE
Panend not firing

### ISSUE THREAD

**Issue by ssuwal** [hammerjs/hammer.js#707]
Panend does not fire even after isFinal is true. Does anyone have any idea on how to trigger panend manually?? Appreciate the help

**Comment by runspired** [comment]
`panEnd` can sometimes fail to fire if `touchEnd` or `mouseUp` also fails to fire.  There are a number of situations (such as moving out of the area being listened on, or moving off screen) that potentially lead to this.

Unfortunately, this can be a tricky situation to detect, it's hard to know if a finger has simple stopped moving for a moment, or has disappeared.

Closing unless a jsbin is produced that reproduces the bug but doesn't fit these scenarios.

@arschmitz we may want to discuss mitigation strategies for the scenarios I put above.
