### ISSUE TITLE
target doesn't work

### ISSUE THREAD

**Issue by knezi** [hammerjs/hammer.js#708]
Hi everyone,
I'm using Hammer.js on Firefox OS and detecting event press. I've got table and in table cells spans. My detection is on each cell and I need to have the target (the concrete cell).
When I click on cell, everything's ok, but when I click on span it detect gesture (as it should), but event.target is the span and there's no event.currentTarget, so there's no way how to detect the cell (obviously without span.parent).
Is it a bug or feature?

**Comment by anthw** [comment]
I believe this may be related to #653

**Comment by runspired** [comment]
Closing in favor of #708
