### ISSUE TITLE
Pan event after Press

### ISSUE THREAD

**Issue by Valianton** [hammerjs/hammer.js#711]
Hello.
What I would like to receive:
I have item in a scrollable container. On touch devices must be scrolling when I made the gesture "scroll" on this item, but if I did Press on item, this item mast dragging whitout scrolling container.
<pre>
 var mc = new Hammer.Manager(item);
 mc.add(new Hammer.Press({time:500}));

 mc.on("press", function(ev)
    {
        var pan = mc.add(new Hammer.Pan({ threshold: 0, pointers: 0}));
        var rotate = mc.add(new Hammer.Rotate());
        mc.on("panstart panmove", onPan);
        mc.on("panend", onPanEnd);
    });

    function onPan(ev) {
         // some item translate operations
    }

     function onPanEnd(ev) {
       mc.remove(pan);
       mc.remove(rotate);
       mc.off('panstart panmove panend');
    }
</pre>
not working in Windows RT, 8/1.
Is that possible to do?

**Comment by runspired** [comment]
@Valianton The current solution for this is to either use drag events, or to add `mousemove` or `touchmove` event listeners following `press`.

It's not currently possible in Hammer.

**Comment by mburger81** [comment]
@runspired Is in meantime a possibility to do this?

We have made a drag&drop on ionic2 which works good, there is only one problem. We have to differentiate a SCROLL intention from a DRAG intention. So we wan't do default ionic2 swipe on pan and do a drag if the component is PANMOVE after a PRESS of 500ms.
