### ISSUE TITLE
Typescript Definition File for v2

### ISSUE THREAD

**Issue by milkisevil** [hammerjs/hammer.js#714]
I'm looking for a typescript definition file (hammerjs.d.ts) for the HammerJS v2 API. These [old](https://github.com/hammerjs/hammer.js/issues/513) [issues](https://github.com/hammerjs/hammer.js/issues/181) link to DefinitelyTyped which only has a definition for v1.1.3.

Otherwise, I'll have a go at writing a new v2 definition file, but it would be helpful to have someone on hand to verify my assumptions (this will be easy for someone with a good understanding of the API).

**Comment by timotei** [comment]
This looks like it's done & merged in the repo. I think it can be closed.

**Comment by runspired** [comment]
@timotei thanks!
