### ISSUE TITLE
COMPUTE_INTERVAL too low?

### ISSUE THREAD

**Issue by milkisevil** [hammerjs/hammer.js#718]
I'm wondering if `COMPUTE_INTERVAL` should be higher than `25`. At this value, the final call to `getVelocity()` in a session is often passed a `deltaX:0` and `deltaY:0`. Which means that a recognizer such as `swipe` isn't triggered.

When setting the `COMPUTE_INTERVAL` to `60`, the final `getVelocity()` in a session doesn't suffer from this problem and so `swipe` is triggered as expected. Perhaps Chrome is internally caching values when deltaTime is `< 60`?

What are your thoughts on `COMPUTE_INTERVAL = 60` or allowing it to be user configurable?

I'm testing on Chrome 38 using touch / Windows 8.1 / Surface Pro 3.

**Comment by runspired** [comment]
Closing in favor of #806, I think this was also accidentally included in PR #717
