### ISSUE TITLE
Rotate / Pinch gestures makes text and button elements uneditable/unselectable on IOS for Hammer v 2.0.4 

### ISSUE THREAD

**Issue by anitapillai** [hammerjs/hammer.js#733]
Associating a two-finger gesture (pinch or rotate) on a container makes text elements  within it uneditable on IOS (iPad / iPhone). Clicking on the text element does not bring up the keyboard nor can we enter any text into the element. Similarly buttons become unclickable. This issue is seen only on IOS and not on Android and is very specific to two-finger gestures, attempting the same scenario with Swipe/Press works fine.  

Here is a jsfiddle with an example: 

http://jsfiddle.net/bhptL6mf/59/

Is there a workaround for this issue?

**Comment by anitapillai** [comment]
Hammer js has a bug in the way it determines if it is acceptable to prevent the browser default behavior of scrolling/zoom etc when the touch-action property is set to none and the browser does not provide native support for the touch-action property. Holds true for IOS also. It fails to differentiate between a tap gesture and a multi-touch gesture which results in click and hover events from not getting recognized when an element has multi-touch gesture associated with it. I have submitted a PR that will fix this issue.

https://github.com/hammerjs/hammer.js/pull/762

**Comment by runspired** [comment]
Closing as this was implemented.
