### ISSUE TITLE
Applying Swipe gesture on a textarea or input element of type text makes it uneditable on IOS for Hammer v 2.0.4

### ISSUE THREAD

**Issue by anitapillai** [hammerjs/hammer.js#734]
Associating a swipe gesture directly on a textArea or an input element of type text makes it uneditable on IOS (iPad / iPhone). Clicking on the text element brings up the keyboard  but we cannot enter any text into the element.  A temporary workaround would be to remove the user-select option. This allows the text to be edited on load, but once we trigger swipe gesture couple of times on the element it becomes uneditable.

This issue is seen only on IOS and not on Android or desktop.

Here are two examples:

http://jsfiddle.net/ng0w4xr9/5/

http://jsfiddle.net/ng0w4xr9/4/    (removing the user-select option..edits on load but stops responding after swipe is triggered couple of times.)

Is there a workaround for this issue?

**Comment by renanlecaro** [comment]
Maybe touchAction:auto could help with this.

**Comment by runspired** [comment]
@anitapillai overall I'd say this is expected.  Can I ask why you need to add gesture support to the textarea itself?  This would interfere with a user's ability to drag their cursor or copy/paste.

Closing as not-a-bug, although perhaps @arschmitz we should give an escape valve here?

**Comment by anitapillai** [comment]
@runspired : The implementation I was supporting had an edge case where we wanted to support it for textarea's. I agree that adding gesture support would interfere with the users interaction with the textarea. Acceptable to close it as not-a-bug.
