### ISSUE TITLE
Touch event firing twice in 1.1.3

### ISSUE THREAD

**Issue by AlexDM0** [hammerjs/hammer.js#735]
Hi,

When we have two Hammer instances in our system, only the touch event fires twice even though it it only bound once.
I made a fiddle to show the problem: http://jsfiddle.net/281w1j31/

Is this a bug?

Regards,

Alex

**Comment by runspired** [comment]
Closing as this is an issue with V1.  V2 can still have issues with overlapping instances which will be addressed.
