### ISSUE TITLE
latest atmosphereJS build (meteor package) is outdated / broken

### ISSUE THREAD

**Issue by strack** [hammerjs/hammer.js#741]
Hey there,
So atmospherejs.com is showing the latest meteor-friendly build / push as being 2.0.4_2, but I'm thinking that it may be an accident, because inside that build, your date is:
`/*! Hammer.JS - v2.0.4 - 2014-09-28                                                                                   // 1`

whereas the 2.0.4_1 version has a later date:
`/*! Hammer.JS - v2.0.4 - 2014-11-24                                                                                   // 1`

Also, missing from _2 (but it's there in _1) is the meteor-specific code for creating the global Hammer variable:
```
if (typeof Package !== 'undefined') { 
  /*global Hammer:true*/  // for JSHint; Meteor.js needs a file-scope global for exporting
  Hammer = window.Hammer;  
  delete window.Hammer; 
} 
````

I, for one, sincerely appreciate your efforts to support your library on Meteor. Thank you, and I hope you have a Merry Christmas / Happy Holidays!

**Comment by adamgins** [comment]
Hi, just wondering if this was fixed?

**Comment by dburles** [comment]
@adamgins Last commit was on the 26th so I don't think so

**Comment by adamgins** [comment]
thanks @dburles wondering if you worked around it? eg just included directly in your Meteor proj?

**Comment by dburles** [comment]
@adamgins I didn't sorry :(

**Comment by adamgins** [comment]
@dburles cheers

**Comment by adamgins** [comment]
@dburles FYI, I seem to have it working with the https://github.com/hammerjs/jquery.hammer.js , I could not get it working with straight JS, I kept getting undefined.

**Comment by lyslim** [comment]
met same issue here, got to use 2.0.4_1 instead.

**Comment by noblestreet** [comment]
Hi Guys,

I got it to work with the following:
$meteor add hammer:hammer@=2.0.4_1

Template.page.rendered = function() {
  var hammertime = new Hammer($('body').get(0));

  hammertime.on('swipe', function(e) {
    console.log(e, e.offsetDirection);
  });
});

**Comment by lyslim** [comment]
@noblestreet , yes, with version 2.0.4_1, it works fine. But it had better that meteor specific code is reflected in the latest build as well.

**Comment by lukicdarkoo** [comment]
@lyslim with 2.0.4_1 it works fine for me too, and it would be great to fix bug in latest version

**Comment by runspired** [comment]
Closing as this is an issue with a meteor build we don't maintain.
