### ISSUE TITLE
panLeft called before panStart

### ISSUE THREAD

**Issue by donovan-graham** [hammerjs/hammer.js#750]
A single panLeft (or panRight) event is being called before panStart.  This creates unexpected behaviour in my code which expects panStart to setup some variable before the panLeft and panRight events happen.  Is this buggy behaviour?

Here's an example:
http://codepen.io/donovan-graham/pen/XJRmLX/

**Comment by donovan-graham** [comment]
I've worked out the listening to panLeft and panRight events are not what I need.  I seems to be that if you want to manage hammer events in a particular order then you should be binding:
panStart, *panMove*, panEnd.

I'm guessing panLeft and panRight are useful in different situations, where you're not concerned about when they start.

**Comment by dmitryshimkin** [comment]
Why is this issue closed? It seems the order of pan and panstart events is not fixed.

**Comment by runspired** [comment]
This issue is fixed on master, this particular one was likely closed as a duplicate.
