### ISSUE TITLE
pointer events registered with deprecated MS prefix in IE 11

### ISSUE THREAD

**Issue by rd-secretstuff** [hammerjs/hammer.js#753]
In the current version it decides to use the MS prefixed pointer events event on Internet Explorer 11,
It uses **MSPointerDown MSPointerMove MSPointerUp MSPointerCancel** instead of **pointerdown pointermove pointerup pointercancel** event though the prefixed ones are deprecated.

This is because the test for prefixed input is like this : 

```javascript
// IE10 has prefixed support, and case-sensitive
if (window.MSPointerEvent) {
    POINTER_ELEMENT_EVENTS = 'MSPointerDown';
    POINTER_WINDOW_EVENTS = 'MSPointerMove MSPointerUp MSPointerCancel';
}
```
IE 11 however has both MSPointerEvent and PointerEvent defined (probably for backward compatibility). 
And will behind the scenes translate the MS prefixed pointer events to the non MS prefixed ones.
This (currently) doesn't pose a problem for hammer.js directly, but if hammer.js is combined with another library (for example webcomponents.js), it will fail to work because the registered event will be **MSPointerDown** while the actual event that is being send is **mousedown**

The test for PointerEvent should probably be like this :
```javascript
// IE10 has prefixed support, and case-sensitive
if (window.MSPointerEvent && !window.PointerEvent) {
    POINTER_ELEMENT_EVENTS = 'MSPointerDown';
    POINTER_WINDOW_EVENTS = 'MSPointerMove MSPointerUp MSPointerCancel';
}
```
This way it will only use the prefixed versions when the non prefixed ones don't exist

**Comment by miguelmota** [comment]
I'm using webcomponents.js and ran into the issue @rd-secretstuff mentioned but fortunately his solution worked wonderfully. 

[Pull Request  #782](https://github.com/hammerjs/hammer.js/pull/782)

**Comment by arschmitz** [comment]
@rd-secretstuff Thank you for reporting this yes this needs to be updated. We are just ramping up development here again and will be sure to get this fixed!
