### ISSUE TITLE
Hammer blocks click events in iframe (on iPhone only)

### ISSUE THREAD

**Issue by zdendapa** [hammerjs/hammer.js#756]
I have page with Iframe. I hammer body of this Iframe to achieve pinch and zoom. It works well. Only on iPhone when I click any link in iframe, nothing happend.
hammer v2.0.4

demo:http://www.urias.cz/temp/zoomZdenda/iPhoneIframeLinks.html

**Comment by arschmitz** [comment]
This is a known issue with touch events on iphone and the work around is SUPER ugly. If your using jQuery though i do maintain a plugin which fixes this issue. https://github.com/gseguin/ios-iframe-touchevents-fix i think fixing this is way outside the scope of this project though so im going to close this.
