### ISSUE TITLE
event.target is wrong

### ISSUE THREAD

**Issue by lore-w** [hammerjs/hammer.js#757]
sometimes , I can't bind the event "tap" on the chrome , so I want to bind the event through "event delegate" . But unfortunately, I found the event.target is wrong...

**Comment by runspired** [comment]
@lore-w could you provide a jsbin replicating?  In general with bubbling events, `event.target` and `event.currentTarget` are also different, you may need to look at `currentTarget` on an event for your delegation to work.

Closing until further information if provided as not specific enough to debug.
