### ISSUE TITLE
Bind on window or document object error

### ISSUE THREAD

**Issue by okwei2000** [hammerjs/hammer.js#759]
First: I have looked at  #688, #644, which talked about the same issue, then I took the fix manually in commit: 
https://github.com/hammerjs/hammer.js/commit/1cab23edc8be3b1ace9a4ead5a4d9cdfa0a5e1f5

but I still go errors when doing this following: 
Hammer(window).on("swiperight", function(ev) {});
Hammer(document).on("swiperight", function(ev) {});

The only thing works for me is Hammer(document.body).on("swiperight", function(ev) {});

**Comment by julianxhokaxhiu** [comment]
Getting exactly the same bug. Did you maybe revert the fix you did on #644 @jtangelder ?

**Comment by julianxhokaxhiu** [comment]
Oh...I just saw that the fixes are there but there was no version bump. So from bower we're getting the bugged version. Can you please bump the version @jtangelder ?

**Comment by julianxhokaxhiu** [comment]
Also the hammer.js and min file are without this fix even...so practically there should be also rebuilted and bumped...

**Comment by josdejong** [comment]
+1

A bug fix release would be great.

**Comment by holic** [comment]
:+1:

**Comment by arschmitz** [comment]
We are working on cleaning up issues and fixing bugs right now and we will do a patch release soon!

**Comment by verde-io** [comment]
This is still an issue, is a new release ever going to come?

**Comment by runspired** [comment]
@verde-io Yes, the current master is likely to be the new release.

**Comment by verde-io** [comment]
@runspired Thanks. When is that likely to come out?

**Comment by runspired** [comment]
@verde-io We're hoping today.

This: https://github.com/hammerjs/hammer.js/labels/Patch%20Release

Tracks the remaining items we want to look at before releasing.  I'm mostly doing prep work atm before a 2-4pm CT sprint to push this out the door.

**Comment by verde-io** [comment]
@runspired any update on the new release?

**Comment by runspired** [comment]
@verde-io haven't had a chance to look into fixing the `pointers.length` bug, which seems to be the root cause of a large number of bug reports.  Hoping over the holiday break to find time :)

**Comment by simoneduca** [comment]
Should this be reopened perhaps?

**Comment by SeeGreatness** [comment]
Perhaps so
