### ISSUE TITLE
Press event options

### ISSUE THREAD

**Issue by okwei2000** [hammerjs/hammer.js#765]
Have the following code, but it seems that the options are not effective at all - time, pointer dont have any effects. 
 
       var hammertime = new Hammer(myElement, {
            time: 5000,
            pointers: 2,
            threshold: 10
        });
        hammertime.on('press', function(ev) {
            alert('here')
        });

**Comment by runspired** [comment]
@okwei2000 you aren't configuring your press recognizer appropriately, see: http://hammerjs.github.io/getting-started/ for examples.

To configure the Press recognizer, you'd need to something like this:
```
 var hammertime = new Hammer(myElement);
hammertime.get('press').set({
        time: 5000,
        pointers: 2,
        threshold: 10
    });
```

**Comment by mohsinali1317** [comment]
I am having the same issue this is how I am setting my press event

      var hammertime = new Hammer(can);
        hammertime.get('press').set({
            time: 1000,
            pointers: 1,
            threshold: 10
        });
        hammertime.on("press", function (ev) {
            alert(ev.type);
        });

But the options don't have any effect. The press is event doesn't wait for 1000 ms in fact it just fires the event as soon as I click.
