### ISSUE TITLE
Badly initialized object

### ISSUE THREAD

**Issue by marcandre** [hammerjs/hammer.js#768]
The following code produces an error:

    (new Hammer(document.body)).off('swipeleft', function(){})
    //=> TypeError: Cannot read property 'splice' of undefined

**Comment by sculove** [comment]
When you didn't attach an event, you will see this error.
I think that Hammerjs has to handle exception.

I pushed codes that fix it.
https://github.com/hammerjs/hammer.js/pull/770

**Comment by sculove** [comment]
I resend pr that separate unrelated changes
#839
