### ISSUE TITLE
ev.pointers.length in panend

### ISSUE THREAD

**Issue by demrks** [hammerjs/hammer.js#769]
I'm not sure if that behaviour is intented, but if I pan with one finger and release it, `ev.pointers.length` in `panend` returns `1`. If I do the same with `touchend`, `ev.touches.length` returns `0`. 

Since the touch was released in `touchend`/`panend` I don't see why there should be any pointers/touches in `ev.pointers`. Released touches will be found in the `changedTouches`/`changedPointers` in any way.

**Comment by runspired** [comment]
This may be due to an incorrect ordering of events in pan that was fixed by https://github.com/hammerjs/hammer.js/commit/92f2d76188480d967e738a19cd508d0b94a31329

**Comment by runspired** [comment]
Turns out this is intended. `pointers` contains pointers that have been removed as well.  You'll need to loop `pointers` and examine their types.  We're looking into the possibility of adding an `activePointers` property for `2.1.x`
