### ISSUE TITLE
How can you prevent a click from firing at the end of a long press?

### ISSUE THREAD

**Issue by lorensr** [hammerjs/hammer.js#772]
Here's my problem:

http://stackoverflow.com/questions/29190110/how-can-you-prevent-a-click-from-firing-at-the-end-of-a-long-press

Is there a way in my `press` handler to prevent the next click from firing? `ev.preventDefault` doesn't do anything, and there's no `ev.stopPropagation`

**Comment by lorensr** [comment]
Solved, see SO link

**Comment by mrasoahaingo** [comment]
Hi, I'm encountering this same issue, is there a solution? the link of solution doesn't work :(
