### ISSUE TITLE
undefined is not a function inside hammer.js

### ISSUE THREAD

**Issue by genethic** [hammerjs/hammer.js#773]
I was using the EightMedia jquery hammer plugin and it works. Now I have read that is not longer mainteined and I am migrating to the new jquery plugin for hammer developed by you.

I have included hammer.js and jquery.hammer.js and this my code:

```javascript
var slide = ('#slides');
	var myhammer = new Hammer(slide);
	myhammer.on('swipeleft', function(ev) {
		$(this).superslides('animate', 'next');
	});
	myhammer().on('swiperight', function(ev) {
		$(this).superslides('animate', 'prev');
	});
```

But swipeleft/swiperight doesn't work now and in the console is this error:

Uncaught TypeError: undefined is not a function on hammer.js line 168.

I am using v2.0.4 - 2014-09-28

**Comment by ryanwalters** [comment]
Try this:

     $('#slides').hammer().on({
        'swipeleft': function () {
            $(this).superslides('animate', 'next');
        }),
        'swiperight': function () {
            $(this).superslides('animate', 'prev');
        })
    });

**Comment by arschmitz** [comment]
There is an issue with the posted code your missing the `$` on your first line. 
Im going to close this but if your still facing this issue after fixing your code please make a small test case using either jsbin or jsfiddle and post it and we will re open this issue
