### ISSUE TITLE
Migrate from 1.0.6 to 2.0.x

### ISSUE THREAD

**Issue by nvd-ai** [hammerjs/hammer.js#784]
What is the process of migrating from 1.x to 2.x? Are there any minor and major API changes from 1.x to 2.x?

**Comment by VinayakHegde** [comment]
that is a big headache. Few of the gestures are deprecated and if you upgrade to v2.x, you gonna break your existing code for sure!

**Comment by pankaj-arunsingh** [comment]
Can anyone name what are the gestures deprecated?

**Comment by VinayakHegde** [comment]
its completely re written. so you can able to seen the new gestures in v2.0.x

**Comment by pankaj-arunsingh** [comment]
Thanks Vinayak

**Comment by arschmitz** [comment]
I'm going to close this since its more of a question then a bug so i'm going to close it as we are now back moving again and focusing on future development!

@VinayakHegde not dead back and hopefully better then ever this will be a community project now!
