### ISSUE TITLE
add whether rotation is in degrees or radians or ... to http://hammerjs.github.io/api/

### ISSUE THREAD

**Issue by Pomax** [hammerjs/hammer.js#785]
I'm trying to find the information that tells me which angular units the rotation property on events uses, but there seems to be no page with that info. Can http://hammerjs.github.io/api/ be extended to say whether "rotation" is deg/rad/grad and whether + is clockwise or anti-clockwise?

I'm sure I can console.log my way to victory here, but that won't help the next person who needs this information.

**Comment by revolunet** [comment]
looks like you can submit a PR here : https://github.com/hammerjs/hammerjs.github.io/blob/398b2fd4794e2090dbdec2718b717f21c3ab7cdf/api.md

**Comment by Pomax** [comment]
handle, although I'll leave that to the project maintainers.

**Comment by revolunet** [comment]
i was referring to "but that won't help the next person who needs this information." and was hoping you can fix that :+1:

**Comment by Pomax** [comment]
I'm going to have to dash that hope, I'm working on way too many things right now to also file this doc fix, but I'd happily bounce that back at you can say that if you think it's a quick thing to add to the docs and know where to add it, you'll have my thanks for doing so.

**Comment by revolunet** [comment]
PR submitted...

**Comment by arschmitz** [comment]
I'm going to go ahead and close this since its really a an issue for a different repo and there is a PR already
