### ISSUE TITLE
build fails on win 7 with node 0.12 and grunt 0.1.13

### ISSUE THREAD

**Issue by Pomax** [hammerjs/hammer.js#787]
trying to run npm build, I get the following build fail log:

```
PS C:\Users\Mike\Documents\Git projects\collaborations\hammer.js> grunt build
Running "concat:build" (concat) task
File hammer.js created.

Running "string-replace:version" (string-replace) task
File hammer.js created.

Running "uglify:min" (uglify) task
File .\hammer.min.map created (source map).
Warning: Cannot assign to read only property 'subarray' of !function(a,b,c,d){"use strict"....
...snip...
...!=typeof module&&module.exports?module.exports=ea:a[c]=ea}(window,document,"Hammer");

//# sourceMappingURL=hammer.min.map Use --force to continue.

Aborted due to warnings.
```

**Comment by manageryzy** [comment]
have the same problem when building my project.

this may be a bug of grunt

**Comment by darrennolan** [comment]
This happens on mac as well, (node 0.12.7 here).

**Comment by Pomax** [comment]
At this point in time Node 0.12 is out of support, and has known security issues that will never be fixed because since then, the Node community split, Node became "Node.js" and "IO.js", reconciled, reformed as the Node.js foundation, merged codebases to Node 4, and now we're on Node 5 with significant advances (native ES2015 support, for instance). So you really want to update your version to latest stable, @darrennolan.

With the latest Node (5.4 as of this comment), hammerjs installs just fine:
```
d:\Temp\_>node -v
v5.4.0

d:\Temp\_>npm -v
3.3.12

d:\Temp\_>npm install hammerjs
testproject@1.0.0 d:\Temp\_
└── hammerjs@2.0.6

d:\Temp\_>
```

**Comment by darrennolan** [comment]
I don't think that's quite right @Pomax - https://github.com/nodejs/LTS/

Though yes, it's high on our priority list to update. If this doesn't build under 0.12 that's cool ^_^

**Comment by Pomax** [comment]
yes, current LTS is 4.2.4

**Comment by joshjung** [comment]
Having this problem on Mac still even on version 4.2.4:

`joshuas-mbp:hammer.js jjung$ npm -v
3.6.0
joshuas-mbp:hammer.js jjung$ node -v
v4.2.4
joshuas-mbp:hammer.js jjung$ grunt build
Running "concat:build" (concat) task
File hammer.js created.

Running "string-replace:version" (string-replace) task
File hammer.js created.

Running "uglify:min" (uglify) task
File ./hammer.min.map created (source map).
Warning: Cannot assign to read only property 'subarray' of !function`

**Comment by joshjung** [comment]
Solved: this issue is the following https://github.com/mathiasbynens/grunt-yui-compressor/issues/28

Changing `gzip` to `min` in `Gruntfile.coffee` fixed the issue for me.
