### ISSUE TITLE
Hammer.js added javascript that stops me from scrolling over my image

### ISSUE THREAD

**Issue by code-mattclaffey** [hammerjs/hammer.js#792]
I have been working on fixing this bug for two days now and hair has nearly been ripped out from this bug. I am using Hammer.js to make the image zoom,pinch,pan and everything works fine and dandy.

However the client has come back saying that on a landscape device you cant scroll to get to the bottom of the image. I have tested this and my senior has tested it and he says it something to do with Hammer.js.

I have used the overflow scroll on the element thats containing the image but the image is 100% width so no matter where I scroll it will be on top on that image.

Has any other Hammer js users came across this problem? if so please advise. :)

Cheers!

**Comment by LePetitDev** [comment]
This is a common side effect of panning with touch. Add a margin between the image and the left and right sides of its container. Now, the space in the margins can be used to scroll.

**Comment by arschmitz** [comment]
This is just how touch action is designed to work it sounds you can minimize this effect by making sure your using the correct `touch-action` property to only disable what you need to. 
I'm going to close this as not a big
