### ISSUE TITLE
Infinity «panmove»

### ISSUE THREAD

**Issue by Valianton** [hammerjs/hammer.js#795]
On Android 5.1.1 (nexus 9) performed infinity event «panmove» even when the finger does not move on the screen

**Comment by runspired** [comment]
@Valianton could you provide us a code sample to be used to replicate, as well as further detail about how to replicate the issue? It seems you are maybe saying that if you set your finger on the screen and leave it there it (unmoved) it triggers `panmove` events until your finger leaves the screen, is that correct?

**Comment by runspired** [comment]
Maybe influence by merging #824

**Comment by runspired** [comment]
Closing this for lack of follow up and not enough information.
