### ISSUE TITLE
Looking for team members

### ISSUE THREAD

**Issue by arschmitz** [hammerjs/hammer.js#800]
To help improve the future viability of this project we are going to build a team around the project.

Any one interested in helping please comment here with in what ways you think you would be willing / able to help. I started an IRC channel for development and support #hammer.js on freenode! would love to see any one interested there!

**Comment by runspired** [comment]
I'd be willing to help out in any capacity needed.  I've currently got only a few hours a week (for the next few weeks), but that should be enough to go through issues and help investigate and label them.

In regards to IRC, I was a co-founder of the Ember Slack channel, and we've hit 1500 members in a little over 2 months.  Ember's IRC/Gitter channels never got about 400, and never saw anywhere near the level of communication and involvement Slack has unleashed.  You might want to consider Slack for HammerJS as well.

**Comment by arschmitz** [comment]
@runspired Awesome thanks I'm potentially open to slack as well if it seems others would prefer and there is demand. Iv never used slack much none of the projects i work on have slack channels. But im completely willing to give it a shot if others want!

**Comment by runspired** [comment]
@enrichit @schue @gagan-bansal @stephanebachelier @picitujeromanov have all expressed interest in at least pitching in to get this cleaned up in the past.

**Comment by arschmitz** [comment]
@runspired yes thanks for pinging them all on this issue i followed the other one all along ( @jtangelder  and i have actually been talking about this for ~6 months ) and had seen all their offers thats why i cross posted hoping any one still interested will show up!

**Comment by jdhiro** [comment]
I'm interested in helping out as well. I already use Hammer in multiple projects, so I'm pretty invested in it.

**Comment by jtangelder** [comment]
I'm also using Slack at my job, and am quite happy with it. Love the itegrations with all kinds of services. I've just opened an organisation, hammerjs.slack.com. Feel free to join while i'm setting it up.

**Comment by jdhiro** [comment]
I use Slack for work, but aren't organizations invite only?

**Comment by runspired** [comment]
@jtangelder @jdhiro yes, but you can build an auto-invite service like http://socket.io/slack/ or ember-community-slackin.herokuapp.com easily.  I reached out to the person who setup the page for Ember to figure out which app/repo he used to do so.

**Comment by jdhiro** [comment]
I have Slack/Gitter running 24/7. It seems like Slack would be the better option if you wanted to host chat for key contributors, and Gitter would be better for drive-by community discussions.

**Comment by runspired** [comment]
@jtangelder https://github.com/rauchg/slackin is what was used for Ember's

**Comment by runspired** [comment]
@jdhiro you should check out some of the public orgs on slack, it's really very adequate for both.  Pop into the Ember one to see what I mean.

**Comment by jtangelder** [comment]
@runspired thx! it's running at http://hammerjs-slackin.herokuapp.com/

**Comment by owenversteeg** [comment]
Been years since I've helped with this project, but I'm willing to help by testing on a large number of machines (I have desktop Windows/Linux touchscreens, old Opera Mobile devices, Palm devices, Android phones, etc., etc.) and possibly contributing code. Even though others don't seem to be, I'm a fan of gitter; I feel it provides a nice interface, especially for those that don't want to take the time to configure IRC. As @jdhiro mentioned, it's nice for drive-by-discussions. I do think having an IRC channel is a good idea though.

**Comment by arschmitz** [comment]
@owenversteeg we have both slack and irc setup now i'm in both. Im not for or against gitter i have not really used it. If enough people seem to want it i'm for it. Any help you can offer will be greatly appreciated. Great to hear you have access to testing devices between the two of us we should be well covered now :-) 
![Device Lab](http://i.imgur.com/t0UTbUP.png)

**Comment by owenversteeg** [comment]
@arschmitz Damn, looks like you slightly beat me on number of testing devices. You win this one :)

I have a ton of experience with CSS/JS (with a focus on CSS.) Is there anything in particular that I could jump into doing? I could also just break out my testing devices and report back on what I find with them.

**Comment by arschmitz** [comment]
@owenversteeg I think right now the most important thing we can do to start is triage the big back log of issues. I started to go through earlier today. If you wanted to help and try to test and confirm, any where that is possible that would be great! Once we have identified the legit issues we can try to prioritize and start fixing.

**Comment by RByers** [comment]
I work on touch input on Blink and at the W3C.  As before I'm happy to help from the browser compatibility / spec side, and love to hear feedback on how the APIs can be made better for use cases like Hammer.

**Comment by arschmitz** [comment]
@RByers Awesome thanks we have worked together on some issues on jQuery Mobile before too. I also work on pep ( formerly the Polymer Pointer events polyfill :-) ) So i'm sure we will be talking more. I follow the specs and mailing lists pretty closely, most of my input goes through my fellow jQuery Team member @scottgonzalez

**Comment by gagan-bansal** [comment]
Great news for such a wonderful lib. 
I can help in labeling the issues with initial guidance.

**Comment by RByers** [comment]
@arschmitz perfect!  Hopefully you guys are less annoyed with me now that we're actually implementing pointer events ;-)

**Comment by arschmitz** [comment]
@RByers ha ha :-) there is definitely no hard feelings. We understand the process you guys have to go through and that its not an easy one!

**Comment by RByers** [comment]
Thanks :-)

**Comment by arschmitz** [comment]
@RByers And super glad you want to help out here a good advocate is always a great thing to have!

**Comment by gabrielschulhof** [comment]
Hey, all! I'm definitely willing to pitch in here and there, time permitting.

**Comment by runspired** [comment]
@anitapillai would you be interested in this?

**Comment by gagan-bansal** [comment]
I am using Hammer for maps development.
I can spend 4-5 hours a week for this. Please suggest, how can I involve in this?

**Comment by arschmitz** [comment]
@gagan-bansal Right now the best help would just be to jump into the issues and try to fix some and submit PR's for them. We finally cleaned things up yesterday to the point where we are starting to land PR and get work going again. I see you joined the slack channel already thats where we talk mostly.

**Comment by anitapillai** [comment]
@runspired : Definitely interested! Just joined the slack channel.

**Comment by gagan-bansal** [comment]
@arschmitz I'll try that.
Thanks
