### ISSUE TITLE
[Meta] Fastclick, Inputs, and "Ghost Clicks"

### ISSUE THREAD

**Issue by runspired** [hammerjs/hammer.js#808]
This is a meta issue for problematic click behavior that will largely be dealt with by converting to pointer events.

Affected Issues:
- https://github.com/hammerjs/hammer.js/issues/742
- https://github.com/hammerjs/hammer.js/issues/753
- https://github.com/hammerjs/hammer.js/issues/726
- https://github.com/hammerjs/hammer.js/issues/727
- https://github.com/hammerjs/hammer.js/issues/720

**Comment by runspired** [comment]
Potentially would fix this issue: https://github.com/hammerjs/hammer.js/issues/578

**Comment by runspired** [comment]
This occurs because ghost clicks don't maintain the original target, only the coordinates: https://github.com/hammerjs/hammer.js/issues/411

**Comment by arschmitz** [comment]
For anyone tracking this issue or the related ones we have created a new fast click to avoid using tap for a fast click. https://github.com/hammerjs/hammer-time

**Comment by arschmitz** [comment]
im going to close this i dont think it is relevant any longer

**Comment by crlang44** [comment]
I'm having this issues with hammer 2.0.8 using it with Angular 4

**Comment by ndcunningham** [comment]
same

**Comment by koakuma-chan** [comment]
> im going to close this i dont think it is relevant any longer

So what is the solution to #411? I doubt "fast click" has anything to do with #411.
