### ISSUE TITLE
User selection

### ISSUE THREAD

**Issue by anselmh** [hammerjs/hammer.js#81]
Hey there,

thanks for developing the framework. I just have a question that might already have been answered. If so, please let me know and excuse me.

Hammer.js currently serves this -webkit-user-select: none on the body tag and also the touch-derivate. Is this necessary and why is it?
The problem is (as all of you can imagine) that user cannot select text anymore which for me is a real blocker issue. Can I somehow prevent this behavior?

Thanks for clarification!
-Anselm

**Comment by Bargs** [comment]
If anybody stumbles across this issue like I did, note the the option name have been changed again. It's now called `cssProps` instead of `behavior`, so your config would look like this:

```
Hammer(content, {
  cssProps: {
    userSelect: true
  }
});
```

**Comment by jpatel3** [comment]
Its very weird, even if cssProps is blank it enables userSelect.

 ```
Hammer(content, {
  cssProps: {
  }
});
```

**Comment by tjvg91** [comment]
`delete Hammer.defaults.cssProps.userSelect;`

place this **before** the initialization of your hammer object

**Comment by musterknabe** [comment]
@jpatel3 It only overwrites specified cssProps, so an empty cssProp will result in the defaults being used.

This worked for me:
```
cssProps: {
    userSelect: 'auto',
 }
```

You should probably set it to something of `auto | text | none | contain | all` (See [https://developer.mozilla.org/en-US/docs/Web/CSS/user-select]())

**Comment by tsarma** [comment]
In case someone is still having/want to overcome this issue. The following excerpt is from hammerjs tips section. And it works too.

> If you care about the text-selection and not so much about the desktop experience, you can simply remove this option from the defaults. Make sure you do this before creating an instance.

`delete Hammer.defaults.cssProps.userSelect;`

Or 
You can just reset the BODY inline css `user-select : text`, with javascript in your favourite domready function.
