### ISSUE TITLE
Recognizer Options of separate Hammer instances are mixed up (not separated)

### ISSUE THREAD

**Issue by LeJared** [hammerjs/hammer.js#813]
**Example:**
http://codepen.io/anon/pen/bdYQaa

**Expected behavior:**
The first div is supposed to recognize Hammer.DIRECTION_ALL, the second one should recognize Hammer.DIRECTION_HORIZONTAL.

**Actual behavior:**
Both instances use Hammer.DIRECTION_HORIZONTAL.

When you inspect both instances in your JS debugger (Firebug, chrome dev tools, ...), you'll see, that the options of the panrecognizers of both instances are set to direction=6 (HORIZONTAL).

If you remove all the JS-code from the second instance, then the first instance is correctly set to Hammer.DIRECTION_ALL. Somehow setting this option on the second instance does also set this option on the first instance.

*EDIT*
Updated example. Now it outputs actual panrecognizer direction options of both instances

*EDIT2*
Update example. I've found, that the options-Object of two recognizer-instances are shared (identical objects). See output DIV in example. The options-objects are identical though the recognizer objects are not.

**Comment by LeJared** [comment]
I've created a bugfix for this issue. It ensures that the options are copied into a new object in the recognizer constructor. This fixes the actual issue.

The deeper problem is in the `Manager()` constructor. This line:
`this.options = merge(options, Hammer.defaults);`
copies the default-options into the newly created Hammer instance. But `merge()` only creates shallow copy of the defaults-object. This way, the default-options for the default-recognizers within these Hammer.defaults are not copied but linked to and thus shared between all recognizers.

So additionally replacing merge() in the constructor with a function that performs a deep copy would be recommended to avoid similar problems else where.

**Comment by runspired** [comment]
> The deeper problem is in the Manager() constructor. This line:
this.options = merge(options, Hammer.defaults);
copies the default-options into the newly created Hammer instance. But merge() only creates shallow copy of the defaults-object. This way, the default-options for the default-recognizers within these Hammer.defaults are not copied but linked to and thus shared between all recognizers.

@arschmitz sounds like we may leak options modifications between manager instances (not just recognizer instances), will investigate and PR fix if so.

**Comment by abrahamD** [comment]
+1. Would like this to be merged. I have multiple instances of Hammer and need different directions listened. My temporary fix is to listen to all swipe directions but it's not ideal (especially for old devices).

Thanks in advance
