### ISSUE TITLE
Touch callout on iOS

### ISSUE THREAD

**Issue by iEgit** [hammerjs/hammer.js#819]
As described [here](http://sky2high.net/en/2015/03/hammer-js-css-touch-action-and-ios-safari-context-menu/) the long tap on image doesn't seem to work on iOS Safari.

So it is not possible to call native context menu on an image with `Hammer.Manager` being used on it.

@DimitryDushkin [fixed](https://github.com/DimitryDushkin/hammer.js/commit/630eab4f075517706a4c7b0bcd71e8ee49673d62#diff-191094f6a87f0935579ad0d0bc330b55R1173) this issue in his fork but it looks like some kind of a hack. Maybe some coherent solution could be worked out.

**Comment by arschmitz** [comment]
Yeah most of that looks like its unrelated to the fix and to the commit message. We will be looking into trying to fix this soon

**Comment by iEgit** [comment]
There is also one bug in Android Browser connected with this one: when we click on native player, the event gets preventDefaulted and video controls don't work.

**Comment by runspired** [comment]
@iEgit please open separate issues for separate issues :P  I know it's tempting to get a conversation rolling in an issue once you have a response.

On Android Browser Bug, that's a won't fix (until the eco-system improves).  See discussion here: https://github.com/hammerjs/hammer.js/issues/858

Incidentally though, it is a similar issue to the context-callout.  You need to set the touch-action CSS appropriately on the manager, and remove the configuration setting for text callout, and your safari image issue should be resolved.
