### ISSUE TITLE
Last state of event while event is in progress

### ISSUE THREAD

**Issue by gagan-bansal** [hammerjs/hammer.js#820]
When I pan, I always store the last `event.deltaX` and `event.deltaY` to `lastDeltaX` and `lastDeltaY`. As I pan the element( for may case map) I take the required action for giving `deltaX` and `deltaY` while panning. Then at next `panmove` I find out the difference of current `event.deltaX`with my stored `lastDeltaX` and apply this difference to my map element. Same is the case with rotate and scale.

So would it be nice store the last state of event object in event like `lastState` as one more event property with all parameters of event object?

**Comment by gagan-bansal** [comment]
Is it suitable or I am expecting that should not be part of the hammerjs logically.

**Comment by runspired** [comment]
Closing in favor of #806
