### ISSUE TITLE
jQuery exposes `jQuery` and $ identifiers in global. How about exposing `Hammer` in global?

### ISSUE THREAD

**Issue by sculove** [hammerjs/hammer.js#822]
I saw https://github.com/hammerjs/hammer.js/pull/328
I understand this pull request.

But, jQuery exposes `jQuery` and `$` identifiers in global.
How about exposing `Hammer` in global?

**Comment by runspired** [comment]
@sculove how are you loading Hammer?  `Hammer` will be available as a global so long as you aren't requiring it as an `amd` module.

**Comment by arschmitz** [comment]
@sculove This is the proper behavior for a module like this. The reason jQuery exposes the globals regardless is because there are so many existing jQuery plugins that do not use AMD and expect the globals to exist.

**Comment by runspired** [comment]
Interestingly, Lodash exposes as a global even when AMD is present for this reason: https://github.com/lodash/lodash/blob/master/lodash.js#L12329

**Comment by sculove** [comment]
@runspired @arschmitz Thank you for your advice.

I faced a problem regardless of dependency checking when 'A' uses a window.Hammer and `A` is called by `requirejs`
Because Hammer does not expose namespace to global.
So I proposed it.

Of course, I solved it.
I think that Hammer is really worth having a identifier 
because Hammer is a famous library.

**Comment by runspired** [comment]
@arschmitz we should make a "final" decision on this.  I lean towards exposing a global, but I give 3 cares out of 10.

**Comment by arschmitz** [comment]
if you prefer a global lets do it. I still think the current wrapper is the "Correct" one but i don't think it really matters and it does make it a bit easier to use in a few cases.

**Comment by sculove** [comment]
@runspired @arschmitz Thank you for accepting my opinion.

**Comment by runspired** [comment]
Resolved by https://github.com/hammerjs/hammer.js/commit/356f7955b01f3679c29d6c45931679256b45036e
