### ISSUE TITLE
hammer.js (v2.0.4) - problems with user-select css property on windows phone 

### ISSUE THREAD

**Issue by dotnetsharp** [hammerjs/hammer.js#823]
If you use hammer.js (v2.0.4) you may get some problems with text-selection on touch devices (text selection is not working any more). To avoid this behaviour you can remove this option (see http://hammerjs.github.io/tips/):

    delete Hammer.defaults.cssProps.userSelect;

This works, EXCEPT on window phones. Here I cannot find any solution to make text-selection possible.

Any solutions or hacks???

**Comment by runspired** [comment]
See previous discussion here: https://github.com/hammerjs/hammer.js/issues/858
