### ISSUE TITLE
Hammer.js not compatable with new version of Firefox

### ISSUE THREAD

**Issue by AnnaSolovjova** [hammerjs/hammer.js#825]
I am currently developing application using Hammer.js library for multi touch gestures recognition.
The last problem I encountered was hammer.js not working in Firefox 39.0. By not working I mean
that even simple gestures are not recognized. 
 <b>   <br> hammertime.on('press pressup', function(ev) {
             console.log("press");
        });</br> </b>
The method above wouldn't be called. Same for other gesture recognition like swipe, rotate etc.
My code perfectly works in Firefox 38.0.5 and in Chrome.

**Comment by runspired** [comment]
@AnnaSolovjova could you modify this codepen with example code that replicates your issue with firefox 39? http://codepen.io/anon/pen/bNLJbN?editors=101

**Comment by runspired** [comment]
Here is a codepen with this working in firefox 39: http://codepen.io/anon/pen/BNbaPQ

**Comment by AnnaSolovjova** [comment]
Thanks for your time (;
