### ISSUE TITLE
Hammer & Electron integration

### ISSUE THREAD

**Issue by nafem** [hammerjs/hammer.js#827]
I have built a prototype which handles multiple touchable objects that works very well in Chrome on desktop, but when I run it in Electron I get the following error in the first reference to Hammer:
Hammer is not defined

I don't understand because hammer.js is loaded and I can see that Hammer is exported to the window. 

Is there something I am missing?

**Comment by runspired** [comment]
@nafem Electron does not play nice with any frontend AMD modules.  This is a known issue when trying to load any of the popular modules for use with electron.  NW.js does a much better job acting as a wrapper (which is what it sounds like you want) where electron is better if you're ready to get low level.

**Comment by runspired** [comment]
@nafem I'm also currently digging for the solution for this to send to you, because I had to solve it once before months ago before giving up and making NW.js work.

**Comment by runspired** [comment]
@nafem here: https://github.com/atom/electron/issues/355

**Comment by runspired** [comment]
@nafem If this resolves your issue, please not only make a note of it here but follow up with Hammer's status when running via electron.  I can confirm it functions normally in NW.js but I've never had an electron app use Hammer.

**Comment by nafem** [comment]
@runspired Thanks for the pointers.

I want to stay with Electron because I am looking at implementing this on a large touch screen potentially with multiple users and so performance is high priority.

After looking at https://github.com/atom/electron/issues/355 I started to look at using require instead of importing directly. 

Require solved the problem, I use:

    window.$ = window.jQuery = require('jquery');
		var Hammer = require('hammerjs');
		console.log( [$, jQuery, Hammer ]);
