### ISSUE TITLE
how to increase doubletap distance with jquery plugin

### ISSUE THREAD

**Issue by ravianexpert** [hammerjs/hammer.js#830]
I am using two plugin for this, see below
hammer.min.js
jquery.hammer.js

my code is here
$("#selector").hammer().on("doubletap", resetImageZoom);

doubletap is working, but once user click two times on different places, it is not working.

Please provide any solution.

**Comment by runspired** [comment]
```
$("#selector").data("hammer").get('doubletap').set({ threshold: 20 });
```
