### ISSUE TITLE
tap fires while scrolling

### ISSUE THREAD

**Issue by braco** [hammerjs/hammer.js#832]
Is it possible to ignore tap if the view is scrolling?

The problem is that in native views and events, click/tap is only fired if the user is not scrolling. In other words: while scrolling, click/tap should only stop the scroll motion and not fire the click event on DOM.

**Comment by runspired** [comment]
Hammer should not be firing taps while the view is scrolling, I have many implementations of hammer with scrollable lists with multiple possible gestures including tap per list item.  This is likely something in your specific configuration.
