### ISSUE TITLE
Vertical pan disables scroll under ipad

### ISSUE THREAD

**Issue by nicolas-van** [hammerjs/hammer.js#833]
I'm using hammer 2.0.4.

The minimal code to reproduce is this:

    var hammertime = new Hammer($("body")[0], {});
    hammertime.get('pan').set({ direction: Hammer.DIRECTION_ALL });

Even I don't do anything else, this code suffice to disable completely the vertical scroll on ipads (I tested with an ipad2, probably with the latest updates). This behavior is not the same under Android nor Chrome. Under those browsers the scroll works normally and that code has not special effect.

**Comment by runspired** [comment]
@nicolas-van this is why the direction does not default to `Hammer.DIRECTION_ALL`.  This is normal browser behavior.  If you want to listen for vertical events over a large region and still have scroll within that region, you will need to implement a custom scroller for that area.

**Comment by nicolas-van** [comment]
I'm not saying it's a bug that `Hammer.DIRECTION_ALL` prevents the normal scroll of the browser. I'm saying it's a bug that the behavior is inconsistent. It should behave the same way under all browsers, whether the scroll is activated or deactivated under all of them.

**Comment by runspired** [comment]
Assume that it does deactivate scroll for all of them, because (mostly) it does.  http://hammerjs.github.io/touch-action/

**Comment by nicolas-van** [comment]
Chrome and Android together represent a huge percentage of browsers, more than 50% according to statcounter: http://gs.statcounter.com/#all-browser-ww-monthly-201406-201506 . So technically... it doesn't deactivate scroll on most browsers as far as we consider that "most" is a least 50% :)

Anyway, if you expect that using `Hammer.DIRECTION_ALL` deactivate the scroll in browsers, you should force it to be deactivated in all cases. It, for any technical reason, it can not be forced it should at least be cited in the FAQ that the behavior is not consistent.

**Comment by runspired** [comment]
> Chrome and Android together represent a huge percentage of browsers, more than 50% according to statcounter

On all my apps using hammer on Chrome or Android scroll is deactivated when touch events are possible, as this codepen shows: http://codepen.io/anon/pen/QbJGZg?editors=101

Are you mistaking the ability to scroll via the trackpad on chrome for touch events?  Scrolling from the trackpad is unable to be accounted for via Js, and does not have the same limitations that scrolling via touch does.

**Comment by nicolas-van** [comment]
No I'm not using the trackpad-two fingers scroll on desktop. I'm using the mobile device emulation mode of Chrome. (I know the two finger scroll is not the same event :) )

And no, sorry but it doesn't work the way you think it is. I tested your codepen example using the Chrome emulation mode and a Nexus 7 and with those devices I can still scroll using the pan event (aka the "one finger scroll"). I can assert that when I'm using an ipad and doing exactly the same thing the scroll doesn't work. The behavior is different from one device to another.
