### ISSUE TITLE
parent child event propagation

### ISSUE THREAD

**Issue by hpet** [hammerjs/hammer.js#834]
I can't stop events being captured and processed by the parent. I have Hammer instance on body and Hammer instance on child (aka "floatable window"). When I try to close child, parent also already captured whatever event and is holding reference to the child target. This is causing memory issues as targets are being hold by parent Hammer instance.

How can I handle this? I have tried many workarounds but none worked. How does Hammer handle events? Where should I capture and what should I capture in order to prevent parent Hammer instance to get any child triggered events? ...I am trying to understand how this works in Hammer but seems I can't wrap my head around it.

**Comment by runspired** [comment]
Closed in favor of #807
