### ISSUE TITLE
After a press event, not always trigger a pressup event

### ISSUE THREAD

**Issue by superlin** [hammerjs/hammer.js#836]
If i press a button which listen the press and pressup event, after a press event, there will be a pressup event, sometimes not.

Is it designed to be like this or is it a bug?

```
var mc = new Hammer.Manager(container);
  
mc.add(new Hammer.Press());

mc.on('press', function () {
    console.log('press');
});

mc.on('pressup', function () {
    console.log('pressup');
});
```

**Comment by runspired** [comment]
Designed this way, look at #751 for resolution.
