### ISSUE TITLE
Wrong documentation or implementation?

### ISSUE THREAD

**Issue by renie** [hammerjs/hammer.js#837]
The documentation for swipe recognizer says that default direction is 'DIRECTION_ALL' [link](http://hammerjs.github.io/recognizer-swipe/).

Although on [the code](https://github.com/hammerjs/hammer.js/blob/master/src/recognizers/swipe.js) says 'DIRECTION_HORIZONTAL | DIRECTION_VERTICAL'.

Which one is correct?

ps.: I found this because I was trying to use 'swipeup' but it was not working. The event was not being dispatched. So I tried 'hammertime.get('swipe').set({ direction: Hammer.DIRECTION_ALL });' and it works.

ps2.: I could do a pull request, but I need to know if I edit the code or the doc =)

**Comment by arschmitz** [comment]
@renie actually if you read the note at the bottom of the page you link you will see it says

 > When calling Hammer() to create a simple instance, the pan and swipe recognizers are configured to only detect horizontal gestures.

Closing this as not an issue.
