### ISSUE TITLE
[META] Hammer's Default Configuration Leaves Gesture Detection Gaps

### ISSUE THREAD

**Issue by runspired** [hammerjs/hammer.js#838]
Gaps currently exist between pan and swipe, and between tap and press.  This is especially confusing for new users who just want to drop it in and play.

These gaps may be problematic for detecting any taps on some mobile devices.  A hypothesis is that this relates to pixel density.  The default tap movement threshold should likely be adjusted higher (to meet pan at 9px, possibly more), to avoid issues like #804 

Velocity settings (and default configuration) should be explained.  Most velocity values will lead to very few swipes being registered.  It's possible we might want to provide a few scenarios for when to use pan versus when to use swipe.  It seems much swipe usage is better suited for and likely intended to be pan usage, but the difference between the mental constructs is poorly understood.

The following affected issues are closed by this meta ticket.
- #804 
- #814

The following affected issues are not closed by this meta ticket.
- #776

**Comment by holic** [comment]
By default configuration, does this mean the options that define each gesture or the default `Hammer` instance (as opposed to `Hammer.Manager`)?

**Comment by runspired** [comment]
It applies to both.

**Comment by holic** [comment]
Great. I am seeing issues with Samsung devices specifically when trying to recognize gestures using an instance of `Hammer.Manager`. Looking forward to the improvements!

**Comment by runspired** [comment]
Closed by #860
