### ISSUE TITLE
[Question] is it safe to include this in a page that has to support ie8 but no gestures?

### ISSUE THREAD

**Issue by QuantumInformation** [hammerjs/hammer.js#843]
I need access to the pinch zoom test to see if the user has zoomed in ie9+. I don't need this test for ie8 but I need to know if it is safe to have this script included in a page supporting ie8.

**Comment by QuantumInformation** [comment]
I wonder if I could just add es5-shim, because ie8 doesn't have object.create..

**Comment by arschmitz** [comment]
@QuantumInformation We don't test on ie8 at all so i would not want to make any guarantee that it would even parse. Why don't you use IE conditional comments to only include if your in ie9 or newer?

Closing this as a question.

**Comment by QuantumInformation** [comment]
thanks @arschmitz, we just want to use the library to detect a change of zoom from the default for that device at the viewport setting, can anyone advice whether this is possible?

**Comment by arschmitz** [comment]
@QuantumInformation no that is not something hammer does we provide gesture recognition we do not handle zoom. we just have pinchin and out events that can be used for zooming. 

There is no way to reliably detect the level of browser zoom in most browsers so i don't think what you want is possible.
