### ISSUE TITLE
Panend event is not triggered when releasing mouse outside Internet Explorer browser window

### ISSUE THREAD

**Issue by mroloux** [hammerjs/hammer.js#845]
Hi,

I noticed a difference in behaviour between Chrome and IE11 on Windows 7.

In Chrome, when you start dragging and release the mouse button outside the browser window, the panend event is fired properly. In IE11 this doesn't happen - the panend event is never fired.

Example at http://jsfiddle.net/uatze0zy/3/

Any ideas?

Matti

**Comment by runspired** [comment]
This is because of limitations of the browsers themselves.  There's unfortunately not much we can do.

Related: https://github.com/hammerjs/hammer.js/issues/707

**Comment by JulianKingman** [comment]
Any work-arounds for this issue?

**Comment by arschmitz** [comment]
We have some workarounds for this case in jQuery UI for draggable ill get a link

**Comment by JulianKingman** [comment]
Thanks.

**Comment by runspired** [comment]
Ping @arschmitz link :D

**Comment by arschmitz** [comment]
@runspired thanks for the reminder the code is in our mouse widget https://github.com/jquery/jquery-ui/blob/master/ui/widgets/mouse.js It's a little spread out though handling different cases its in the `_mouseUp`, `_mouseDown` and `_mouseMove` functions there are all kinds of edge cases involved too for ie and safari

**Comment by JulianKingman** [comment]
What's `documentMode`?

**Comment by arschmitz** [comment]
@JulianKingman it tells you what document mode (compatibility mode) IE is running in older IE's ( up through 10 ) had the ability to set their rendering mode ( which version of IE that ran as ) The document mode tells you which one has been set. https://msdn.microsoft.com/en-us/library/cc196988(v=vs.85).aspx
