### ISSUE TITLE
Inappropriate default touch-action for DIRECTION_ALL swipe

### ISSUE THREAD

**Issue by patrickhlauke** [hammerjs/hammer.js#846]
```
var hammertime = Hammer(el);
hammertime.get('swipe').set({ direction: Hammer.DIRECTION_ALL });
```

results in `touch-action: pan-x pan-y` being set on the element. this tells the browser that it *should* handle panning in all directions, meaning that the swipe never registers at all in IE11/MS Edge. It should be `touch-action: none`.

I suspect in other browsers it currently does work (to an extent) because the JS fallback kicks in instead.

**Comment by patrickhlauke** [comment]
in the meantime, I circumvented the issue with

```
var hammertime = Hammer(el, { touchAction: 'none' });
hammertime.get('swipe').set({ direction: Hammer.DIRECTION_ALL });
```

see http://patrickhlauke.github.io/touch/hammer/swipe/

**Comment by elmonty** [comment]
It's not just DIRECTION_ALL.  Hammer does not fire any pan events in touch IE11 with DIRECTION_VERTICAL unless I use your code above to set touchAction to 'none'.

**Comment by patrickhlauke** [comment]
@elmonty see https://github.com/hammerjs/hammer.js/pull/855
