### ISSUE TITLE
Disable hammer on specific div

### ISSUE THREAD

**Issue by Silvering** [hammerjs/hammer.js#847]
Hi eveyone! I'm using the Carousel demo which is exactly what I was looking for. However inside each slide I have texts blocks with vertical scroll. I would like to disable the possibility to swipe up/down when the user try to use the scroll. Here is my code : https://gist.github.com/Silvering/f455abfc663f68c25403

Any idea? Thanks a lot!

**Comment by runspired** [comment]
@Silvering questions on usage belong on StackOverflow or in the Hammer Slack channel, thanks.
