### ISSUE TITLE
Double Tab event does not work in Android Phone

### ISSUE THREAD

**Issue by JohnnyLe** [hammerjs/hammer.js#848]
Hi everyone!

I got a problem with ```doubletap``` event  on some Android Phone devices as bellow

- (Phone) Sony XPERIA C3 - Android 4.4.2, Chrome 44
- (Phone) Sony XPERIA J1-Compact, Android 4.4.4, Chrome 44
- (Phone) Sony XPERIA SO-02F, Android 4.4.2(updated from 4.2), Chrome 44
- (Phone) Sony XPERIA SO-05D, Android 4.1.2, Chrome 44
- (Tablet) ASUS Pad TF-300T, Android 4.1.1, Chrome 44

You can easy to reproduce the problem in the test page http://hammerjs.github.io/ 

Very appreciated if everyone can share root cause and solution to fix.

**Comment by runspired** [comment]
@JohnnyLe could you share your Hammer setup? Double tap isn't a default event in many setups, and can be configured with or without requireFailures that make it harder to trigger.

**Comment by JohnnyLe** [comment]
Hi @runspired 

Thank you for your advice.

Bellow are simple my setting up of Hammer.

- HTML, it's using hammer.min.js version v2.0.4 - 2014-09-28

```
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="css/jquery.ui.css"/>
        <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css"/>
        <link rel="stylesheet" type="text/css" href="css/app.css"/>
        
        <script src="js/libs/jquery.min.js"></script>
        <script src="js/libs/jquery.ui.min.js"></script>
        <!--<script src="js/libs/jquery.ui.touch-punch.min.js"></script>-->
        <script src="js/libs/lodash.js"></script>
        <script src="js/libs/hammer.min.js"></script>
        <!--<script src="js/libs/kinetic-v5.1.0.min.js"></script>-->
        <!--<script src="js/PinchLayer.js"></script>-->
        
        <script src="js/watermark.js"></script>
        <script src="js/app.js"></script>
        <title>App</title>
        <!-- Support scale across devices -->
        <meta name="viewport" http-equiv="X-UA-Compatible" content="width=device-width, maximum-scale=1.0, user-scalable=no">
    </head>
    <body> 
        
        <!-- Image content -->
        <div id="screen">
            <!-- Main page -->
            <canvas id="canvas">Your browser does't support canvas</canvas>          
        </div>        
    </body>
</html>
```

- JavaScript Code app.js

```
// Canvas obj
this.canvas = document.getElementById("canvas");

// Setup Hammer
 var mc = new Hammer.Manager( this.canvas );
mc.add(new Hammer.Pan({ threshold: 0, pointers: 0 }));
mc.add(new Hammer.Pinch({ threshold: 0 })).recognizeWith([mc.get('pan')]);        
mc.add( new Hammer.Tap({event: 'doubletap', taps: 2 }));
mc.add(new Hammer.Tap( { event: 'singletap' } ));
mc.add( new Hammer.Swipe()).recognizeWith( [mc.get('pan')] );

 // Bind event
 mc.on("doubletap", onDoubleTap.bind( this ));

 // On double tab
 function onDoubleTap() {
      // Callback when doubletab trigger      
 };

```

It works ok in Desktop PC and iOS, but with above Android device it does not trigger double tab event.

But it seems there is problem with the Hammer library in above Android devices, because I tested default setup as home page http://hammerjs.github.io/ in those devices and the result is the same.

Do you have any idea?

Thanks
Johnny

**Comment by runspired** [comment]
It's probably not a bug in hammer (my double tap has worked fine for Android).  It's likely the fact the of those platforms you are testing, only android correctly uses touch-action CSS.

There's also the issue that scaling and pixel densities are treated differently, I often have to expand the distance threshold for Android devices.

Also: this needs `recognizeWith` or `recognizeFailure`.
```
mc.add( new Hammer.Tap({event: 'doubletap', taps: 2 }));
mc.add(new Hammer.Tap( { event: 'singletap' } ));
```

**Comment by JohnnyLe** [comment]
So you mean should use requireFailure like guideline at http://hammerjs.github.io/require-failure/ ?

```
var singleTap = new Hammer.Tap({ event: 'singletap' });
var doubleTap = new Hammer.Tap({event: 'doubletap', taps: 2 });

hammer.add([doubleTap, singleTap]);

tripleTap.recognizeWith([doubleTap, singleTap]);
doubleTap.recognizeWith(singleTap);

singleTap.requireFailure([doubleTap]);
```

**Comment by JohnnyLe** [comment]
I have tried, but the problem is the same in Sony XPERIA C3 - Android 4.4.2, Chrome 44. 
Did you can reproduce in the same device with the page http://hammerjs.github.io/ ?

Thanks for your following up.

**Comment by kelonye** [comment]
@JohnnyLe worked for me when I passed the `recognizers` option as an empty array as  in [test_multiple_taps.js#L10](https://github.com/hammerjs/hammer.js/blob/52a090e79bf23af5da4bece36535b66191f5a063/tests/unit/test_multiple_taps.js#L10)

**Comment by kokers** [comment]
@JohnnyLe Did you found a solution?

All my tap (singletap, doubletap etc) are not working on Xperia Z2
Chrome 46.0.2490.76
Android 5.1.1

Even with the simple:

		$('.show-on-hover').hammer().on("tap", function(){
			$(this).toggleClass('hover');
		});

Other devices works fine.

Doesnt work on demo page too  http://hammerjs.github.io/
