### ISSUE TITLE
r.js optimizer compatible amd support check (for requirejs with namespace)

### ISSUE THREAD

**Issue by meszarv** [hammerjs/hammer.js#852]
When requirejs optimizer (r.js) compiles javascript application into one file and with namespace option  defined in the configuration, it will not compile hammer.js correctly. 
To support this optimization,  the check for amd support in the page should be in this exact form: 
`typeof define === 'function' && define.amd`
which is then compiled into this form:
`typeof myNamespace.define === 'function' && myNamespace.define.amd`
[http://requirejs.org/docs/faq-optimization.html#namespace](http://requirejs.org/docs/faq-optimization.html#namespace)

**Comment by runspired** [comment]
This is resolved by an open PR that's ready to be merged.
