### ISSUE TITLE
touch-action style is not removed on destroy

### ISSUE THREAD

**Issue by joeporpeglia** [hammerjs/hammer.js#853]
After calling `destroy` I still see `touch-action: pan-y` in the style attribute of my container.

**Comment by cofeer** [comment]
Seeing similarly, the `touch-action:none` style attribute on my container after `destroy` called.

**Comment by runspired** [comment]
@arschmitz to fix this we would have to keep track of whether we were the ones to have set the touchAction property.  Perhaps we could cache any older / existing values and replace with that when tearing down?

**Comment by frederikbosch** [comment]
Or register a data attribute for this? `data-hammer-prev-style`? And put it back to the previous value when destroying?

**Comment by sculove** [comment]
I add feature about this issue. #900
