### ISSUE TITLE
How can I prevent Hammer to prevent natural scroll?

### ISSUE THREAD

**Issue by verlok** [hammerjs/hammer.js#854]
Hi,
I just started using Hammer 2 and I love it (see [my tweet](https://twitter.com/verlok)).
I use Hammer to change the size of an image on pinch, but this image is inside a naturally scrollable area (overflow: touch) and when I start to use Hammer, it prevents the natural scroll of the scrollable area.
Is there a fix to this?
Thank you

**Comment by MacroX1990** [comment]
this is what I did:

var mc = new Hammer.Manager(myElement, {
        touchAction: 'manipulation'
    });
    mc.add([new Hammer.Pinch()]);

    mc.on("pinchin", function (ev) {
        //code
    });
    mc.on("pinchout", function (ev) {
        //code
    });

I hope this helps

**Comment by runspired** [comment]
See (for instance) my response on #856
