### ISSUE TITLE
Uncaught TypeError: value.toLowerCase is not a function 

### ISSUE THREAD

**Issue by catalinux** [hammerjs/hammer.js#864]
I'm using such setting

```
    var options = {
      touchAction: true,
      recognizers: {
        pan: { enable: true, threshold: 0 },
        pinch: { enable: true, threshold: 10 },
//        swipe: { enable: true, threshold: 10 },
        tap: {
          time: 600,
          threshold: 100
        }
      }
    };
```

and
```jsx
        <Hammer action={this.action} onTap={this.handleTap} onSwipe={this.handleSwipe} onPan={this.handlePan} options={options}>
          <img style={imageStyle} src={this.props.image}/>
        </Hammer>
```

But I get the error in title. The problem is that value that "comes" into the function is "true" - boolean type

I'm using 
```
    "react": "^0.14.0",
    "react-dom": "^0.14.0",

**Comment by runspired** [comment]
This is an error with your own handler.

**Comment by catalinux** [comment]
Hi, 

can you add more details? that erros come at line 38 https://github.com/hammerjs/hammer.js/blob/82dc62322ffeb7abf731ba6e3465239f581d2f3b/src/touchaction.js#L38

**Comment by runspired** [comment]
`touchAction: true,` isn't a valid option.  It should be a string of the touch-action property you want used.
See the docs: http://hammerjs.github.io/touch-action/

Ask questions on StackOverflow or Slack: http://hammerjs-slackin.herokuapp.com/ (seems to be down atm, pinged @jtangelder to get it back up).
