### ISSUE TITLE
Add information about disabled events directly in the recognizers

### ISSUE THREAD

**Issue by julmot** [hammerjs/hammer.js#870]
I just searched a long time for the question why my "pinch" event is not working. I didn't find anything in the recognizer documentation, API, but on [Stackoverflow](http://stackoverflow.com/a/25551305/3894981). I know you guys have issued this in the "Getting started" section. However, I didn't read this because my application is already using hammerjs for over years and I just needed to add a "pinch" event and not to read the Getting Started guide again. So in my opinion, the information about disabled events should be directly in the related page, e.g. for "pinch" it should be [here](http://hammerjs.github.io/recognizer-pinch/).

**Comment by runspired** [comment]
I agree, can you PR that?

**Comment by arschmitz** [comment]
:+1:

**Comment by julmot** [comment]
I'll do a pull request later.

**Comment by julmot** [comment]
Someone just need to merge it.

**Comment by runspired** [comment]
@julmot thanks! Closing here, hopefully @arschmitz can do a docs release with that?
