### ISSUE TITLE
jQuery 2.1.4 multiple selectors not working

### ISSUE THREAD

**Issue by aicm** [hammerjs/hammer.js#872]
Hello there,

It seems hammer cannot bind on a multiple selector, i.e. `$("#id1,#id2").hammer()...`

Here's the code: http://jsfiddle.net/1qacj0ct/2/
Here's the screen recording: https://www.dropbox.com/s/7q0185j4ikgcw9z/hammerjs-bug.mp4?dl=1

Thanks :+1:

**Comment by runspired** [comment]
This should be reported to https://github.com/hammerjs/jquery.hammer.js

**Comment by aicm** [comment]
Thanks for your prompt attention to this matter. Not to mention the awesome reply :-1:
