### ISSUE TITLE
panstart doesn't fire before pan[direction]

### ISSUE THREAD

**Issue by adithya217** [hammerjs/hammer.js#873]
From the docs, I assumed that on attaching:

```javascript
mc.on('panstart panup pandown panend', function(event){ ... })
```
A panstart is triggered before pan up / down are triggered. But that doesn't seem to be the case. A single pan up / down is triggered before the panstart event. To have an alternative to this, I tried using:

```javascript
mc.on('panup pandown', function(event){ console.log(event.isFirst); })
```
But isFirst doesn't seem to be true ever.

Anyway to know if an event is the first for its input type? This scenario helps in setting up some variables after detecting a first input of its type.

**Comment by runspired** [comment]
This is fixed on master and will be included in the next release.
