### ISSUE TITLE
HammerJS Manager off() errors out if there wasn't an on()

### ISSUE THREAD

**Issue by soluml** [hammerjs/hammer.js#874]
If you try to `.off()` an event before having done an `.on()` you end up with a `Uncaught TypeError: Cannot read property 'splice' of undefined` error.  This is because the managers handlers object is empty.  Here's a [CodePen showing the issue](http://codepen.io/soluml/pen/XmOeLQ?editors=001).

Should be an easy fix, I'll try to submit a pull request later.

**Comment by runspired** [comment]
This is already fixed on master.

**Comment by soluml** [comment]
Is there a build after 2.0.4?  I'm running 2.0.4 in the example above.  Would be great if it's fixed.
