### ISSUE TITLE
Horizontal pan and full pan cannot work together when using requireFailure

### ISSUE THREAD

**Issue by loganfuller** [hammerjs/hammer.js#875]
I'm running into issues with adding a horizontal pan recognizer on a parent element and a full pan recognizer on a child with the child requiring failure of the parent. It works fine when the parent is a horizontal pan and the child is a vertical pan, but I can only scroll vertically when I set the child to a full pan recognizer.

```javascript
// Parent
// ---------

this.hammerHoriz = new Hammer.Pan({
    direction: Hammer.DIRECTION_HORIZONTAL,
    threshold: 5,
});

this.hammerParent = new Hammer.Manager(parentDomEl);
this.hammerParent.add(this.hammerHoriz);

this.hammerParent.on("panstart", this.handleParentPanStart);
this.hammerParent.on("pan", this.handleParentPan);
this.hammerParent.on("pancancel", this.handleParentPanEnd);
this.hammerParent.on("panend", this.handleParentPanEnd);


// Child
// ------

this.hammerPan = new Hammer.Pan({
    direction: Hammer.DIRECTION_ALL,
    threshold: 5,
});

this.hammerChild = new Hammer.Manager(childDomEl);

this.hammerPan.requireFailure(this.hammerHoriz);

this.hammerChild.add(this.hammerPan);

this.hammerChild.on("panstart", this.handleChildPanStart);
this.hammerChild.on("pan", this.handleChildPan);
this.hammerChild.on("pancancel", this.handleChildPanEnd);
this.hammerChild.on("panend", this.handleChildPanEnd);
```

**Comment by runspired** [comment]
This is due to leaked configuration objects that get shared between recognizer and manager instances.  It's currently fixed on master and will be included in the upcoming patch release.  We're down to one bug (`pointers.length`) that needs patched before we can ship.

**Comment by loganfuller** [comment]
That's great to hear! Is there a recommended hotfix in the meantime?

**Comment by runspired** [comment]
Unfortunately, there is not a hotfix for that bug that I'm aware of, you'd need to build from master.
