### ISSUE TITLE
Cannot be used with virtual DOMs

### ISSUE THREAD

**Issue by Frikki** [hammerjs/hammer.js#877]
It seems as Hammer can’t leave elements in peace. For touch events, this inline style is set on elements:

```
touch-action: pan-y; -webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
```

This completely eliminates any hope for using this library with virtual DOMs. Sadly! :(

**Comment by runspired** [comment]
Use a better virtual Dom :p

But seriously, most VD implementations handle this just fine.  Also, the styles you are complaining about are necessary, hammer is functioning as a touch-action polyfill, something that will continue to improve overtime.

**Comment by Frikki** [comment]
Any suggestions on which vdom to use then?

**Comment by runspired** [comment]
Any implementation that doesn't wipe out your element references without warning, or (alternatively) which doesn't diff your actual DOM.

Which implementation are you using that's giving you trouble?

**Comment by Frikki** [comment]
@runspired I’m using Matt Esch’s virtual-dom.

**Comment by runspired** [comment]
Given that lib is so heavily react-inspired, there's probably a version of this which you need: https://facebook.github.io/react/docs/more-about-refs.html

The implementation you are using seems to have very sparse documentation, but I'm guessing you need to be attaching to `rootNode`: https://github.com/Matt-Esch/virtual-dom/blob/master/vdom/README.md#example

It looks like you then would need to copy `rootNode.style` to `leftNode.style` after initializing Hammer.

**Comment by runspired** [comment]
(Also, sucks that the patch is applied directly to `rootNode`, there should be another layer there managed for you for staging, surprised there isn't).

**Comment by Frikki** [comment]
@runspired Am I wrong in my assumption that a new instance on Hammer is needed for each element we want to apply listeners to?

**Comment by runspired** [comment]
I'm not sure what you mean to ask.

A new instance of Hammer.Manager would be needed for each DOM tree / DOM region you want a unique manager for.

**Comment by Frikki** [comment]
Maybe it’s be that doesn’t understand the docs well enough, but why would I need a separate manager for a tree/region? Why not just one manager for the whole DOM?

**Comment by runspired** [comment]
You could use one manager for the whole DOM, but then anywhere you wanted to use native `scroll` either horizontal or vertical would likely be prevented.

**Comment by Frikki** [comment]
@runspired Also for, say a `div` with scroll in the DOM tree?

**Comment by runspired** [comment]
Correct, `touch-action` is a CSS property that controls whether the developer or the device is going to get to control the outcome of a `touch`.  https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

**Comment by Frikki** [comment]
Okay, so I’m screwed because these styles are set imperatively by Hammer. Thank you for you explanation, @runspired .

**Comment by runspired** [comment]
You can *probably* get the particular `virtual-dom` implementation you are using to work by copying what Hammer does to your virtual-implementation so that it won't be overwritten on the next patch.

**Comment by danielnaab** [comment]
@Frikki, did you happen to come up with a solution to this? I've been using `virtual-dom` with touch events also, but thinking that some kind of [widget](https://github.com/Matt-Esch/virtual-dom/blob/master/docs/widget.md) could wrap the Hammer events. [This](https://github.com/JedWatson/react-hammerjs/blob/master/src/Hammer.js) looks like a reasonable starting point. I'm looking into it now...

**Comment by Frikki** [comment]
@danielnaab I managed to make a [hammer.js driver](https://github.com/CyclicMaterials/cycle-hammer-driver) for [Cycle.js](http://cycle.js.org/) that uses *virtual-dom*.

**Comment by danielnaab** [comment]
Thanks @Frikki. I'm not using `Cycle.js`, but more of a [Mercury](https://github.com/Raynos/mercury)-style approach. This isn't tested, but I put a widget together yesterday based on [react-hammerjs](https://github.com/JedWatson/react-hammerjs/blob/master/src/Hammer.js): https://github.com/danielnaab/virtual-dom-hammerjs

**Comment by runspired** [comment]
@Frikki @danielnaab if in the process you identify something that is absolutely not able to be done in your current approaches or just annoyingly complicated to do, please report back.  I think we'd be willing to add something to 2.1 or 2.2 to make this easier if needed as long as it were a minimal change.

**Comment by arschmitz** [comment]
@runspired totally agree as long as its not a huge change all for making this work

**Comment by Frikki** [comment]
@runspired Thanks. The Cycle.js Hammer driver is in early stages and need community feedback. If we find issues that cannot be solved by ourselves, I’ll definitely report back. Cycle.js embraces functional programming and isolation of side effects through the use of drivers. Hammer.js, on the other hand, seem quite "class"-oriented in its style.

**Comment by danielnaab** [comment]
@runspired virtual-dom-hammerjs is working for me as of now, although it's probably doing something wrong. I'm learning how to use Hammer as I go, which is maybe not the best approach :)

One nice thing that might help with object reuse is if it were possible to create a Hammer object that isn't parented to a node, and then add/remove the attached node at a later point. In practice it's not really needed, though.

**Comment by runspired** [comment]
@danielnaab an element-less manager instance and the ability to swap elements, and possibly even a `dispatch` method for sending an event to a manager might be things I'd consider.  I've bumped into situations where reusing the manager with a new element was ideal before.  @arschmitz thoughts?

**Comment by arschmitz** [comment]
These are things im open to in general but that would be 3.0
