### ISSUE TITLE
Memory Leak or Usage Problem, not sure

### ISSUE THREAD

**Issue by garygriswold** [hammerjs/hammer.js#878]
I have an application that is creating and destroying tappable elements frequently, and I am seeing continual memory growth when I create and destroy hundreds of elements which are all tappable.  Is there something I am doing wrong, or is this a bug?  The following is how I create the listeners.

     var touchableNode = new Hammer(domNode);
     touchableNode.on('tap', function(event) {
           ....
     }

**Comment by runspired** [comment]
@garygriswold you destroy the hammer instance and null it out when you destroy the tappable element, yes?

**Comment by garygriswold** [comment]
Chris,

You are correct in thinking that I do not destroy and null out the Hammer instances.  It has not been my habit, since removing the root DOM node of a tree releases DOM objects from memory just fine with no additional processing.  But, I certainly will hold references to all of the Hammer instances so they can be individually destroyed, if that is what is required.  But one more thing, I am not exactly sure of what syntax you mean by the word destroy.  Is there a destroy() method on the Hammer instance?

Gary

**Comment by BAM5** [comment]
@garygriswold [destroy()](http://hammerjs.github.io/api/#destroy())

Also, perhaps you should familiarize yourself with garbage collection?

**Comment by runspired** [comment]
@garygriswold 

>  since removing the root DOM node of a tree releases DOM objects from memory just fine with no additional processing

That's not actually true.  Removing the root DOM node only removes itself and it's children if nothing retains them in memory.  Event listeners and variables that have references to nodes in that tree will cause them to be retained.  Call destroy on the Hammer instance, and null it out for good measure and you shouldn't have a memory retention issue anymore.
