### ISSUE TITLE
Version 2.0.5 Blockers

### ISSUE THREAD

**Issue by frederikbosch** [hammerjs/hammer.js#879]
In this [this thread](https://github.com/runspired/ember-gestures/issues/7) @runspired told me there are bug blockers for the 2.0.5 release of hammerjs. It might be helpful to register which ones. Then people can help to create PRs for these specific bugs.

**Comment by IgorMinar** [comment]
Can you please provide update or ETA please? https://github.com/angular/angular/issues/5766 is still blocked on this. Thanks!

**Comment by runspired** [comment]
@IgorMinar I thought I was going to have time yesterday but didn't, hoping to have some time this afternoon instead.

**Comment by runspired** [comment]
Release is landing.

**Comment by frederikbosch** [comment]
@runspired Great work!

**Comment by runspired** [comment]
Thanks! @arschmitz should have the new build pushed up after a lunch meeting :)
