### ISSUE TITLE
$(...).hammer is not a function(…)

### ISSUE THREAD

**Issue by JDSGIT** [hammerjs/hammer.js#884]
Hey Hammer,

Mea culpa, I'm not our mobile developer - he's actually out this week and I'm trying to stumble through some errors that just started today randomly.  I a .net/DB guy and won't pretend anything here but hoping you can point me in the right direction.

We're using a lot of the controls/touches from Hammer and it's been awesome/worked great.  It appears, however, that a partner of ours is maybe generating an error which is causing our entire .js file to to fail on each function $(...).hammer

The only issue I'm seeing before the hammer issue is this:

jquery-1.6.2.min.js?07192014&_=1449619888200:18 'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.

Which generates thousands of errors in our file:
TypeError: $(...).hammer is not a function(…)
Uncaught TypeError: $(...).hammer is not a function

Do you know how or why the content were are framing in for this partner (carfax) would cause our library to break?  When we disable their content (i.e. turn off the service for our users, everything works fine).  Maybe this is standard behavior in mobile I really don't know the processing logic but trying to issue a patch as my bro is unreachable.

Do we need to update our hammer?  This is what all we are using:
/*! iScroll v5.1.3
iscroll.stickyheaders.js
jquery-2.0.3.min.js
jquery.animinate
jquery.hammer.min.js v1.0.0
jquery.sticky.js v.1.0.0
mobiscroll.custom.2.9.2.min.js

I know, probably more than you needed but felt it may be prudent to list it all.  Any suggestions on why every hammer function is throwing an error?

Thanks in advance,
Jason

**Comment by runspired** [comment]
@JDSGIT please reach out on slack for support, would be glad to discuss: http://hammerjs-slackin.herokuapp.com/

**Comment by JDSGIT** [comment]
will do thanks.  that url doesn't work and tried several googles.  what exactly or where is the support forum?  all the best,
jason

**Comment by JDSGIT** [comment]
...nevermind, it came up now for some reason.  thanks.

**Comment by runspired** [comment]
Fixed the link above: https://hammerjs.herokuapp.com/
