### ISSUE TITLE
Can you please cut 2.0.5 for Angular 2?

### ISSUE THREAD

**Issue by IgorMinar** [hammerjs/hammer.js#886]
angular/angular needs unreleased fixes for #688 and #644 (commit in master: da49a2730779ecc3b4dd147cc418a0df7c70fad9)

we'd like to declare a peerDepedency on hammerjs in npm, but can't until there is a release in npm (since it's a peer dependency, we don't want to fork your repo and ask people to depend on our git branch).

can you please cut 2.0.5? I believe the current contents of master are sufficient to resolve both #688 and #644. thank you!

related issue: https://github.com/angular/angular/issues/5766

// @adamdbradley for Ionic

**Comment by runspired** [comment]
We'll be cutting soon, the pointer.length bug is pernicious, with the overwhelming number of tickets (of actual bugs) pointing back to it.  We don't want to release with out it.

**Comment by IgorMinar** [comment]
thanks

**Comment by jtangelder** [comment]
Thanks @runspired :-)
