### ISSUE TITLE
When will be npm release?

### ISSUE THREAD

**Issue by Delagen** [hammerjs/hammer.js#897]
No for 2.0.5 & 2.0.6

**Comment by runspired** [comment]
We unfortunately don't have control over the ability to publish to NPM,  The original author   Needs to give us access.  We are working on it :)

**Comment by Delagen** [comment]
May be publish under another name? hammer-js for example?

**Comment by runspired** [comment]
Would defeat the purpose.  You can install directly from the tag with npm if you need it now.

**Comment by jtangelder** [comment]
Published!
