### ISSUE TITLE
Vertical Scroll is not working in iOS Devices

### ISSUE THREAD

**Issue by shmdhussain** [hammerjs/hammer.js#902]
Using hammer.js (v 2.0) I tried to trigger events for the pandown gesture, but when the element Which I am applying the gesture event is having more content than the browser layout height, the default scrolling stops, see this codepen http://codepen.io/shmdhussain/pen/GomRVw#0 

Issue happening in iOS Devices iPhone ( tested on iPhone 6Plus with iOS 8.4.1)

**Comment by arschmitz** [comment]
@shmdhussain this is intentional vertical pan and scrolling cant coexist because they are the same gesture. see http://hammerjs.github.io/touch-action/

**Comment by shmdhussain** [comment]
I am Implementing Pull to Refresh, How could I Implement?, If the content is more, user will always want to scroll down the page.

**Comment by arschmitz** [comment]
Pull to refresh in the browser is not really supported currently there are several well known issues that prevent this sort of functionality right now these are being worked on at the browser and spec level. If you google around you will find some people that have found some ways to make it work ok. This is not something that hammer does though.

**Comment by runspired** [comment]
@shmdhussain the best way I've seen this accomplished is to hook into `scroll` and if/when scroll offset is "0" start "pulling" instead

**Comment by shmdhussain** [comment]
@runspired @arschmitz Thanks For suggestions and help. I Implemented this usingt he code shared by berkin http://codepen.io/berkin/pen/jyfHq see this implementation

**Comment by sharath90** [comment]
@shmdhussain Were you able to fix the scroll issue ?

**Comment by shmdhussain** [comment]
Yes sharath ...see my post above...I used older version. I am able to do that....

**Comment by sharath90** [comment]
Thanks @shmdhussain for quick reply. I tried the link, pull to refresh works good, but I cannot use mouse left button to scroll. Basically I have to implement pull to refresh on mobile web, where both scroll using touch and drag at the top the container(this is to refresh content) should work. Let me know if you think of anything. Thanks in advance.

**Comment by shmdhussain** [comment]
Sharath disable scrolling when user pulls down and enable again when user release....so scrolling will work.....

**Comment by sharath90** [comment]
How would you disable/enable scroll ? Sorry for asking detail things.
