### ISSUE TITLE
panstart event only fires on horizontal movement when direction is set to DIRECTION_ALL

### ISSUE THREAD

**Issue by daniel-erickson** [hammerjs/hammer.js#910]
My understanding is that the default value of DIRECTION_ALL should fire 'panstart' in any direction after reaching the threshold, currently it will only fire on horizontal movement. This is due to the test on line 48 of recognizers/pan.js passing when it is set to  DIRECTION_ALL. Failing would be just as bad as then it would only work on vertical movement. I can get around this if it is intended behaviour, otherwise I would love a fix.
Thanks!

**Comment by daniel-erickson** [comment]
I just found the note in the documentation to state that a simple Hammer() is only setup to detect horizontal gestures. I don't believe it is possible to have a 2 dimensional (X,Y) pan at this stage? Im not actually using the panning functionality, I just want to use the events that hammer provides.

**Comment by runspired** [comment]
@daniel-erickson please ask further support questions on the Slack.

To get all directions to work, use a Manager and add the recognizers yourself (see the codepen in the readme).

To get all directions to work AND to not break scroll, you will need to adjust touch-action: http://hammerjs.github.io/touch-action/
