### ISSUE TITLE
[2.0] I can't preventdefault on an anchor tap

### ISSUE THREAD

**Issue by dschissler** [hammerjs/hammer.js#911]
I simply want to prevent the anchor element from going to the href location.  This is a pretty basic and common maneuver but nothing seems to work and apparently many things have changed in version 2.0.

```javascript
    let mAnchor = new Hammer.Manager(this.anchor, {
      domEvents: true
    });
    mAnchor.add(new Hammer.Tap());
    mAnchor.on('tap', (e) => {
      e.srcEvent.preventDefault();
      e.preventDefault();
      e.gesture.preventDefault();
    });
```

**Comment by runspired** [comment]
You would need to prevent default on the click, `tap` is not a click, nor click based.

**Comment by dschissler** [comment]
The `tap` event fires when I click the damn link.

**Comment by runspired** [comment]
... so add a click handler and prevent default on the click
