### ISSUE TITLE
event.velocityX in panend has changed sign between 2.0.4 and 2.0.5

### ISSUE THREAD

**Issue by robations** [hammerjs/hammer.js#915]
The sign of `event.velocityX` in the panend callback seems to have changed sign between versions 2.0.4 and 2.0.5. This is on a element configured for `Hammer.DIRECTION_HORIZONTAL`.

At the moment I'm not sure if this was a deliberate bug fix or unintended. Either way, with 2.0.4:

- panend velocity is +ve when panning right to left (and vice versa)

With 2.0.5 and 2.0.6:

- panend velocity is -ve when panning right to left (and vice versa)

I don't have a minimal test case but can provide one if it would be helpful (time allowing).

**Comment by robations** [comment]
It's like "natural scrolling" all over again! :)

I see there is a commit that switches the `input.deltaX - last.deltaX` that feeds into the velocity calculation. Anyway, I've pegged hammerjs to 2.0.4 until I can work out what's happening.

**Comment by arschmitz** [comment]
i believe you are referring to this commit https://github.com/hammerjs/hammer.js/commit/e40dcde43bdac7a74c8ce5c05a4f62121089cd91 the one you link is just the update of the dist file for release. There was a bug and the values were reversed in the calculation

**Comment by robations** [comment]
Thanks for the extra info. Too late now but it might have been worth a new major version, even though it's a bug. This was a surprising change in backwards compatibility for my project and I had multiple instances of the project with strangely inconsistent behaviour.
