### ISSUE TITLE
HammerTime.js adding touch-action:none to all elements automatically.

### ISSUE THREAD

**Issue by fattalgazi** [hammerjs/hammer.js#919]
As I understand, we have to add `style="touch-action: none"` attribute to all elements which we want to disable 300 ms delay. 

It is difficult work for me because we have a lot of pages, because of this reason, I added that js code to my document on ready function.

```
    //fast clicks
    $('input, select, label, span, i').each(function()
    {
        var newStyleAttr = "touch-action: none;";
        var hasStyleAttr = $(this).attr('style');
        if(hasStyleAttr){
            newStyleAttr = newStyleAttr +" "+hasStyleAttr;
        }

        $(this).attr('style',newStyleAttr);
    });
```

As I tested, everything works very well, all 300 ms delays gone on all elements. But I want to ask , is it the correct way what I am doing ?

**Comment by arschmitz** [comment]
This is the issue tracker for hammer.js not hammer-time. As far as the "right way" to do this thats kind of up to you this is not something i like to blindly apply and if your going to i would use manipulation not none.
