### ISSUE TITLE
Always on Global Window

### ISSUE THREAD

**Issue by nwhite89** [hammerjs/hammer.js#921]
I am looking to use Hammer JS but I don't want to assign Hammer JS to the Global scope `window`. Also it is possible for Hammer to have already been loaded I was looking through the code, it seems to suggest this should be possible but I'm wondering if there is a reason it's not been done so far?

https://github.com/hammerjs/hammer.js/blob/master/src/expose.js#L57

On this line here it suggest `freeGlobal` however, if you don't provide window at all which means it will always be set to the window scope as freeGlobal is either window or self (basically the same) however, it then reassigns to window by `window[exportName]` if `define` or `module.exports` isn't supported which suggests it shouldn't be on the window scope at that point?

I'm happy to make a PR to change this (which effectively is removing the line (https://github.com/hammerjs/hammer.js/blob/master/src/expose.js#L58)

But I'm not entirely sure if there is a particular reason for this?

**Comment by runspired** [comment]
The reason for this is that `define` is not always the `define` you might think.
