### ISSUE TITLE
advice for http://hammerjs.github.io/

### ISSUE THREAD

**Issue by yalishizhude** [hammerjs/hammer.js#924]
When my phone visit the website http://hammerjs.github.io/, it loads very slowly.I find there are some images uncompressed,so I strongly advise you compress all imagess like pano-1,pano-2 and so on.
thx~

**Comment by matchai** [comment]
Besides compressing them, the images only appear to be used with a maximum height 200px, despite being 1872px in height.

The total website size is 25.5 MB, while the images alone are 25.1 MB.
One solution would be to simply reduce the image sizes so their heights match the 200px maximum height applied to them.

**Comment by arschmitz** [comment]
@matchai this is not the place for this the website has its own tracker. Also if you look the images are used for zooming demos so they must be very large
