### ISSUE TITLE
Recognizers on outer element are triggered before events on inner element

### ISSUE THREAD

**Issue by jeron-diovis** [hammerjs/hammer.js#926]
```html
<div id="outer">
    <div id="inner">
        touch me
    </div>
</div>
```

```js
const hammertime = new Hammer(document.getElementById("outer"));
hammertime.on("tap", () => console.log("tapped"));
hammertime.get("tap").set({ 
   enable() {
     console.log("outer recognizer");
     return true;
   }
})

document.getElementById("inner").addEventListener("touchstart", () => console.log("inner touchstart"));
```

On touching text I get logs:
```
> outer recognizer
> inner touchstart
> tapped
```

1. How it is even possible?
2. How can I prevent any interactions on `#inner` div from being recognized on `#outer` div? `stopPropagation` in my `touchstart` handler does just nothing.

**Comment by runspired** [comment]
This isn't a bug, for support please see the Slack channel.  TL;DR version, DOM events go through two phases, capture and bubble, and the primary listener (for touchStart mouseDown) is attached to `window` with capture semantics.
