### ISSUE TITLE
Pointer-Events support

### ISSUE THREAD

**Issue by nexflo** [hammerjs/hammer.js#946]
Might make sense - IE jumped on the bandwagon and firefox and chrome are implementting it as well.

Gains additional fields like pressure, tilt, etc.

https://mobiforge.com/design-development/html5-pointer-events-api-combining-touch-mouse-and-pen

**Comment by arschmitz** [comment]
We support pointer events already https://github.com/hammerjs/hammer.js/blob/master/src/input/pointerevent.js
