### ISSUE TITLE
Scroll isn't disable on drag events with iOS 9.3

### ISSUE THREAD

**Issue by adrienbecker** [hammerjs/hammer.js#952]
Hi everybody,

Scroll isn't disable on drag events with iOS 9.3.
I have compared with old ios version and all it's good !

Best,

Adrien

**Comment by arschmitz** [comment]
Thank you for reporting this. Im already working on a patch for it. This is because of iOS incomplete implementation of `touch-action` we now need to not just check if its supported but if it supports none

**Comment by adrienbecker** [comment]
Ok ! Thanks @arschmitz for your precisions

**Comment by simonwidjaja** [comment]
Hey guys. What is the best way to interim fix this? 
(BTW: Keep up the great work!)

**Comment by arschmitz** [comment]
im not sure there is a simple fix working to get this fixed but been busy hope to get it done this weekend

**Comment by adrienbecker** [comment]
Read last message ! https://bugs.webkit.org/show_bug.cgi?id=149854

**Comment by arschmitz** [comment]
@adrienbecker thats unrelated to this but thank you

**Comment by adrienbecker** [comment]
![failed](https://media.giphy.com/media/uIeAJ5LVIQ5ji/giphy.gif)

**Comment by arschmitz** [comment]
@adrienbecker no worries that was the cause with some issues in some of my other libraries not totally off base or anything just not this particular issue. Thats for touch-action manipulation to work. In your case touch action none is the issue which is just not supported by webkit at all. We fake it when its not supported. Problem is we check for support of touch-action as a whole not the individual props since we never expected someone ( apple ) to implement just one value and not the rest.

**Comment by jtangelder** [comment]
I guess this can be checked with `CSS.supports('touch-action', 'none');`. But I don't have an iPhone to confirm that this will work. Do you @arschmitz? This will be an easy fix then. In touchAction.js is a condition to detect native support, we could easily enhance it.

**Comment by jtangelder** [comment]
https://github.com/hammerjs/hammer.js/pull/955 a PR, can anyony verify this fix?

**Comment by runspired** [comment]
@jtangelder I have an iPhone but I've avoided upgrading to 9.3 due to this... :/ 

Guess I need to take the leap?

**Comment by arschmitz** [comment]
@jtangelder @runspired i have one upgraded @runspired see comment on #955 though

**Comment by adrienbecker** [comment]
@arschmitz Great ! It works fine :)

**Comment by adrienbecker** [comment]
Can you update the npm package ?

**Comment by arschmitz** [comment]
We will do a new release with this and some other fixes some time this week i would think.

**Comment by jbach** [comment]
Any updates on the npm release?

**Comment by adrienbecker** [comment]
#956 is always open

**Comment by zakness** [comment]
For anyone coming across this, a quick fix might be to call `event.preventDefault()` in your handler. This has worked for me for `pan` and `pinch` (haven’t tried others).
