### ISSUE TITLE
Unable to drag hammer element

### ISSUE THREAD

**Issue by fsjoyti** [hammerjs/hammer.js#953]
![captureew](https://cloud.githubusercontent.com/assets/10965471/14116967/058a3fec-f5a8-11e5-8356-2aa4dbec4e00.PNG)

I am trying to implement a drag event for my hammer object but so far it is not eve detecting the touch event . I am not sure what I am doing wrong

**Comment by arschmitz** [comment]
Hammer.js 2.x does not include the drag event it was removed.
