### ISSUE TITLE
Hammer.Manager undefined in Meteor 1.3

### ISSUE THREAD

**Issue by csellis** [hammerjs/hammer.js#959]
Getting the following error:
`TypeError: Cannot read property 'Manager' of undefined`

Hammer is installed and I try to instantiate it in the following example:

```
Template.mobileSwipe.rendered = function() {
		var height = $('#my-content').height();
		console.log('Height: ' + height);


		var stage = document.getElementById('swipe');
		console.log(stage)
		var mc = new Hammer.Manager(stage);
		var Rotate = new Hammer.Rotate();
		mc.add(Rotate);
		mc.on('rotate', function(e) {
			var rotation = Math.round(e.rotation);

			stage.style.transform = 'rotate('+rotation+'deg)';
		});

	}
```

It keeps failing on the var mc = new Hammer.Manager(stage);

**Comment by arschmitz** [comment]
You have not loaded Hammer `Hammer is the `undefined` variable there. You need to make sure you have loaded hammer and have a valid reference to it. Im going to close this since it does not appear to be a problem with hammer but that you have not loaded it properly.

**Comment by yehr59** [comment]
You need add npm package : 
**`npm install hammerjs`**

and if you want use velocity in Hammer you need this package : 
**`meteor add velocityjs:velocityjs`**

It's resolve my Hammer problems.
