### ISSUE TITLE
prevents the use of save image context menu on ios in safari/chrome

### ISSUE THREAD

**Issue by kurtharriger** [hammerjs/hammer.js#963]
On ios if you press and hold an image for 2 seconds you will get a context menu with the options 'Save Image' and 'Copy'.   Using react-hammerjs wrapper component I'm trying to capture the swipe, pinch and pan events, this works well but I discovered that I can no longer save the image to my photo library which is essential to my use case.  I tried a few techniques to try to get this context menu to appear programmatically, but nothing seems to work on ios.  

I'm thinking maybe just conditionally wrapping my image in Hammer on standard click event to enable gestures and then unwrap component on tap event to re-enable default browser behavior to save images. But I thought I would raise the issue in case there is a simple fix I'm missing.

**Comment by runspired** [comment]
This is because on iOS we must polyfill touch-action, and to do so we `preventDefault`, there are ways (see docs) to avoid calling preventDefault.
