### ISSUE TITLE
Touchpad on Macbook Tap issue

### ISSUE THREAD

**Issue by kloining** [hammerjs/hammer.js#968]
The Tap recognizer works fine on iPhone, iPad, Windows (with mouse), but I see a strange behaviour in tap behaviour on my Macbook Pro touchpad.

To get the Pan action to trigger as a single tap, I have to:
1. click and release
2. move the cursor before the timeout

This because the trackpad sends a isFirst: true on click, and then fires isFinal:true when the mouse is being moved again - after the click.

**Comment by kloining** [comment]
As a temporary fix, which I haven't tested too much, This is my result in TapRecognizer (from line 2068)

`if ((input.eventType & INPUT_START) && (input.pointerType != "mouse") && (this.count === 0)) {
    return this.failTimeout();
}
else if ((input.eventType & INPUT_END) && (input.pointerType == "mouse") && (this.count === 0)) {
    return this.failTimeout();
}

// we only allow little movement
// and we've reached an end event, so a tap is possible
if (validMovement && validTouchTime && validPointers) {
    if (input.eventType != INPUT_END && (input.pointerType != "mouse")) {
    return this.failTimeout();
}`

**Comment by arschmitz** [comment]
@kloining what version are you using? have you tried this with 2.0.8?

**Comment by kloining** [comment]
Yes, I'm using the latest 2.0.8.
The behaviour is the same every time: I click on touchpad/or with a normal mouse, this triggers one "mousedown" event (with isFirst:true) and when I start to move the mouse, it fires a "mousemove" event with isFinal:true. It's the same in Chrome and Safari. I'm using OS X El Capitan 10.11.4, so this seems like a Mac behaviour,

**Comment by arschmitz** [comment]
@kloining can you please make a jsbin or similar test case. Did you see this same behavior with 2.0.6? or do you believe this is a regression?

**Comment by kloining** [comment]
I couldn't reproduce it in jsbin, and I discovered after lots of debugging that if you use Hammer inside a jQuery widget with ui.mouse enabled, _mouseinit() has a this.element.bind('mousedown' event, only triggering on macs (and overriding the default behaviour in Hammer). 

At last I figured out I had launched jQuery draggable on the same element..

**Comment by runspired** [comment]
This sounds like an event interop issue with another handler cancelling propagation.  Will reopen if confirmed otherwise, but I've used Hammer successfully on every platform mentioned in this thread.
