### ISSUE TITLE
Don't trigger swipe with native zoom

### ISSUE THREAD

**Issue by julmot** [hammerjs/hammer.js#969]
Assuming the following user requirements:

- Zooming should be enabled (pinch zoom) (Can be done with `{touchAction : "auto"}`)
- When swiping to the left/right on the body, a redirection based on the application history should be done (swiping to the right will open the last viewed view, to the left will open the next view)

I'm familar with how the swipe event should look like. But my problem is, that I want to prevent swipe from getting triggered when the user zoomed in or while he is zooming in. When zooming into the application and then swiping, the user expects that just the zoom viewport will change, no history event (swipe) should get triggered. He only expects history changes when he didn't zoomed into the app.

So, I know I can detect a pinch event with HammerJS too, but as far as I can see there is no way to detect the zoom level. Am I right? `event.scale` doesn't have the value `0` when there is no zoom, so I assume that this is something different.

**Comment by runspired** [comment]
browser level scaling is tricky to detect: http://stackoverflow.com/questions/1713771/how-to-detect-page-zoom-level-in-all-modern-browsers

`event.scale` here is something different.
