### ISSUE TITLE
There another way to set gesture and call a function without using .on() of jQuery?

### ISSUE THREAD

**Issue by Urahara** [hammerjs/hammer.js#974]
```
var mc = new Hammer(elemento);
mc.on("swipeleft", function(event) {
                 // action
 });
```

Is there any way to set function of event without using .on method of jquery? Is talking about set an atribute like "onclick" of input. Cause of this bug in chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=574343

**Comment by arschmitz** [comment]
Hammer does not use or depend on jQuery in any way its just a function with the same name

**Comment by Urahara** [comment]
Yeah, but there any way to assign the event "swip" in the input attribute?

**Comment by arschmitz** [comment]
no

**Comment by arschmitz** [comment]
Just to explain a little. Hammer events are not native events so even if we made this possible it would not help the issue described there. Hammer it self listens to a variety of native events using `addEventListener` and its just not possible or feasible to make hammer use attributes which is what would be required to fix the issue described there. 

I'm actually vary familiar with that issue as im also the lead of jQuery Mobile which is part of where that is being reported.

**Comment by Urahara** [comment]
wow! thanks for clarifying, this issue is really bad i hope that will be fixed soon.

**Comment by arschmitz** [comment]
@Urahara my understanding from others that are testing the issue on JQM ( i have not personally tested it yet ) is that its fixed in chrome 51 already
