### ISSUE TITLE
Hammer.js blocks scrolling on Safari iOS 9.3

### ISSUE THREAD

**Issue by ClementParis016** [hammerjs/hammer.js#977]
Using Hammer v2.0.8, scrolling is no more possible on Safari iOS 9.3.
Rolling back to v2.0.6 corrects the issue.

I've seen there is on this repo a branch named `fix-ios93` that seems to be addressing this specific issue.
Are you planning to merge it or provide an other fix?

**Comment by arschmitz** [comment]
can you please create a jsbin or fiddle demonstrating the issue? that branch was not merged because we fixed it in a different way.

**Comment by ClementParis016** [comment]
Sure, I will do it on Tuesday when i will be back to work.

**Comment by ClementParis016** [comment]
@arschmitz, here you go: https://jsbin.com/mocoxur/edit?html,js,output

Using an Hammer Manager prevents scrolling on iOS (Safari, couldn't test others). If you use a simple hammertime, it works:

```js
var hammertime = new Hammer(document.querySelector('body'));

hammertime.on('swipeup', function() {
  console.log('swipeup');
});

hammertime.on('swipedown', function() {
  console.log('swipedown');
});
```

This is how I solved the issue, but I guess it should work when using a Manager too?

**Comment by arschmitz** [comment]
@ClementParis016 its expected to block scrolling when using swipe up and down v2.0.6 had a bug that allowed it.
