### ISSUE TITLE
Pan doesn't check for threshold after pinch

### ISSUE THREAD

**Issue by casperlamboo** [hammerjs/hammer.js#980]
This is probably intended behaviour but I was wondering if there is a way around this.

I'm working on a drawing app in which I use HammerJS. I use pinch/2 pointer pan to zoom to drag the canvas around. I use the single pointer pan for various tools such as a freehand and a eraser tool. Currently the drag sometimes is triggered immediately after the user finishes a 2 pointer event which causes a line to be drawn or part of the drawing to be erased. I was wondering if it is plausible to setup hammer in such a way that the threshold has to be acquired again after a 2 pointer event.

**Comment by casperlamboo** [comment]
I've written a small example to show the problem I'm encountering. This is basically an extremely stripped down version of the app I'm making.

It listens to 3 events.
 1. `1 pointer pan, drag` this draws a shape
 2. `2 pointer pan, multitouch` rotates, scales and translates all drawn shapes
 3. `tap` clears the screen

Sometimes after a multitouch event a drag event is triggered and a line is drawn.

To run the example clone the [project](https://github.com/casperlamboo/HammerJS-Example) and run `npm install` and `npm start`. `npm start` starts a server on port 3000.

**Comment by casperlamboo** [comment]
I've recorded myself using the example.
![vid_20160520_121408_rotated_cut](https://cloud.githubusercontent.com/assets/6638028/15425364/148615d0-1e88-11e6-98cf-e0d3054e3a70.gif)

**Comment by runspired** [comment]
@casperlamboo you are correct in Hammer's current limitations, however, this is a behavior I'm working in enabling for 3.0.
