### ISSUE TITLE
"pan" triggered without "panstart" after window resize

### ISSUE THREAD

**Issue by argelius** [hammerjs/hammer.js#986]
I noticed a weird bug where "pan" is triggered before "panstart" after the window is resized.

### Platform
Chrome 50.0.2661.102 (Official Build) (64-bit)

### How to reproduce

In this Codepen if you resize the window and then quickly pan the "pan" event is triggered but not the "panstart" event.
http://codepen.io/argelius/pen/rLNMYm

**Comment by runspired** [comment]
@argelius I cannot reproduce this with your codepen. Willing to reopen if you help me replicate.
