### ISSUE TITLE
Hammer PAN event is not working in IE 11 touch device in windows 8 

### ISSUE THREAD

**Issue by vikashsd** [hammerjs/hammer.js#996]
Hello Team,
With any version of hammer.js ,The PAN event in IE 11 in windows 8 device its not working.

Kindly look into that.can u suggest?

**Comment by runspired** [comment]
Please provide a working replication of this, because we do test IE11 and it is known to work correctly.

**Comment by vikashsd** [comment]
Hello Team,

Thank you so much  for reply.

Have a great time to you!!!

I am replying late because your mail came into spam.

For div element the PAN event is working in IE 11 touch windows device but
its not working for SVG element.

OS: Windows 8
Browser: IE11
Element: SVG Element
Device:  Windows touch tablet
Event: PAN event is not working


I will provide the replication of issue soon.

Have A Good Day!!


Regards,
Vikash Singh
Software developer Siemens
Mob:+91 9738230144

**Comment by vikashsd** [comment]
Hello ,

Kindly find recorded  replication of the  issue ​
 VID_20160715_155014.mp4
<https://drive.google.com/file/d/0B0YnDWTNQ_vxOTRzbDVneGZ5M2c/view?usp=drive_web>
​
Regards,
Vikash

**Comment by vikashsd** [comment]
Hello,

Kindly update on the issue.


Regards,
Vikash

**Comment by runspired** [comment]
While the video is nice, without demo code it's not a valid replication, any number of other things could be producing this error.

Based on your further feedback on this being specific to `svg`, it also seems likely that this is either a duplication of https://github.com/hammerjs/hammer.js/issues/906 (which has a simple fix but needs an implementor).

**Comment by vikashsd** [comment]
Hello ,

Thanks for reply!!

I am sharing you same source code of demo replication ,for that replication
video was created.

I think the issue #906 is different from this.


<html>
<script src="hammer-2.0.7.js"></script>
<style>
#Element {                                 // style for div element
  background: silver;
  height: 300px;
  text-align: center;
  font: 30px/300px Helvetica, Arial, sans-serif;
}
</style>



<div id="Element">
<svg width="500" height="350" id="outerSVG">
<text x="0" y="45" width="50" height="50" fill="red" id="svgText">SVG
sample!</text>  // Attaching event with SVG Text Element.
</svg>
</div>

<script>
    var mySvg = document.getElementById( 'svgText' ), // getting SVG
element
    mc = new Hammer( mySvg );

    mc.get( 'pan' ).set( { direction: Hammer.DIRECTION_ALL } );

    mc.on( "panleft panright panup pandown tap press", function ( ev ) {
        mySvg.textContent= ev.type + " gesture detected.";
        console.log( ev.type + " gesture detected." );
    } );
</script>




</html>

Kindly find in attachment.


Have A Good time !!


With best regards,
Vikash Singh
Mob: 9738230144

**Comment by vikashsd** [comment]
Hello,

Kindly update about this issue , Are you going to fix in next version.


Regards,
Vikash

**Comment by runspired** [comment]
@arschmitz I do think that this is likely an IE11 representation of the Firefox issue seen in #906 

I put his example here but lack a test device atm.

https://jsfiddle.net/9ufvvgds/7/

**Comment by vikashsd** [comment]
Hello Team,

Kindly update, when this can be fixed from your side.

Similar issue id #46 has been raised.


Regards,
Vikash

**Comment by AmyBlankenship** [comment]
This issue also seems to be causing a problem in vis.js when you click the vertical scroll bar in some versions of IE. You can't let go after that.
