### ISSUE TITLE
Current Branch labeled as 2.0.8 but actual js files are 2.0.7

### ISSUE THREAD

**Issue by nicholasbg** [hammerjs/hammer.js#997]
If you go here you'll see the version is 2.0.7 but should be 2.0.8.

https://github.com/hammerjs/hammer.js/blob/master/hammer.js

Same issue with the minified file and possibly other files (didn't check everything).

**Comment by arschmitz** [comment]
Hi thank you the files are correc and contain the 2.0.8 code. The header just did not get updated. Thank you for pointing this out.

**Comment by runspired** [comment]
@arschmitz confirm this is a "won't fix" as it's a non-affecting issue and fixing it would just require another patch bump :trollface: ?

**Comment by neiljeffries** [comment]
Hello from 6 years the future :),

We are using hammerjs v2.0.8 in an Angular project.

Our enterprise security scanner continues to find v2.0.7 even though we are using v2.0.8.

After several rounds of deleting the node modules folder, uninstalling/reinstalling hammerjs v2.0.8, the scanner continued to insist we were using 2.0.7.

Then I finally found the reason... Version 2.0.8 still contains references to v2.0.7 in node_modules\hammerjs\hammer.js. **After stumbling upon this post I now know how this came to be - lol.**.

I'll either have to convince our security team to defer this or we will have to figure something else out.


```

Hammer.VERSION = '2.0.7';

/*! Hammer.JS - v2.0.7 - 2016-04-22
 * http://hammerjs.github.io/
 *
 * Copyright (c) 2016 Jorik Tangelder;
 * Licensed under the MIT license */
```

**Comment by runspired** [comment]
None of us have had time for this project for years, though I keep hoping someday I'll work on mobile web again and have the opportunity to come back to it. Probably due for a new release to take advantage of modern APIs. If you want to take that on it would also fix the release issue ;)
